* Basic English: Book 1
lessson twenty-five   My Father 
 My father does the same thing every morning. He gets up  at six o'clock . He washes ,brushes his  teeth and combs his hair. Then , he puts on his clothes  and 
  eats breakfast. At six thirty he listens to the news on the radio. At exactly  seven o'clock  he leaves the house. My father has very regular habits. 
  
  
Lesson twenty-six  He usually plays Tennis 
 What do you usually  do on Sundays?
 I usually go for  a walk  in the mountains.
 Does your husband go with you ?
 No. He doesn't. 
What does he do?
He usually plays tennis. 



Lesson twenty-seven  Jack and His dog  | here aug31

  Jack  seldom gets togethre with his friends. He  usually stays at home with  his pet dog, luckly . 
The somethimes go for long walks  in the park. Although jack is often alone, he is never lonely. He always tells  his friends 
that a dog is man's  best friend.

Lesson twenty-eight I Always Walk 
How do you  go to school, Judy?
I usually take a bus, but somethmes I ride my bicycle. What about you?
I live near our school,so I always walk.
You're luckly.

 Lesson twenty-nine Poor Dick 
  There are holes in  Dick's shoes. He  needs new shoes. Dick doesn't want cheap shoes. He wants expensive shoes, but he doesn't have any money. He needs a job. He is looking  for one, but he isn't having any luck. No one wants to give him a job because his shoes have holes in them. Poor Dick. 

Lesson thirty  Money  Doesn't Grow on Trees 
Mother, can you  buy me a new bike?
NO,Sam. I can't.
But all my friends have new bicycles.
You cat ride their bikes.
Why can't I have a new bike?
Because money doesn't grow on trees.

Lesson thirty-one  Poor Amy 
 Amy can't  pay this month's rent. She needs some help. Unfortunately , none of her friends  can help her. They
don't have any money, either. Poor Amy is really  depressed. She has no money,and the landlord is knocking at the door. Amy is very nervous. She shouts ,"No none is home!"


Lesson thirty-two Do You Have Any Change 
Hi, Connie! Do you have any  change?
What for ?
 I need some coins to buy  a snack from  the vending machine.
I see. Here you are!
 Thank you.
You're welcome!

Lesson thirty-three She wants to Wear Something Formal 
  Judy is looking for something nice to wear for a job interview. She wants  to wear  something formal. 
Unfortunately, she doesn't have anything except casual clothes. Judy is worried. She has nothing suitable to wear, so she puts on her best casual  clothes. She goes to the interview. Guess what? Judy gets the job!


Lesson thirty-four Let's Go Clubbing
Hi,Paula! What are you doing ?
Nothing special!
Let's do something together.
Do you have anything in mind?
Let's  go clubbing!
Great!Can you handsome brother come,too ?

Lesson  thirty-five  There's  Little Food
 Fred's having a party, but he's very embarrassed. There are many people at his party, but there's very little food.
There's very  little meat. There isn't much  rice ,either. There are only a few cans of coke and a little orange juice. However, everyone is happy at the party because there's plenty of beer.


Lesson  thirty-six A Lot of Bills 
Do you have any money with you?
Not much. why?
I need to borrow some.
What's the matter?
I have a lot of bills to pay this month. 

Lesson thirty-seven  A Wonderful Time
  My girlfriend and I had a wonderful time last night. First, I took her to a cozy restaurant  for dinner. Then, 
we went to a  concert.Finally , we had some coffee at a nearby cafe. Just before we parted, she gave me  a good-night kiss. At that moment, I was on top of the world. And now I'm in love.

Lesson thirty-eight  Nobody Answered the Phone 
Ryan and Jane are brother and sister.
Hi,Ryan,where did you go last night?
I stayed home. Why?
I called you many times, but you did not answer your phone.(助动词后动词用原型 所以 answer)
Oh ,sorry ! I switched my phone  to silent mode before dinner. I probably  forget ot reset it. 

Lesson thirey-nine  Homesickness 
   After  my graduation, I went to Beijing to further  my studies. I lived there for  three  years. At first, I was happy, but later, I was frustrated  and depressed. I was   homesick all the time. Although the people were friendly , I missed my family , my  friends and  the lifestyle in my hometown.

Lesson forty  Everybody  Spoke English 
 Welcome back! What was America like?
OK, I guess.
What do you mean by "I geuss?"
Well,frankly speaking, it was terrible.
Why ?
Everybody only spoke english.

Lesson forty-one Going Camping 
  Last weekend, my  classmates and I went camping . We found  a  grassy spot beside a  river.We put up our tents and made a campfire. Then ,we fished at the river. We had only one fishing rod, so we took turns. After a while, we caught a  big trout. Finally, we sat around the fire, roasted the fish and sang songs. Camping  is really fun!

Lesson forty-two Are You Having Fun?
 How often do you go camping?
This is my first time.
Really? Are you having fun?
Yes, I'm having a wonderful time.

Lesson forty-three  Killing two Birds with One stone
  Dan must take a day off tomorrow. He has to take care of his sick mother. He ought to talk to his boss, but he's afraid. His boss might get angry with him. What should Dan do ? He can take the work home. This way, he can  kill two birds with one stone.

Lesson forty-four  She Had a Bad Cold 
Where were you yesterday?
I was at home. In fact, I was taking care of Sally.
What's wrong with her?
She had a bad cold.
Is she getting better?
Yes Thanks.

Lesson forty-five What a Nightmare!
  Jeff had a  terrible day. He missed the train to  work. Moreover, he had  to wait a long time for the next train. As a matter of  fact, he waited for two hours. To make matters worse, he left his briefcase on the train. As a result, he had to go to the police station. Poor Jeff never got to work that day. What  a nightmare!

Lesson forty-six   A Terrible  Headache 
Do yoy have any aspirins?
In face, I don't , why?
 I have  a terrible headache.
well ,you should go see a doctor immediately.

Lesson forty-seven  Be Polite 

  Everyone should  be polite. Polite people show good manners. Moreover, they are popular. On the other hand, rude people are looked  down upon. Rudeness shows poor education. Therefore, why not be polite? A simple "Please" "Thank you" or "You're welcome" can make a big difference.

Lesson forty-eight  Don't Mention It
Excuse me, Chris.Could you pass me the sugar,please?
Sure, Here you are.
Thanks. 
Don't mention it. 

Lesson forty-nine Never Talk  to Strangers 
  Something strange happened to me  yesterday. on my way to school, I met a stranger. He stopped me and said,"You are betty, aren't you?" "No," I replied. He asked,"You know me , don't you?" "I don't," I answered. Then he said,"You owe me $100, don't you?" I ran away. At that monent, I remembered my  mother's words:" Never talk to strangers."

Lesson fifty You're Sally, Aren't  You 
Excuse me. You're Sally,aren't you?
Yes
Hi,I'm George. You remember me,don't you?
No.
We met at Bill's party.
Now I remember.Nice to see you again. 

Lesson fifty-one  My Girlfriend
 My girlfriend always complains. According to her, I should be more  ambitious.I should work harder and earn  more money. She also thinks I should live in a bigger and nicer apartment. In a way, she's right. However, she should be more considerate and less criticlal .After all, I am  trying  my best. Besides, money  isn't everything.

Lesson fifty-two Sam's OK 
Do you like Ray or Sam?
I like Ray.
Why?
Sam's OK, but Ray's taller, cuter and more interesting. What about you?
I like Same better.
Why ?
He's less proud. Besides, he's richer!

Lesson fifty-three  country Life
  My parents  perfer to live in the country . The streets  there  are cleaner. The air is  fresher and the people are nicer and friendlier. Besides. it is  busier and noisier in the city. But above all, it is safer to live in the country. My parents believe in the saying, "Safety first"

Lesson fifty-four I Like Brighter Colors 
Do you like my new dress ,Mike?
Frankly, I like brighter colors better.They make you look younger.
Do darker colors make me look older?
Well...yes.
Then, buy  me another dress.

Lesson fifty-five  More Is Not Always Better 
  Some people have more money  than others.However, they're not necessarily happier. On the other hand, some people are as poor as church mice, but they  are happy. In a way , these poor people are as rich  as kings. Therefore, I always remember my father's  words, "More is not always better."

Lesson fifty-six  I want the  Cheaper One 
Why  is this watch  more expensive  than that one?
Because its brand name is more famous.
Is it more reliable?
No, Not really
Then, I want the cheaper one.

Lesson fifty-seven  The  Elephant and The Whale 
  The biggest  and strongest animal on land is the  elephant .The largest and heaviest animal in the sea  is the whale. It's  also  the biggest  eater in the world. It eats a ton of food a day. It looks like  a fish, but it is really  a mammal . Although  the elephant and the whale   are both mammals, they  are indeed very different.

Lesson  fifty-eight  The Smartest teacher 
Which country is the biggest in the world?
Russia
Which country  has the  most people in the world?
China
Who is the smartest teacher in the school?
But.... you are the only teacher in the school.
I know.

Lesson fifty-nine My Best Friend 
 My best friend is the most  thoughtful  person in the world. When  I'm sad, he is the most sympathetic. When  I'm  sick, he is the most concerned. When  I'm  in trouble, he is  the most helpful. In fact, he is  the most  dependable person   in the world. He is the cosest person  to me.He is my father. 

Lesson  sixty  The Longest River in the World 
Which  is the longest river in the world?
The Nile
Which  is the biggest ocean in the world?
The pacific Ocean.
Which  is the best school in the village?
But... this is the only  school in the village, sir.
I know.

Lesson sixty-one The Hare and the turtle 
   The hare can run very fast, but the turtle can only  walk slowly. One day  the hare proudly  challenged the turtle to a race. The  hare started quickly  but stopped to take a nap   every now and then. The turtle walked  slowly  but surely. While the hare was sleeping , the turtle  passwd him.  Finally , the turtle  won the race. In the  end ,  he was  rewarded for his   perserverance. We call all  learn  a lesson  form  the turtle. 

Lesson sixty-two  Practice Makes perfect 
Can you help  me gif-wrap this, please?
Sure.(after a while)
Wow!You did  that  beautifully .
Well, I practice daily.
Practice makes perfect, right?
Certainly!


Lesson sixty-three Saving a Drowning Boy 
 Ray  was walking on the beach one summer day when  he heard a little boy shout,"Help! Help!"  the boy  was drowing , Without  thinking, Ray dove into  the water, Soon he was swimming back to shore with  the boy. Crowds of poeple were watching eagerly. After a while  the boy  was  breathing agein. Then  the boy sat up and said   TO Ray, "You are my hero"

Lesson sixty-four Dan's  a good swimmer 
Dan's  a good swimmer, isn't he?
Yes, In fact, he's a lifeguard.
Wow! Can he teach me the butterfly and the  backstroke 
Yes,He can  also  teach you the free style  and the  breststroke.
Greeat

Lesson sixty-five 

* Advanced English 

** Lesson one Let's Visit New York?
  New York, New York.
  These  words were used to describe  New York when it was  by far the largest,richest, and most  developed city in the United States. New York still remains the largest and most famous city in the U.S. today, but some of its"nice" reputation has fallen over the past thirty years with  stories of  rampant  crime making headlines around the world. How true are these stories? Is New York still a "nice" place to visit? if so, what can a tourist do in New York? Let's  take a closer look  at America's premier[prɪˈmɪr] 第一 city.



premier    美: [prɪˈmɪr] 英: [ˈpremiə(r)]

    n.总理；地区总理
    adj.首要的；最著名的；最成功的；第一的
    网络首相；拍得丽；首位的



** Lesson twenty-four  Coffee  or Tea Break?
  Do you prefer a coffee break or a tea break? Are  you getting off  the lift at the  groud floor, or are you going  to get off the  elevator on the first floor? Travelers to  English-speaking countries have to   adjust  to differences between  British  and American  English . There are also 

adjust    美: [əˈdʒʌst] 英: [ə'dʒʌst]

    v.调整；调节；适应；习惯
    网络校正；校准；使适应




** Lesson two  The amish 
  In the land of  rock and roll, the space shuttle, computerized living, who could imagine  that  about 50,000 Americans do not use  telephones, electric lights, or cars, not  because  they  are poor, but out of choice? As hard as this may be to imagine, the American, or more properly, the Amish Mennonites, still  live a traditional, rural 美: [ˈrʊrəl]  乡村的 lifestype direct from  17th century Europe?
  To understand these unique Americans better,it is  necessary to understand  their history. Beginning with the   revolution  started  by Martin Luther , Leader of the Protestant Reformation in  Germany   in the  16th century, 






rural  美: [ˈrʊrəl] 
    adj.乡村的；农村的；似农村的
    网络乡下的；田园的；乡村风味的

** Lesson 3  indoor pollution 
   So you  think  that  by staying at home  you are safe from all the terrible kinds   of pollution present  outdoors,  such as  in  or near factories, roads, and garbage dumps? Do you  think that by staying in your office you are breathing cleaner, safer air than when  you go outside fou lunch  or are on  the way back home from work?Think again . Recent research done at the University of Texas has shown  that staying indoors  may actually be  more harmful to  one's  health than   being  outdoors even in  smoggy cityes.

present  [ˈpreznt , prɪˈzent] n.  目前;现在;礼物;礼品  adj. 存在;出现;出席;在场;当前的;现存的
smoggy  [ˈsmɑːɡi] adj.烟雾弥漫的
take office  入职
The man  will take office on the first  of  the month
in one's way  挡路  hey ,evan ,don't stay  my way                                                                
On her way to the library,Mary ran into Peter. 
Recent(不可数) research(which was ) done

  Apparently ,we are  safe neither at home  nor in the business office.We use  water  in both  place, but the above-mentioned research   shows  that  chemicals added to our local water supply to kill harmful bacteria can have unwanted side effects.These  chemicals can cause potenital harm through  dranking  and in seemingly  harmless activities as cleaning  one's  house.  These  additives are released from water by daily  actions like  water running out of faucets , spraying from garden  hoses, or splashing in dishwashers  and washing machines.As the water is agitated, these  chemicals are released into   the air  and then  breathed in . Once  inside our bodies,they start to affect our health adversely.

addicted   美: [əˈdɪktəd]       adj.上瘾了的；入了迷的；沉迷于…的      网络上瘾的；成瘾；中毒
addiction     美: [əˈdɪkʃ(ə)n]      n.瘾；嗜好；入迷  
apparently   美: [əˈperəntli]       adv.显然；可见；看来     网络显然地；明显地；表面上
perspective    美: [pərˈspektɪv]       n.观点；远景；景观；透视法     adj.(按照)透视画法的；透视的
chemicals  [ˈkɛmɪkəlz] n. 化学制品;化学品  chemical的复数
bacteria  [bækˈtɪriə] n.细菌  bacterium的复数
potential  [pəˈtenʃl] adj.潜在的;可能的 n.可能性;潜在性;潜力;
additives  [ˈædətɪvz] n.(尤指食品的)添加剂，添加物  additive的复数
release  [rɪˈliːs]  vt.  释放;放出;放走;放开;松开 公开;开放 n.释放;获释;公开;发行;发布
faucets  [ˈfɔsəts] n. 龙头;旋塞 faucet的复数
spraying   [ˈspreɪɪŋ] v. 喷;喷洒;向…喷洒;向…扫射(或抛洒);
hoses  [ˈhoʊzɪz] n. (灭火、浇花等用的)橡皮管，塑料管，水龙带;(旧时的)男式紧身裤 v. 用软管输水冲洗(或浇水)
splash  [splæʃ] v.泼洒;哗啦哗啦地溅;噼里啪啦地落;把(水、泥等)泼在…上，溅在…上;朝…上泼(或溅);
agitate  [ˈædʒɪteɪt] v. 摇动(液体等);搅动;激怒;安;使激动
adversely [əd'vɜ:slɪ]  adv.反而 不利地；有害地
 added to     That dress  add  to you  beautiful 那件衣服使你更加美丽
 Unfortunately,He is a drug addict 

  Does  this  mean   we should stop  bathing? No, say the scientists, but we should  put all pollution  into  perspective [pərˈspektɪv]  观点 洞察. Activities at home such  as the  burning  of propane, coal, cooking  oil, or even  candles and incense release  carbon monoxide  and particulates  such  as soot  which  have been proven as harmful to healthe as working or living  near high-density traffic. New rugs, bedding, and even clothing give off that "new smell," which is a sure sign of chemicals. In the office,newly  applied paint, newly purchased telephones and other telecommunications equipment, and computers and their peripherals release polluting chemicals, too.  As offices  and homes often  have inadequate ventilation, these chemicals can build up to become health nuisances. Their toxic effects  are only now being slowly recognized.

put all pollution  into perspective
The city is densely populated. 人口多  sparsely
sparsely  [ˈspɑrslɪ] adv.稀疏地;稀少;节省地   Desert  are sparsely populated

propane [ˈproʊpeɪn] n. 丙烷   coal [koʊl] n.煤;(尤指燃烧着的)煤块
incense [ˈɪnsens , ɪnˈsens] n. 熏香;香(尤指宗教礼仪用的)
carbon   [ˈkɑːrbən] n. 碳;碳（指导致全球
monoxide  [mənˈɑːksaɪd]n.一氧化物
carbon monoxide 一氧化碳  
particulates   [ˌpɑrˈtɪkjələts] n.微粒;颗粒;粒子 particulate的复数
soot  [sʊt]n.烟灰;油烟;煤烟子  v. 煤烟弄脏;弄得尽是煤烟
proven  [ˈpruːvn , ˈproʊvn]adj.被证明的;已证实的 v.证明;证实  prove的过去分词
high-density [haɪ ˈdensəti]adj.密度大的；高密度；致密的
rugs  [rʌgz] n.小地毯;垫子;(盖腿的)厚毯子 rug的复数
bedding  [ˈbedɪŋ] n.床上用品，寝具，铺
applied  [əˈplaɪd] v.应用;使用;施 请求;涂;敷  adj. 应用的;实用的 apply的过去分词和过去式
purchased  [ˈpɜːrtʃəst] v.购买;采购 purchase的过去分词和过去式
peripherals [pəˈrɪfərəlz] n.外围设备;周边设备 peripheral的复数
inadequate [ɪnˈædɪkwət] adj. 不充分的;不足的
ventilation [ˌvɛntəˈleɪʃən]n.通风;通气能力;通气量;通风设备
nuisances [ˈnusənsɪz] n 隐患.麻烦事;讨厌的人(或东西);妨害行为 nuisance的复数
toxic   [ˈtɑːksɪk] adj. 有毒的;引起中毒的 n.毒物;毒剂

  These  facts suggest that, at a  minimum, proper airing of  newly purchased goods with  an obvious chemical smell is a  wise precaution. Home  and office windows should be opened   during good weather to allow a flushing of stale air. Even  one's  car needs to be ventilated as well as the garage.

minimum  [ˈmɪnɪməm]  n. 最少量，极小量 （数量）极少的;最低限度的
proper  [ˈprɑːpər]adj.适当的;正确的;恰当的;符合规则的;真正的;像样的;名副其实的;符
airing  [ˈerɪŋ] 通风  播出 n.晾晒;晾;(意见等的)公开发表，公开讨论;透风 v. 晾;晾干;(使)通风，透风;
Right now, we are on the air,We are airing radio english on Sunday == We are broadcasting
wise [waɪz]adj.明智的;
precaution [prɪˈkɔʃ(ə)n] n.预防；预防措施；防备；避孕措施 v.使提防；预先警告
stale [steɪl]adj.不新鲜的;陈腐的;(空气)污浊的;(烟味)
ventilated [ˈventɪleɪtɪd]v.使(房间、建筑物等)通风;使通气;
garage  [ɡəˈrɑːʒ]n.停车房;车库;

 We need further  research  to understand better other potential health hazards, too. For  example , the effect  of  overcrowding of schools(carbon dioxide build-up),factory  work environments(an endless list of potentially dangerous substances). and even home heating and  cooling(the furnace and air conditioner may be our enemies, not our friends) have  only recently started to come to light. Until we understand the  effects of our new technological environment better , we can only hope that "there is no place like home."

further [ˈfɜːrðər]adj.进一步的;更多的;附加的
potential [pəˈtenʃl]adj.潜在的;可能的 n.可能性;潜在性
hazards [ˈhæzərdz]n.危险;危害 v.冒失地提出;
substances [ˈsʌbstənsəz]n.物质;物品;
furnace [ˈfɜːrnɪs] n.熔炉 暖炉
 
carbon dioxide CO2   [ˌkɑːrbən daɪˈɑːksaɪd] n.二氧化碳
primitive  [ˈprɪmətɪv]adj.原始的;远古的;人类或动物发展早期的;发展水平低的;落后的;原始本能的



手工打单词要记得的打下来 记住一个单词 然后写下 不要一个个字母的边看边打 


bookworm 书虫 


** Lesson four  Pizza,Please!
  One of the world's  most  popular foods   along with the hamburger, fried  chicken, and milk  shakes is pizza. Although the  origin  of the first  three  foods  is well understood, that of  pizza ---unitl recently, anyway--was for a long time  an internatinal controversy. 
  The word  pizza  has always been  known  to mean  pie or  cake,  and is an Italian word. This  fact  alone  might suggest pizza's origins.However, some  years ago  in New York City,a Chinese  restaurateur challenged the Italian ethnicity of pizza by declaring that pizza  was originally a  Chinese food, but was then  taken  along  with pasta by  Marco Polo  back  to Italy. It seemed the question  would  never be solved.
  The  case actually  made itself into court(only in America!)!Italian restaurateurs challedged  the Chinese businessman's  view, but when  all the evidence was in, the result was announced by a judge: as early  as the Roman Empire, pizza  was banked in  ovens there  and eaten. Chinese normally steam(蒸) or fry their foods, not bake them. Bread and other  baked goods to which  pizza belongs  were  developed from  India  through  Europe  where the are  still   enjoy  today. Besides,cheese is an essential element of pizza and the Chinese traditionally did not produce cheese. The case  was closed,and pizza's  paternity  has  now been established. 
  For pizza lovers, of  course, their favorite food might have been  invented in   Argentina or Indonesia. Who  cares? Indeed ,pizza has changed as it has spread around  the globe, so that when  ordering a pizza  in Honolulu,New York, Paris, Istanbul, New Delhi, or Tokyo, you are sure to receive a slightly different version   in each city or country.Pizza known to Italians and  New Yorks(wehre pizza was first introduced into the United States by the many Italian Americans living there) is a  round, thin-crusted baked dish covered with  tomato sauce and cheese. To improve the taste, pieces of Italian sausages such  as pepperoni  and salami意大利香肠, and vegetables like onions, green peppers and olives are added. Occasionally(有时), anchoves, small, salty fish, are also used. However, Asians enjoy pizza with corn, cucumbers黄瓜, and other vegetables, not to   mention  assorted  seafood.Hawaiians, perhaps predictably, developed a  pizza with a pineapple and ham topping.Today  , nearly every   country has its favorite local variety of pizza. Worldwide, there  must be more than  1,000 varieties of pizza.
  Some  people  are not so found of pizza. They  classify it as a junk food, along with  greasy French fries.potato chips, and hamburgers. On the  coutrary, say  defenders of piza, it  is indeed a healthful food.  Carefully  chosen fresh ingredients  can ensure 确保  the  the quality of any food we eat, and pizza is no exception.
  Other  protes that  pizza is too fattening to be eaten regularly. Not true, respond  those  enamored of (迷恋) pizza's charms. It all depends on  the ingredients and how  well they  are prepared.For example, the meats which  are used as toppings  on pizza are often first fried to remove excess fat. The cheeses used  can be selected for their high protein but low milk fat.Sparse rather than generous addition of  spices such  as salt ensure that pizza need not be considered junk food. A well-made pizza not only  looks,  smells, and tastes great, but it is a wise choice for everyone as  a regular food   source. Indeed, it seems  the only  disadvantage (缺点,不好的 ) to  pizza is that  when dropped, it causes a mess !
   Children enjoy   pizza  because  it's    fun to  eat and  delicious . Workers enjoy   it because it is  inexpensive and  quick  to order, too. Families  enjoy  the convenience  of carrying home a whole meal from  the many vendors fo this  world-famous  food. With  its many advantages , no one needs to resist the  allure  of one  of the world's  most popular foods. Come on  think of it, let's  have pizza for dinner tonight!

ensure 确保 
insurance 

local    美: [ˈloʊk(ə)l]
convenience    美: [kənˈviniəns]    n.方便；便利；适宜；便利的事物（或设施）
version [ˈvɜrʒ(ə)n]     n.描述；变体；变种；型式     网络版本；版本号；译本

allure [əˈlʊr]      v.诱惑     n.吸引力；诱惑力；引诱力     网络魅力；倾城之魅
exaggerate [ɪɡˈzædʒəˌreɪt]    v.夸大；夸张；言过其实

apple  pie 
 my  daughter is apple of my eye. 掌上明珠 
a piece of cake   == cinch  == so easy 
tea  a cup of tea . it not my cup of tea 不是我喜欢的 

pasta  [ˈpɑstə]     n.意大利面食 意粉；通心粉
fry [fraɪ] n.鱼苗；油炸物；〔英国〕油炸杂碎 v.用油炸烤炒；油煎；油炒；用油煎

established  [ɪˈstæblɪʃt]adj.已确立的；已获确认的；确定的；著名的    v.“establish”的过去式和过去分词 建立；建立的连接；已制定的

charm  [tʃɑrm]     n.风韵；妩媚；(迷人的)魔力；咒文     v.迷(人)；使喜爱；用魔法保护[治疗]；把(蛇等)养乖    词形：    charms     charming    charmed

burglary/theft

** Lesson  eleven   English  in the caribbean 
Let's dancing to the beat.

  When  we hear  the  word  English, we  naturally  think  of  the  language  spoken by  those  living in the  United Kingdom  or of the people living  in England. We also  often think  of their language as the international language, the one spoken as a  native 本地 language in Ireland, the United States, Canada,Australia, and New Zealand  ,countries which  have had a close association 有关  with  England for centuries. However, English is  spoken as a native or second language in a  large number of other  countries which were once colonies(殖民地) of the  British Empire. 
  Latin America,  including Mexico, Central America, the Caribbeam, and South America, is often thought of as  a linguistically语言上  homegenous 同类  area of Latinate languages(those languages like  French, Italian, Portugueses, and Spanish   which originated from  Latin). This is generally true , as  the vast majority of poeple  there speak Spanish or Portuguese as  their  mother tongue. However, a number of small Caribbean  island nations were also  once  part of the British Empire;  accordingly因此,  their citizens  even  after independence speak English. These nations  include   Antigua and barbuda, the Bahamas, Dominica, Grenada, Jamaica,Barbados, and the Republic of  Trinidad and Tobago. 
  Do the Caribbean English  speakers speak British English? Not exactly.  All  over  the world where English has been spoken for hundreds of years by speakers of other languages, certain(一些) special accents 口音  or dialects have arisen(arise 产生). India is famous for "Indian English"; "Irish English" is  unmistakable, too. Likewise, Caribbean English  has its own  special patterns,  vocalulary, and even gramatical forms  different from  the standard RP(received pronunciation, also  referred to  as Received Standard) of British English . There special features include a lilt  or  "sing-song" sound to the language, and plenty of local slang.
  As only  a relatively few  people live on  these  inslands, how can we hear their  special dialect or accent?One kind of  pop music  called  reggae is the easiest way  outside of  befriending someone from these  naitons. Reggage music has been pupular since the 1980's, when performers like  Bob Marley of Jamaica pleasantly  surprised the world with  their own original reggae music  as  well as their  interpretations of other well-known pop Anglo music. Reggae is famous for  its strong, often syncopated beat, laid-back  singing style, and ,of course, the " island" dialect.  Another   perennial music  favorite is calypso,  which is  als sung in the Caribbean island English  dialect 方言. The hit song "Yes, We Have No Bananas," is reminiscent of 使人想起  this drum-heavy musical style,  especially from  Trinidad and Tobago. 
  Given the islands' historic ties to both the United Kingdom and the United States, it is  little wonder that today the peoples of  these  small  nations continue to use  English  in government, academia, business, and trade.Local [ˈloʊk(ə)l] languages still exist alongside  the Caribbean  English dialect , too. but they  are mostly  the  patois  of the marketplace and home. Many of the  residents of 居民  this area, also  referred to as  the West indies or the Antilles, have emigrated to  the U.K. or  the U.S. and , because of their  linguistic pwowess, have done  relatively well as so-called  "third world" immigrants. A few  writers of contemporary renown also  hail from  this area,  as do  some sports figures.
   If you  plan to  visit  any of the above-memtioned island  for  any purpose, do not  worry about  your language skills . Caribbean  peoples are well-known  for their  friendly , patient dispositions. After a few  days, your ear  will become  attuned to the liting  cadence of the lovely  Carbbean  English  dialects,and your  stay  in this tropical paradise will  be all  the more rewarding.

pattern    美: [ˈpætərn] 
    n.模式；方式；格局；型     v.给…加花样；照图样做；仿造；形成图案     网络模型；型态；句型
   
dialect    美: [ˈdaɪəˌlekt] 
    n.方言；语调；【语】语支；(某职业的)专业用语    网络乡土语言；本土语言；闽南语   
   
accent美: [ækˈsent]      n.口音；重音；重音符号；强调     v.强调；重读；给…加上重音符号     网络重音打击法；外来词发音；强调动作

certain    美: [ˈsɜrt(ə)n]     adj.肯定；确定；确信；无疑     pron.（不提及人或事物的名称时用）某些
    网络确定的；肯定的；一定的   


He's been in English with a heavy Japanese accent
他说的英语带有浓重的日本口音

patois    美: [ˈpæˌtwɑ] n.方言；土语；土


alongside    美: [əˈlɔŋˌsaɪd] 
prep.在…旁边；沿着…的边；与…一起；与…同时
adv.在…的侧面；与…并排


received    美: [rɪˈsivd] 

Caribbean    美: [ˌkerɪˈbiən] 
adj.加勒比海地区的；加勒比

linguistically    网络语言性；语言上；语言方面

generally    美: [ˈdʒen(ə)rəli] 
    adv.通常；大体上；一般地；普遍地
    网络通常地；广泛地

native    美: [ˈneɪtɪv] 
    n.本地人；当地人；出生于某国（或某地）的人
    adj.出生地的；儿时居住地的；本地的；当地的
    网络原生；本国的；本土的
 
colony    美: [ˈkɑləni] 
    n.殖民地；【动】(鸟,蚁,蜜蜂等的)集团；【生】群体
    网络集落；殖民区；菌落

central    美: [ˈsentrəl] 
    adj.最重要的；首要的；主要的；起支配作用的
    n.〈美〉电话总局；接线员
    网络中环；中心的；中央的

vast    美: [væst] 
adj.辽阔的；巨大的；庞大的；大量的
n.〈诗〉广大无边的空间；大海


pattern    美: [ˈpætərn] 英: [ˈpætə(r)n]

    n.模式；方式；格局；型
    v.给…加花样；照图样做；仿造；形成图案
    网络模型；型态；句型

Lesson twenty-four  Coffee or Tea Break ?
  Do you   perfer a coffee break or a   tea  break? Are you  getting   off th elift at the ground floor, or  

  

  value 


substantial    美: [səbˈstænʃ(ə)l]
adj.大量的；价值巨大的；重大

* Lesson fourteen Alpine Treasures
  From  the Atlantic Ocean  to the Ural Mountains  stretches the  continent of Europe. The most   striking geographic  feature  within  this densely-populated area is the Alps Mountain Range, commonly called  the Alps .The Alps voers most of Austria  and Switzerland as well  as significant areas of  areas fo German,France,and Italy. The  picture-perfect land and  lifestyle of the Alps contain many treasures for  all the peoples of the world . Who  hasn't dreamed of  visiting  the Alps  for a vaction ? If you  are lucky  enough  to vacation  in the Alps , what  delights await you ?
  The  ladies can look forward to dirndls  and Alpine  flowers . A dirndl is a special  Alpine  dress  worn  particularly by  the German-speaking  populations  of the Alps( in most of the Swiss and all of the German and Austrian areas). This long, often colorful and simple-patterned dress includes a full skirt, gathered  waist,and tightfitting bodice. Most women fall in love with  a dirndl  the momnent  they see one. Save up to buy  one, though. Most dirndls are  hand-made and rather pricey. Compared to the  cost of the intercontinental voyage to the Alps, though , a dirndl is well worth the expense. The wearer will have  a cool weather treasure  to wear for many years.
   If  dirndls are really to expensive, thouth, the hundreds  of species of Alpine flowers will also  delight not  only  women, but all nature lovers, for free. Of course, to see  these  botanical wonders, one must  visit the Alps during its relatively brief  spring through fall, that is, between June and September for most blossoms. The  hills are alive with tiny, multi-colored petals in  somethimes bizarre shapes. Don't touch  ! Most lpant species are protected by laws  carrying  stiff fines, even for unsuspecting tourists. Instead , theese natural  treasures are are available on the  many postcards or in the coffee table books  throughout the region. Taking one's  own pictures or movies in  an even better idea. With  luck, it is still possible to find  the rare edelweiss growing  on a mountain slope. Its yellow  center with  white  star-lkie petals has become an Alpine symbol, present in many folk art  handicrafts.
   Speaking  of

stretch    美: [stretʃ]   n.延伸；伸出；紧张；弹性 v.伸展；努力；扩张；拉直 adj.有弹力的   

continent    美: [ˈkɑntɪnənt]     n.大陆；洲；陆地；欧洲大陆（不包括英国和爱尔兰） adj.自制的；节欲的；禁欲的

pattern    美: [ˈpætərn] 
    n.模式；方式；图案；模型
    v.构成图案（或花样）；促成（某行为模式）
    网络样式；式样；图形  

    striking    美: [ˈstraɪkɪŋ] 
adj.引人注目的；异乎寻常的；显著的；妩媚动人的
v.“strike”的现在分词
    
dirndl     美: [ˈdɜrnd(ə)l] 
    n.紧身连衣裙
    网络缩腰紧身裙；阿尔卑斯裙；少女装    

  

  
Austria    美: [ˈɔːstrɪə] 英: ['ɒstrɪə]
n.奥地利；【国】奥地利；欧洲中南部内陆国家  

Alps英: [ælps]    n.阿尔卑斯山脉
    网络日本阿尔卑斯；阿尔卑斯地区；德康电子

alpine美: [ˈælˌpaɪn] 
    adj.高山的；（尤指中欧）阿尔卑斯山的
    n.高山植物
    网络阿尔派；阿尔派恩；阿尔派公司    
  
substantial meal 

take care of yourself 照顾好自己

take care 保重

take care of yourself照顾好自己

take care的意思是保重，是国外常见的告别语，take care of yourself一般理解为我先走了你好好照顾自己。

和人告别不要只会说goodbye了，适当的关心可以增进友谊。

Darling, I have to go.Take care of yourself.

好好休息
You need to have a good rest.

Do not exhaust yourself

Thank you for asking.

I just feel a little tired.

谢谢你的关心，我只是有点累。


https://www.sohu.com/a/402973463_444261 关心别人别再说"take care"了，这些才是老外最常用的表达



americano     美: [əˌmerɪˈkɑnoʊ]  英: [əˌmerɪˈkɑːnəʊ]      网络美式咖啡；美国佬；美式甜蜜


I can't drink americano


I don't like to drink  americano  that  It tastes bitter.

The problem is  I ain't  getting much sleep.



bitter      美: [ˈbɪtər]   英: [ˈbɪtə(r)]

    adv.剧烈
    adj.激烈而不愉快的；充满愤怒与仇恨的；愤愤不平的；令人不快的
    n.苦啤酒（在英国很受欢迎）
    v.把…弄苦；变苦
    网络苦的；痛苦的；苦味
