* 感觉
一开始没听太明白 慢慢能听明白很多 eg  pillowcase etc 
*  1 Getting  up   0-->21:00  p7

 consult a dictionary [kənˈsʌlt]
glossary[ˈɡlɑːsəri] n. 词汇表，术语表；专门词典
semester[sɪˈmestər]    n. 学期，半学年
curtains[ˈkɜːtənz]窗帘（curtain的复数）
sunlight[ˈsʌnlaɪt] n. 阳光，日光
layers 层 ; 表层 ; 层次 ;/lerz/
fabric[ˈfæbrɪk]n.织物; (建筑物的)结构(如墙、地面、屋顶);   布料;  
cloth material 布料 [məˈtɪriəl]
cushion( cushioning, cushioned, cushions )
 [ˈkʊʃ(ə)n]    n. 垫子，坐垫；减震垫，缓冲垫
feathers [ˈfeðər]    n. 羽毛（feather 的复数）；翅膀；羽状裂缝     v. 为……装上羽毛；给……以薄边
cotton[ˈkɑːt(ə)n] n. 棉，棉花；棉布；棉线，棉纱；脱脂棉，药棉
adj. 棉的，棉制的
pants [pænts]    n. <美> 裤子；<英> 内裤，短裤；
presents [prɪˈzents]  n.礼物;礼品;目前;现在
v. 把…交给;颁发;授予;提出;提交;(以某种方式)展现，显示，表现 present的第三人称单数和复数
nowadays  现今;现在;目前
comforter 令人感到安慰的人 ; 加衬芯床罩 
comforters  [ˈkʌmfərtərz]n.令人感到安慰(或慰藉)的人(或事物);加衬芯床罩
sheet [ʃiːt]n.床单;被单;
flat  平面
blanket [ˈblæŋkɪt]    n.毯子；毛毯
certain time 确定时间
jarring  [ˈdʒɑːrɪŋ]v.（使）撞击，受震动而疼痛;（对……）产生不快的影响;使烦躁;（与……）不协调，不和谐，相冲突
slam  [slæm]v.(使…)砰地关上;用力一放，砰地放下;使劲一推;猛劲一摔;苛刻指摘;<主美口>轻易贏过，轻易胜过;冲，奋力行进;猛烈抨击
original  [əˈrɪdʒən(ə)l] n.原件；正本；原作；原稿 adj.原来的；起
go off na.进行得 (well； badly)；(话等)冒出
expression 表示 ; 表达 ; 表
emphasize ˈemfəsaɪz]v.强调;重视;着重;使突出;使明显;重读，强调(词或短语);加强的语气

native [ˈneɪtɪv]adj.出生地的本地的;当地的;土著的;原产于某地的;天赋的n.出生于某国(或某地
sufficient [səˈfɪʃ(ə)nt]adj.足够的，充足的；（理由、条件）充足的，充分的
fitted ˈfɪtɪd]adj. 合适的；订做的；有……设备的 v. 适应
original əˈrɪdʒən(ə)l] adj. 起初的，原先的；原作的，真迹的；新创作的，未发表的；独创的，新颖的；有独到见解的，有独

series  [ˈsɪriːz]n.系列;连续;接连;(广播或电视上题材或角色相同的)系列节目;

*  2 cleaning up 22:00 -->44:00  short 22:32 -->45:24
whisker [ˈhwɪskər]   n.（猫、鼠等的）须；络腮胡子；连鬓胡子     网络晶须；胡须
shave [ʃeɪv]n.刮脸；修面；剃须v.剃（须发）；（尤指）刮脸；（少量地）削减
spread [spred]    n.传播；蔓延；扩展；散布    v.传播；扩
cheek [tʃik] n.面颊；〈口〉冒失行为[言语]；厚颜无耻
demonstrate [ˈdemənˌstreɪt] v.演示；证明；说明
drawing a bath 洗澡
pleasant[ˈpleznt]adj. 令人愉快的;   宜人的;   可喜的;   吸引人的;   友好的;   和善的;   文雅的;
bonus [ˈboʊnəs]n. 奖金;   红利;   

sink [sɪŋk] 洗涤池，洗碗槽 v. 下沉;下陷;沉没;使下沉;使沉没
faucet [ˈfɔsɪt]    n.龙头；旋塞    网络水龙头
drain [dreɪn]    n.消耗；下水道；排水管；耗竭    v.排空
gargle [ˈɡɑːrɡl] vi.含漱;漱喉 n.(含)漱液;;漱口;含漱声
pour [pɔr]v.倒；倾倒；倾泻；n.流出；大雨 bathroom [ˈbæθˌrum] n.浴室；卫生间
amount[əˈmaʊnt]n.数量；金额；数额    v.等于；总
thread [θred]n.螺纹思路；脉络v.穿过；（使）穿过 网络线程；执行绪；多线程
floss [flɑs]    n.丝线    v.用牙线剔（牙）
toothpaste  [ˈtuθˌpeɪst]    n.牙膏
curtain  [ˈkɜrt(ə)n]    n.帷幕；窗帘；
lather [ˈlæðər]   v.给…涂上皂沫；用皂沫覆盖；产生泡沫；起泡沫n.（皂液的）泡沫
lather up     网络挤泡沫；涂以肥皂泡
rinse [rɪns] vt.冲洗;漂洗;清洗;n.冲洗;漂洗;洗刷漱口液
shave [ʃeɪv]n.刮脸剃须    v.剃（须发）；（尤指）刮脸
razor [ˈreɪzər]    n.剃须刀
cream [kriːm]n.奶油;乳脂;奶油夹心糖;护肤霜;洁
disposable [dɪˈspoʊzəb(ə)l] adj.用后即丢弃的；一次性的
blade [bleɪd]    n.刀片；
back and forth 来回地，反复来回
cheek [tʃik]    n.面颊
gargle美 [ˈɡɑrɡ(ə)l]    n.漱口剂；咕噜声
demonstrate [ˈdemənˌstreɪt]    v.演示；证明
bonus[ˈboʊnəs]n.奖金;红利;意外收获
tube[tuːb]n.管;(金属、塑料、橡胶等制成的)管子;
squeeze[skwiːz]v.挤压;捏挤出n.挤压;捏;榨出的液体;小量挤出的汁;挤;
attached [əˈtætʃt] v. 把…固定，把…附(在…上) adj. 依恋;爱慕;  附属于;  所附的;  
separate [ˈsepərət]    v.分离；区分；隔开；区别    adj.单独的
spout [spaʊt] n. 喷口;(容器的)嘴;(喷出的)水柱，液体柱
v. 喷出;喷水;喷射;滔滔不绝地说;喋喋不休地说
rub[rʌb]v.擦;磨;搓;(使)相互摩擦;摩擦;涂n.擦;抹;搓;揉;问题;困难
towel[ˈtaʊəl]n.毛巾；手巾；纸巾；抹布    v.用毛巾擦干
beard[bɪrd]n.胡须;(人的)络腮胡子;髯;(动物的)颔毛;vt.〔比喻〕公开反对;公然蔑视
mustache[ˈmʌstæʃ]n.胡子;(很长时称作 moustaches)髭，口上须，八字须


*  3 Eating Breakfast          46:00-->
p18-->
cupboard  [ˈkʌbə(r)d]    n.橱柜；密室    网络碗柜；
cereal [ˈsɪriəl]  麦片   n.谷物；谷类植物
a stack of [stæk] 一堆 ; 一摞 
skim [skɪm]v.浏览；略读；撇去（液体上的油脂或；滑过adj.撇去奶油的；用脱脂乳做的
silverware[ˈsɪlvərwer]n.银器;镀银器皿(尤指餐具);(体育比赛中的)银杯
grab[ɡræb]v.抓住;攫取;喝;捞取，赚取，抢占n.抓取(或截取、采集)的图像;抓具;抓斗
jam[dʒæm]n.果酱;拥挤;堵塞;卡住(因而发生故障)v.使劲(往某处)挤(或压、塞);(使)卡住，不能动弹，不能运转;塞入;塞进;挤进;挤满;
rinse[rɪns]vt.冲洗;漂洗;清洗;(用清水)洗涮;冲掉…的皂液;(用清水)冲掉
n.冲洗;漂洗;洗刷;染发剂;漱口液
Thermos美 /[ˈθɜːrməs]n.热水瓶;瑟姆斯保温瓶;真空瓶;
plastic[ˈplæstɪk]n.塑料；信用
coffee grounds 咖啡渣
cabinet [ˈkæbɪnət] n.内阁；储藏柜；陈列柜 橱柜；柜子    adj.内阁的；小房间用的；玲珑的；细木工做的
shelves[ʃelvz]n.(固定在墙上的或橱柜、书架等的)架子突出的岩石;陆架;陆棚v.“shelve”的第三人称单数
singular[ˈsɪŋɡjələr]adj.单数的;奇特的;非凡的;单数形式的;突出的;显著的;奇怪的;异常的n.单数;单
batter[ˈbætər]n.击球手;面糊(用于做糕饼)v.连续猛击;殴打
combine[kəmˈbaɪn ,ˈkɑːmbaɪn]v.(使)结合;联合;混合;兼做;兼办
maple leaf[ˈmeɪpl liːf]n.枫叶(加拿大的象征);枫叶旗(加拿大国旗)
stove[stoʊv]n.火炉;(用于取暖的)炉子v.用火炉烤[烘干]；
flip[flɪp]v.(使)快速翻转，迅速翻动;快速翻阅，浏览;勃然大怒，心烦意乱;（快速地）调频道，换台;轻抛，轻
flat[flæt]adj.平的;水平的;平滑的;扁平的;枯燥的;平淡的;色彩单调的;不景
round [raʊnd] adj.圆的
tray[treɪ]n.盘;托盘;碟;(各种用途的)浅塑料盒
drawer[drɔːr]n.抽屉;开票人;出票人
heats[hiːts]n.热;温度;炎热天气;(建筑物、车辆等中的)高温，热的环境v.加热;变
brown [braʊn]n.棕色；褐色
thick[θɪk] 粘稠 adj.充满；弥漫；厚的；粗的n.最厚[粗]的部分；〈口〉笨蛋；〈俚〉可可粉
spread[spred] 抹在面包上的东西;涉及区域 v.传播;展开;打开;摊开;使散开;张开;伸开;（使）蔓延，扩散，散开;使分散;延伸;涂;
n.传播;蔓延;扩展;散布;广泛;多样;;宽度;文
thin [θɪn] adj.薄的
think [θɪk] adj.充满；弥漫；厚的；粗的
 syrup 糖水 ; 糖浆  [ˈsɪrəp]
maple[ˈmeɪpl]n. 槭树;   枫树;   槭木
iron 铁 ; 熨斗 ; 铁器
square[skwerz]n. 正方形
whole [hoʊl] n.整个；整
utensil [juˈtens(ə)l] n.器具Web器皿；餐具
spread [spred]  涂 n.传播；蔓延；扩展；散布v.传播；

15:04
A silverware tray, “tray,” is a place

*  4  Getting Dressed & Ready for Work
at this point 此时
buckle[ˈbʌkl]n.搭扣;(皮带等的)锁扣v.(使)搭扣扣住;(被)压垮;双腿发软
coordinating[koʊˈɔːrdɪneɪtɪŋ]v.使协调;使相配合
polish[ˈpɑːlɪʃ]v.磨光;润色;擦光;修改;润饰n.抛光;擦
wallet[ˈwɑːlɪt]n.钱包
belt [belt]n.皮带；腰带；传动带；传送带v.猛击；
garage[ɡəˈrɑːʒ]n.停车房;车库
casual[ˈkæʒuəl]adj.随便的;漫不经心的;非正式; 休闲
collar[ˈkɑːlər]n.衣领;领子
suit [sut]
occasion [əˈkeɪʒ(ə)n]n.时机；理由；原因；某次 场合；机会；
butt[bʌt]屁股
rear[rɪr] 屁股，臀部; adj.后面的，背部的;〈军〉后尾（部队）的，殿后的
loose[luːs]宽松的 vt.释放;放任;adj.;零散的;不受约束;自由;
shorts[ʃɔːrts]n.短裤
tight [taɪt] adv.紧紧地；
briefs[briːfs]n.(男子或女子的)内裤
a circle[ə ˈsɜːrkl]一周；一圈 
shiny[ˈʃaɪni]adj.闪亮的;光亮的;锃亮
reflect[rɪˈflekt] v.反射；〈比喻〉反映




* Episode 6 At My Desk, on Break, and at Lunch   41:30-->
这节听多了 感觉容易很多
agenda美 [əˈdʒendə]   n.议事日程    网络议程；议程
stack [stæk] n.堆栈；一摞；
memos[ˈmɛmoʊz]n.备忘录memo的复数 short for  memorandum[ˌmeməˈrændəm]
two-dozen两打；二十几；架
conference call[ˈkɑːnfərəns kɔːl]n.电话会议
head office 总公司 ; 总部
head down 使船顺风航行  来到 
vending machine[ˈvendɪŋ məʃiːn]n.自动售货机; 
bulletin board[ˈbʊlətɪn bɔːrd]n.公告牌;布告栏
snack [snæk] n.小吃；点心
chat[tʃæt] v.聊天；交谈
pack[pæk]v.（把…）打包
take out 外卖；   na.取出；带到；拔(牙等)；取得(专卖权等)
stand in line 站队 ; 排队 ; 站成一排 
pain[peɪn]n.(身体上的)疼痛;痛苦;苦恼;烦恼;讨厌的人(或事)vt.使痛苦;
 opinion[əˈpɪnjən]n.意见;想法;看法;(群体的)观点，信仰;专家意见
Those terms 这些术语
 term[tɜrm]     n.条款；说法；价钱；措辞    v.把…称为
 team 小组
expression [ɪkˈspreʃ(ə)n] n.表达；表情；说法；压榨 网络表达式；
criticize[ˈkrɪtɪsaɪz]v.批评;批判;挑剔;指责;评论;评价
conference [ˈkɑnf(ə)rəns]n.研讨会；（正式）讨论会；体育协会（或联合会）网络会议
in charge of[ɪn tʃɑːrdʒ əv]
preposition [ˌprepəˈzɪʃ(ə)n] n.【语】介词 
drawer [ˈdrɔːə(r)] n.抽屉；出票人；起 
headquarters[ˈhedkwɔːrtərz]n.总部;总公司  head office 总公司 ; 总部
branch office[bræntʃ ˈɑːfɪs]支店（行），分号，分公司
opposite[ˈɑːpəzɪt]adj.对面的;另一边的;相反的n.对立的人(或物);对立面;反面
head down, that simply means to go to somewhere. 
kick back 放松 
casual [ˈkæʒuəl] n. 休闲 临时工；便装；
eventually[ɪˈventʃuəli]adv.最后;终于
gossip[ˈɡɑsɪp] v.说长道短n.流言；
common[ˈkɑmən] adj.常见的；通常的；普遍的；共有的n.公共用地；公地学校、大学等的）学生公共食堂 网络普通的
break [breɪk] n.中断；休息；破裂；机会v.中断；
breakfast[ˈbrekfəst] n.早餐
pack[[pæk]
dine [daɪn] v.进餐
dine in 堂食
deliver [dɪˈlɪvər]     v.交付；发表；兑现；传送    网络递送；投递；传递
inconvenient[ˌɪnkənˈviːniənt]adj.不方便的;引起麻烦的;造成困难的
butt[bʌt] n.屁股； 引起麻烦

 


* 5  Commute to Work    19-->41
听了几次 还是听明白了很多的呢
ignition[ɪɡˈnɪʃn].点火装置;点火开关;着火;点火;点燃

accelerato [əkˈseləˌreɪtər]n.油门；
gas pedal[ˈɡæs pedl]n.同accelerator 油门
transmission[trænzˈmɪʃn]车辆的）传动装置，变速器 档位 n.传输;传递;传送;传达;传染;播送;发射;发送;
reverse[rɪˈvɜːrs] n.倒挡 v.颠倒;彻底转变;使完全相反;撤销，);使反转;使次序颠倒;交换（位置或功能）;承认错误;（使）倒退行驶;打对方付费的电话n.相反的情况(或事物);后面;背面;反面;
stick [stɪk] v.粘贴；刺；忍受；    n.条；枯枝；枝条；   网络棒；坚持；手杖
stick shift[ˈstɪk ʃɪft]n.手动变速车
automatic transmission[ˌɔːtəmætɪk trænzˈmɪʃn]n. 自动车(机动车的)自动变速器
 freeway 高速公路 
 on-ramp [ɒn'ræmp] n.(主要公路上的)驶入坡道

 parking garage 停车库 ; 停车场
swiping[ˈswaɪpɪŋ]v.刷(磁卡) 挥拳打;扬起巴掌打;挥起(物体)击打;偷窃;
separate[ˈseprət , ˈsepəreɪt]v.分离;(使)分开;分割;划分;(使)分散;隔开;
commute[kəˈmjuːt]v.通勤;
metal[ˈmetl]n.金属，合金;金属制品;
gasoline[ˈɡæsəliːn]n.汽油;同petrol
windshield[ˈwɪn(d)ˌʃild] n.风挡；（摩托车等前面的）挡风玻璃,网络档风玻璃
rear [rɪr] v.抚养；养育；饲养；培养n.屁股；后部；臀部adj.后面的
announcement [əˈnaʊnsmənt] n.通告；宣告网络公告；通知
determines[dɪˈtɜːrmɪnz]v.决定 查明;测定;准确算出;;形
straight[streɪt]adj.直的;
determines[dɪˈtɜːrmɪnz]v.决定 查明;测定;准确算出;;形
straight[streɪt]adj.直的;
park[pɑrk] v.停（车）；泊（车n.公园；园区；运动场；专用区

gear [ɡɪr] n.齿轮；装置；挡
manual [ˈmænjuəl]adj.用手的；手工的；体力的；手动的 n.说明书；指南；使用手册
 brake pedal 制动器踏脚板，刹车踏板 
 brake[breɪk] n.刹车；制动器；车闸；阻力
break[breɪk] n.中断；休息；破裂

clutch [klʌtʃ] 离合器 v.抓住；握紧；攫住n.；一窝雏
clerk[klɜːrk]n.店员;职员;文  学过又不记得这个单词了
complain about[kəmˈpleɪn əˈbaʊt]抱怨，投诉
average[ˈæv(ə)rɪdʒ] n.平均水平；平均数
regular[ˈreɡjələr] n.常客；常规

*  Episode 7 The commute  Home and Running Errands 00->21:00

signal my turn onto 打转向灯
merge[mɜːrdʒ]v.合并;融入;(使)结合;并入
hassle[ˈhæsl]n.困难;麻烦;分歧;争论;烦恼
stalled[stɔːld]v.(使)熄火，抛锚;故
fast lane[ˈfæst leɪn]n.(高速公路或州际公路上的)快车道
surface streets 地面街道
 make a stop 停止，休息，停留 
 fridge[frɪdʒ]n.冰箱
 pasta [ˈpɑstə]     n.意大利面食 意粉；通心粉
checkout stands 结帐站
cashier[kæˈʃɪr]n.出纳员
cart[kɑːrt]n.手推车
trunk[trʌŋk]n.大旅行箱, 大行李箱;树干（汽车后部的）行李箱
load 装上
errand[ˈerənd] n.差事；差使
section 部分 ; 部门 ; 部件
divided[dɪˈvaɪdɪd]分配  adj.被分割的;分裂的;有分歧的v.(使)分开分割分成
indicate[ˈɪndɪkeɪt]v.表明;显示;象征;指示;写明;打行车转向信号;
blinker[ˈblɪŋkər]n.马眼罩 指示灯
flashes[ˈflæʃɪz]v.(使)闪耀，闪光;(向…)用光发出(信号);
combine with[kəmˈbaɪn wɪð]与…结合
refers to[rɪˈfɜːrz tu]v.查阅;提到
temporary[ˈtempəreri]adj.短暂的;暂时的
shoulder[ˈʃoʊldər]n.应急车道 肩, 肩膀, 连肩肉;肩状物;山肩;路肩
get in the way 妨碍 
common [ˈkɑmən] adj.常见的；通常的；普遍的；共有的n.公共用地；公地；
construction [kənˈstrʌkʃ(ə)n] n.施工；建筑
surface[ˈsɜrfəs] n.表面
regular [ˈreɡjələr] 常规
intersection[ˌɪntərˈsekʃn]n.十字路口;交叉路口;交点;

*  episode 8  Making  and Eating  Dinner, and Washing Up 
series[ˈsɪriːz]n.系列;连续(广播或电视上题材)系列节目;(两队之间的)系列比赛
get home 抵家 
counter [ˈkaʊntər] n.（厨房的）操作台 计算器；（商店、银行等的）柜台；
preheat[ˌpriːˈhiːt]vt.使(烤箱)预热
oven[ˈʌvn]n.烤箱;烤炉
burner [ˈbɜrnər] n.煤气头；煤气灶火圈；炉膛
boiling[ˈbɔɪlɪŋ] n.沸腾；
yell [jel] v.叫喊；
chopping['tʃɒpɪŋ] v.砍；劈；切碎；剁碎n.砍；劈；剁；猪
stir[stɜːrz]v.搅动;搅和;搅拌;(使)微动;(使)行动，活动stir的第三人称单数
toss[tɔs] v.抛；摇摆；(轻)拌
place mats[pleɪs mæts]n.餐具垫place mat的复数
napkin [ˈnæpkɪn] n.餐巾(纸)
leftovers[ˈlɛfˌtoʊvərz]n剩菜;残羹剩饭
plastic wrap[ˈplæstɪk ræp]n.(食品)保鲜膜
aluminum foil[əˈlumənəm fɔɪl]铝箔
flat top[ˈflæt tɑːp]平顶；
fahrenheit [ˈferənˌhaɪt] n.沸点为212°；Gabriel Daniel adj.华氏温标的
burners[ˈbɜːrnərz]n.煤气头;煤气灶火圈;炉膛;(取暖用的)炉子
stoves[stoʊvz]n.(用于取暖的)炉子，火炉stove的复数
lettuce[ˈletɪs]n.莴苣;生菜
dressing [ˈdresɪŋ] n. 沙拉酱 打扮；穿着；；调味汁
flat sheet[flæt ʃiːt]平板；平直薄板；平片材；扁插索针

*  Episode 9 Relaxing, the Mail,  and the Trash
sort through[sɔːrt θruː]整理; 分类
junk mail 垃圾邮件
front stoop[frʌnt stuːp]n.前门前的台阶
newscast[ˈnuzˌkæst] n.新闻节目；新闻广播
reality[riˈæləti]  shows 真人秀
commercials[kəˈmɜrʃəlz]n.(电台或电视播放的)广告commercial的复数
thumb through[θʌm θruː]匆匆翻阅，浏览（书籍、杂志
mystery[ˈmɪstəri]n.神秘的事物;不可理解之事;奥秘;谜;
bins[bɪnz]n.垃圾箱;(有盖)大容器，箱，柜
roll [roʊl] n.卷；打滚；翻滚；名单v.滚动；
separate[ˈseprət , ˈsepəreɪt]v.分离;(使)分开;分割;划分;(使)分散;隔开;阻隔;
statement[ˈsteɪtmənt]n.陈述;声明;报表
fliers[ˈflaɪərz]n.飞行员;飞机乘客;小广告;广告传单
plural[ˈplʊrəl]adj.复数的;多元的;复数形式的;
competition [ˌkɑmpəˈtɪʃ(ə)n] n.竞争；比赛；竞赛；对手网络竞争对手
contest[ˈkɑːntest , kənˈtest]n.竞赛;比赛;(控制权或权力的)争夺，竞争
fictional[ˈfɪkʃənl]adj.虚构的;小说(中)的
particular[pərˈtɪkjələr]adj.专指的，特指的(与泛指相对);不寻常的;格外的;特别的;讲究n.(正式记下的)细节;详情

trucks[trʌks]卡车
neighborhood['neɪbərˌhʊd]n.街区;城区;（
excited. [ɪk'saɪtɪd] adj.激动的；兴奋的；受刺激的；紧张不安的

*  10
ritual[ˈrɪtʃuəl]n.仪式;礼节;程序;
admit[ədˈmɪt]v.承认(过错、罪行);招认
floss[flɔːs]n.丝线v.用牙线剔(牙)
undressed[ʌnˈdrest]adj.赤裸;一丝不挂v.(给…)脱衣服
hamper[ˈhæmpər]盛脏衣服的大篮子  vt.妨碍;阻止盒装食物，袋装食物;
pajamas[pəˈdʒɑməz] n.（一套）睡衣裤
slipper [ˈslɪpər] n.拖鞋；(室内)便鞋；(马车的)煞车
pull back 退出 ; 退却 ; 撤退 拉开
covers 掩蔽 袜子 被套
fluff[flʌf]vt.抖松; 拨开  n.(禽兽，尤指幼者的)绒毛;(衣服等上的)蓬松毛团;没多大意义的娱乐
 climb into 进入 ; 〈非正〉穿衣 
nod off[nɑːd ɔːf]（尤指不打算入睡时）打瞌睡，打盹儿
 fairy tales feəri 'teɪliːz n.童话(故事);不实之词;谎言
 imaginary[ɪˈmædʒɪneri]adj.想象中的;幻想的;虚构的
 religious[rɪˈlɪdʒəs]adj.宗教信仰的;宗教的;
prevent[prɪˈvent]vt.防止;阻止;阻碍;阻挠
 abbreviated[əˈbriːvieɪtɪd]v.缩略;把(

abbreviated[əˈbriːvieɪtɪd]v.缩略;把(
The covers, "covers,"  blanket, the comforter, and the top sheets.被套，“被套”是毯子、被子和顶层床单
ceiling[ˈsiːlɪŋ]n.天花板;顶棚;



 15:00
 





