*  English  conversation on the go 
** Lesson 20  twenty Checking into  Hotel


Good morning.  I'm  Mr. jack Wu. I have a reservation for a  suite.

oh, yes, Mr. Wu. Please  


background

gorgeous 好看 
wait
minute 

It's very easy to overspend when you  have a  credit card.

***   word and other


    
** Lesson 21 Changing Money
Monday June 06 2022

*** 课文
I  would  like to cash  these  traveler's checks,please

How much do you have ?

Five hundred US dollars.

Do you have any identification?

Will my passport do ?

That's be fine .

****  Dialogue B

What's the exchange rate for US dollars,please?

Which  currency do you want to change  your  money into?
 Hong Kong dollars ,please
It's 7.89 Hong Kong  dollars to  1 US dollar.
Can you  change US$100?
How do you  want your money?
Seven  hundreds,eight tens and the rest  is change, please
No problem.


***  word and other
bounce 跳票

go (went) to bed later 晚睡
sleep later  起床好晚

** Lesson 23  At  the Airport I 
   wednesday June eighth 08th  2022
***   Dialogue A
  This is the arrival lounge.
  I know, Where is the  departure lounge?
  Come .Follow  me.
  There! The check-in counters are over  there.
  Don't we have to go pay the airport tax first?
  No. We pay it after we check in.

***  Dialogu B
   Good morning . May I have your passport ,please?
   Here you are.
   Smoking or non-smoking.
   Non-smoking.
   Aisle  or window seat?
   Window seat,please.
   Do you have any luggage to check in ?
   Yes. This is my carry-on  luggage and I'll check in  these two suitcase.

   

   
*** Vocabulary
  section 区域 

  check in 美:  
    v.〈美〉报到；(旅馆)登记
    网络入住；办理登记手续；签到


    Laundromat    美: [ˈlɔndrəˌmæt] 英: [ˈlɔːndrəmæt]
    n.自动洗衣店；〈美〉自动洗衣店的招牌
    网络自助洗衣店；自助式洗衣店；自助洗衣房

    词形：

    
** Lesson 30 Emergency Calls

*** Dialogue A
 This is an emergency call! Get an ambulance here right away.
 Where are you calling from ?
 I'm at No.10 Zhong Hua Road.
 What's the  problem?
 A taxt ran into a truck.

 
***  Dialogue B
 Fire! There's a fire. Come quick!
 Where's the fire ?
 At No.7 Kaifeng Street.
 What's burning?
 My restaurant is on fire.
 How did it happen?
 A gas tank exploded.
 We'll be right there!

 
***  vocabulary

 calmly 冷静


 
** Lesson  28  Going to the  Movies
  Thursday June ninth 09th  2022

  
*** Dialogue  A
 Can I have two tickets for Titanic, please?
 For what time ?
 The 9:30 p.m. show , please.
 I'm afraid it's full. How about the midnight show ?
 That'll be fine. Can I have our seats up front, please ?
 Sure , That'll be twenty dollars,please.

 
***  Dialogue B
 Where were you last night?
 I was at the movies . I went to see titanic.
 How was it ?
 It was fantastic.  The  main actor  and actress really did a good job.
  Sounds like it  was a very goog movie.
  You can say that again.

  
***  vocabulary

main    美: [meɪn] 英: [meɪn]
n.总管；电源；（建筑物的）污水总管道；水源
adj.主要的；最重要的


14 

 wonderful 

    
* Basic English: Book1

** lessson twenty-five   My Father
 My father does the same thing every morning. He gets up  at six o'clock . He washes ,brushes his  teeth and combs his hair. Then , he puts on his clothes  and 
  eats breakfast. At six thirty he listens to the news on the radio. At exactly  seven o'clock  he leaves the house. My father has very regular habits. 

** Lesson twenty-six  He usually plays Tennis
 What do you usually  do on Sundays?
 I usually go for  a walk  in the mountains.
 Does your husband go with you ?
 No. He doesn't. 
What does he do?
He usually plays tennis.



**  Lesson 45   What a Nightmare!
    Tuesday  June seventh  2022 

    
*** Reading 
    Jeff had a  terrible day. He missed the train to work. Moreover, he had to wait a long time for the next train . As a matter of fact , he waited for two hours. To make matters worse , he left his briefcase on the train.  As a resul, he had to  go to the police station. Poor Jeff never got to  work  that day. What a  nightmare!

    
***   Vocabulary & idioms  word and 
terrific ==great 
take a  bus to work everyday
 I bike to work everyday 

 hurry up 快点


He sing very well .
Beats me! (难倒我了,问题是单数 所以 加了s) 

naughty 调皮

On the train 空间大可直立
In the taxi , 空间不大不可直立

He is stupid ,  to make matters worse,he don's study  


He don't study . as a result , he failed the exam.



* Intermediate English: Book 1

** Lesson 1  Rome  Wasn't Built in a day
  English is an internatinal languages. Therefore,  it is necessary for us  to learn it. It can be  rewarding  or just a  waster of time. It's up to you. It depends on  how you study it. Here are some tips about  learning  English.
   First , don't  be afraid ot make  mistakes.  You  will  learn  from them. Second, you must not be shy. Be thick-skinned and  speak up! Finally , you must  be patient. Remeber,"Rome wasn,t built in a day."
 
**  Lesson 2  How  to imporove your english 
Mack is talking  to his friends  don.
 Hi, Don, How are you doing in your English class?
 Not so well, I'm afraid.
 What's the problem?
 I'm  not improving . Tell me, how come your English is so good ?
Well,uh... I have an American girlfriend.
 Aha!That's it. Now I know what to do.(He runs off)
Hey, come back! I was just kidding!

** Lesson 3  The city of Song 
  Listening to music  is the favorite pastime  of many people all over the world . This is especially true  for people  living in Vienna, the city of song. Being  the home  of Mozart, this  city is the brithplace  of classical music  and the waltz.
  Music fills the  air in Vienna. Going  to public concerts is often  free  charge. And  don't forget, Vienna is also home to the world  famous Vienna Boys' Choir. No wonder people say Austra is  always alive with the sound of music.


**  Lesson 4   He Who  hesitates is lost 
Are you having  a  good time,Daisy?
Are you kidding? I'm having  the time of my life. I love the  concerts.
Concert going  is fantastic but what  else  can we do?
Biking along  the banks of the river Danuber could  be fun.
It sounds  like a great  idea!
Let's do it then.
You're right . As they say,"He who hesitates is lost."




**  Lesson 75  The  Amish

  In the heart of America, in the  states  of Pennsylvania, Ohio and 


** Lesson 78  Believe  It  or Not
My friend,Andy, is talking to  his girlfriend, Jenny, about what I said  in the previous lesson .
A: So  who did you go to the movies with ?
J: Nobody.
A: What do you mean NOBODY?
J: Don't shout at me. Allow me  to  explain.
A: I'm waiting.
J: Uh... that was  my uh.. brother.
A: Do you expect  me to believe that ?
J: You can  believe  what  you want .
A: I'll never get you to tell me the truth, I guess.
J: Why don's you believe me?
A: Because I had  dinner with your brother  last night!

expect [ɪkˈspekt] v.期望；预计 
 



*  Advanced English
** Lesson one Let's Visit New   York? 
   New York, NewYork.                                                                                                                                                       
   These  words were used to describe  New York when it was  by far the largest,richest, and most  developed city in the United States. New York still remains the largest   
 and most famous city in the U.S. today, but some of its"nice" reputation has fallen over the past thirty years with  stories of  rampant  crime making headlines around     
 the world. How true are these stories? Is New York still a "nice" place to visit? if so, what can a tourist do in New York? Let's  take a closer look  at America's         
 premier[prɪˈmɪr] 第一 city.                                                                                                                                                 
                                                                                                                                                                           
 premier    美: [prɪˈmɪr] 英: [ˈpremiə(r)]                                                                                                                                   
                                                                                                                                                                                n.总理；地区总理                                                                                                                                                        
     adj.首要的；最著名的；最成功的；第一的                                                                                                                                  
     网络首相；拍得丽；首位的 

advance美: [ədˈvæns]  d 音 弱化 
n.进展；进步；提高；预付款
v.提前；进步；促进；预付
adj.先遣队；预先的；事先的；先头

despite    美: [dɪˈspaɪt] 
    prep.尽管；即使；尽管（自己）不愿意
    n.怨恨；恶意；轻蔑；侮辱
    网络不管；不顾；任凭

 glaring    美: [ˈɡlerɪŋ] 
adj.显眼的；明显的；易见的；刺眼的
v.“glare”的现在分词


property    美: [ˈprɑpərti] 
    n.属性；财产；财产权；【戏】道具
    网络性质；特性；性能

    词形：
    properties



This river abound in fish.




** Lesson two The amish 
 
   In the land of  rock and roll, the space shuttle, computerized living, who could imagine  that  about 50,000 Americans do not use  telephones, electric lights, or cars,  
 not  because  they  are poor, but out of choice? As hard as this may be to imagine, the American, or more properly, the Amish Mennonites, still  live a traditional, rural  
 美: [ˈrʊrəl]  乡村的 lifestype direct from  17th century Europe?                                                                                                            
   To understand these unique Americans better,it is  necessary to understand  their history. Beginning with the   revolution  started  by Martin Luther , Leader of the     
 Protestant Reformation in  Germany   in the  16th century,                                                                                                                  
                                                                                                                                                                           
 rural  美: [ˈrʊrəl]                                                                                                                                                         
     adj.乡村的；农村的；似农村的                                                                                                                                            
     网络乡下的；田园的；乡村风味的


     


**  Lesson 3   indoor pollution

   So you  think  that  by staying at home  you are safe from all the terrible kinds   of pollution present  outdoors,  such as  in  or near factories, reoads, and         
 garbage dumps? DO you  think that by staying in your office you are breathing cleaner, safer air than when  you go outside fou lunch  or are on  the way back home from     
 work?Think again . Recent research done at the University of Texas has shown  that staying indoors  may actually be  more harmful to  one's  health than   being  outdoors  
 even in  smoggy cityes.                                                                                                                                                     
                                                                                                                                                                             
                                                                                                                                                                             
   Apparently ,we are  safe neither at home  nor in the business office.We use  water  in both  place, but the above-mentioned research   shows  that  chemicals added to    
 our local water supply to kill harmful bacteria can have unwanted side effects.These  chemicals can cause potenital harm through  dranking  and in seemingly  harmless      
 activities as cleaning  one's  house.  These  additives are released from water by daily  actions like  water running out  fo faucets , spraying from garden  hoses, or     
 splashing in dishwashers  and washing machines.As the water is agitated, these  chemicals are released into   the air  and then  breathed in . Once  inside our             
 bodies,they start to affect our health adversely.                                                                                                                           
   Does  this  mean   we should stop  bathing? No, say the scientists, but we should  put all pollution  into  perspective [pərˈspektɪv]  观点 洞察. Activities at home      
 such  as the  burning  of propane, coal, cooking  oil, or even  candles and incense release  carbon monoxide  and particulates  such  as soot  which  have been proven as   
 harmful to healthe as working or living  near high-density traffic.                                                                                                         
                                                                                                                                                                             
 addicted   美: [əˈdɪktəd]                                                                                                                                                   
     adj.上瘾了的；入了迷的；沉迷于…的                                                                                                                                       
     网络上瘾的；成瘾；中毒

addiction                                                                                                                                                                   
                                                                                                                                                                             
     美: [əˈdɪkʃ(ə)n]                                                                                                                                                        
                                                                                                                                                                             
 英: [ə'dɪkʃ(ə)n]                                                                                                                                                            
                                                                                                                                                                             
     n.瘾；嗜好；入迷                                                                                                                                                        
     网络上瘾；成瘾；沉溺                                                                                                                                                    
                                                                                                                                                                             
 present   美: [ˈprezənt]                                                                                                                                                    
     n.目前；现在；礼物；礼品                                                                                                                                                
     adj.存在；出席；在场；出现                                                                                                                                              
     v.出现；提出；显示；提交                                                                                                                                                
     网络呈现；赠送；现在的                                                                                                                                                  
                                                                                                                                                                             
 take office  入职                                                                                                                                                           
                                                                                                                                                                             
 in one's way  挡路  hey ,evan  ,don't stay  my way                                                                                                                          
                                                                                                                                                                             
 apparently   美: [əˈperəntli]                                                                                                                                               
     adv.显然；可见；看来                                                                                                                                                    
     网络显然地；明显地；表面上                                                                                                                                              
                                                                                                                                                                             
                                                                                                                                                                             
                                                                                                                                                                             
                                                                                                                                                                             
 perspective    美: [pərˈspektɪv]                                                                                                                                            
     n.观点；远景；景观；透视法                                                                                                                                              
     adj.(按照)透视画法的；透视的                                                                                                                                            
     网络透视图；视角；看法                                                                                                                                                  
                                                                                                                                                                             
 手工打单词要记得的打下来 记住一个单词 然后写下 不要一个个字母的边看边打                                                                                                     
                                                                                                                                                                             
                                                                                                                                                                             
 bookworm 书虫                 

     



 
**  Lesson  four  Pizza, Please

**  here  

 
**  Lesson 5  The animals  around the world: Chameleons
  Every few months this  program will feature an  animal which  has caught the eye of the world's public to become a  favorite or "hot"  animal. In  the first  of this  unusual series, we  will  look at the chameleon, one of  nature's strangest creatures.
  Perhaps no  other  group  of animals  has  caught mankind's  imagination like reptiles.  Among the several subclasses(or "orders" in biology) of  reptiles are snakes and lizards, turtles and tortoises ,crocodiles  and alligators, and the  tuatara, a marine lizard in  New Zealand. The dinosaurs, too, belonged to  the calss o f reptiles. Was it a  snake,lizard, or crocodile that caught the fancy of some Chinese in times gone by  to  create dragon? A perrennial  theme ,reptiles have  been featured over the past ten years in box-office hits and bombs alike as dinosaurs( JURASSIC Park and The lost world), corcodiles, and snakes(Anaconda). Though not nearly as large as these mighty reptiles,, the lowly chameleon nonetheless has amazed  countless generations   with  its special talents and skills.
  What is a  chameleon? Its  unusual name fits  this unusual animal perfectly, for  pit translates from  the ancient Greek as "lion on the ground." This is unexpected, since chameleons spend most  of their time in trees, and as  for looking  like a lion, a chameleon  looks like a .. well, a chameleon! No  other animal in Nature's  zoo looks quite as  bizarre as  they do. Where do they live? True  chameleons  are found  only in the tropical  forests  and jungles of the Old world, and  nearly half of its   species live on the African  island  of Madagascar.
  What's so special about  the chameleon? Plenty! From  its  tongue to its  tail the chameleon  offers a  storehouse  of specialites. The tongue  of this modern-day  dinosaur look-alike  can be  extended more than twice the  length  of its  body. This  type of tongue . also present in frogs and toads, is called an extensile tongue. The eyes of hte chameleon  are even  more remakable. Its eyes are turreted and can be moved independently  so that it can view two  different object simultaneously! This comes in especially handy as it is tree-dwelling. The chameleon can  keep  one eye on its prey  and the  other on its footing. Its head  is often  helmet-shaped, and some  species have horn-like structures  growing  out of  this  scaly helmet.

prey on sth  sth的猎物  
  
live on    na.以…为主食；靠…生活；继续活着；靠［吃］…生活
    网络以……为主食；靠……为生；以…为食
Most Chinese live on rice. 

dwelling    美: [ˈdwelɪŋ] n.住宅；住所；公寓 v.“dwell”的现在分词

storehouse    美: [ˈstɔrˌhaʊs]     n.仓库；货栈；（信息或知识等的）宝库     网络库房；储藏室；栈房

multitude    美: [ˈmʌltɪˌtud] n.众多；群众；人群；大量

An umbrella aAlways come in handy in the summer. 
伞在夏天总是派得上用场。

perfectly    美: [ˈpɜrfɪk(t)li] adv.非常；十分；完美地；完全地
ancient    美: [ˈeɪnʃənt] 英: [ˈeɪnʃ(ə)nt]adj.古代的；古老的；很老的n.（尤指古埃及、古希腊和罗马的）古代人
tropical    美: [ˈtrɑpɪk(ə)l]  adj.热带的；来自热带的；产于热带的
prey    美: [preɪ] n.猎物；受害者；受骗者 v.折磨；掠夺；捕食 (on, upon)；损害 (on, upon)
helmet     美: [ˈhelmət] n.头盔；防护帽v.给…戴上头盔
shaped    美: [ʃeɪpt]     adj.具有（或呈）…形状的
    v.“shape”的过去分词和过去式    网络成形；成形的；成型的 horn    美: [hɔrn] 英: [hɔː(r)n]
n.角质；（羊、牛等动物的）角；（乐器）号；（车辆的）喇叭
v.在…上装角；把…做成角状；(动物)用角抵触[刺挑]；把(牛角)截去
adj.角制的    

structure     美: [ˈstrʌktʃər]     n.结构；组织；石理；【心】(直接经验中显现的)结构性
    网络语言结构；结构体；建筑

    scaly    美: [ˈskeɪli]     adj.有鳞屑的；有皮屑的    网络有鳞的；鳞状；鳞状的

  The feet and   tail  of the chameleon are also special. Both  are prehensile; that is , they  are both perfectly adapted  to their sylvan  environment. The toes  of the chameleon's feet are bunched into  inside and outside groups of two  or  three to enable this reptile to grasp  tree  branches tightly. The chameleon can  thus  climb extraordinarily well  while  using its  tail  to  grab  objects for  further balance.

adapted    美: [əˈdæptəd] adj.适合…的；改编成…的
v.适应不同环境[情况等]；“

toe    美: [toʊ] n.脚趾；(鞋,袜等的)尖；蹄尖；蹄铁尖
v.用脚趾踩；装[修补]鞋尖[袜尖等]；用脚尖踢；【高】用棒尖打(球)
grasp    美: [ɡræsp] v.理解；领会；抓紧；明白
n.领会；紧握；控制；紧抓
thus    美: [ðʌs]     adv.因此；这样；如此；从而      网络因而；于是；由此

further    美: [ˈfɜrðər] adv.进一步；此外；更远；而且 v.促进；增进
    
  The above   inventory of  natural selection specializations would  be remarkable enough, but what  really  separates the  chameleon from its fellow reptiles is  the  fact  that  its  scales contain  the ability to change color. Though many people think  the chameleon  can change its color  at will  and that it can blend into any color, these are misconceptions. In fact,chameleons can  blend  into many  natural colors and even  patterns, but they cannot  do this at will. Instead, this  happens naturally according to  temperature, emotional state of the animal, and the triggering of certain  hormones within its body.

  pattern    美: [ˈpætərn]     n.模式；方式；格局；型
    v.给…加花样；照图样做；仿造；形成图案    网络模型；型态；句型
certain    美: [ˈsɜrt(ə)n] 
    adj.肯定；确定；确信；无疑    pron.（不提及人或事物的名称时用）某些    网络确定的；肯定的；一定的    

misconception    美: [ˌmɪskənˈsepʃ(ə)n] n.误解
    trigger    美: [ˈtrɪɡər] v.触发；扳动扳机射击；松开扳柄n.(枪上的)扳机；【物】触发器；【
    
  It is hard to imagine an animal more interesting than  the chemeleon,with  its weird appearance and special abilities. We should  always  remember,however, that these animals require their native habitat to flourish in, not zoos or individuals'  terrariums. If you want your grandchildren to see  this  gift  of nature, do not collect  it as s pet. These natural treasures evolved over millions of years without  mankind's help;they will continue to survive better if left alone.

  individual    美: [ˌɪndɪˈvɪdʒuəl] 
n.独立单位；〈俚〉人 adj.单一的；特有的；个体

appearance    美: [əˈpɪrəns] n.外观；外表；出现；外

habitat 美: [ˈhæbɪˌtæt] n.生境；栖息地；居住地；

treasure    美: [ˈtreʒər] 
n.宝藏；财富；宝贝；宝贵的人材 v.珍藏；珍重；爱护；热爱
  
*** vocabulary 
reptile美: [ˈreptɪl] n.爬行动物 adj.匍匐的；爬虫类的；卑劣的


perennial.多年生植物 永久的

SERIES      美: [ˈSꞮRIZ]     N.串联；一系列；连续；接连    网络级数；丛书；序列

program    美: [ˈPRƏƱˌꞬRÆM]     n.节目；计划；【计】程序；课程(表)    v.编写程序；为…制定计划；使…按安排进行

irresistible    美: [ˌɪrɪˈzɪstəb(ə)l] 
    adj.不可遏止的；无法抵制的；极诱人的；忍不住想要的
    网络不可抵抗的；不可抗拒的；无法抗拒

anaconda    美: [ˌænəˈkɑndə] n.水蚺（南美洲蟒蛇）      redhat 安装程序

nonetheless    美: [ˌnʌnðəˈles] adv.尽管如此

perfectly    美: [ˈpɜrfɪk(t)li] adv.非常；十分；完美地；完全地

ancient    美: [ˈeɪnʃənt] 英: [ˈeɪnʃ(ə)nt]adj.古代的；古老的；很老的n.（尤指古埃及、古希腊和罗马的）古代人

tropical    美: [ˈtrɑpɪk(ə)l]  adj.热带的；来自热带的；产于热带的
prey    美: [preɪ] n.猎物；受害者；受骗者 v.折磨；掠夺；捕食 (on, upon)；损害 (on, upon)

helmet     美: [ˈhelmət] n.头盔；防护帽v.给…戴上头盔

shaped    美: [ʃeɪpt]     adj.具有（或呈）…形状的
    v.“shape”的过去分词和过去式
    网络成形；成形的；成型的

horn    美: [hɔrn] 英: [hɔː(r)n]
n.角质；（羊、牛等动物的）角；（乐器）号；（车辆的）喇叭
v.在…上装角；把…做成角状；(动物)用角抵触[刺挑]；把(牛角)截去
adj.角制的    

**  Lesson 6 Table Manners in Anglo-America  June 28 2022 
  "Oh ,no Here I am at an American family's home at the dinner table.There are all kinks of plates, saucers,cups,and silverware at my place. Which  should I use  for which food? Should I sit down  first or wait  for the host to invite me? Should I have brought a gift? Someone please tell me what to do!"

manner    美: [ˈmænər]     n.礼貌；举止；习惯；方法
anglo-america     网络 英美；盎格鲁美洲；美利坚
spoon    美: [spun] n.勺；匙；调羹 v.用勺舀
silverware      美: [ˈsɪlvərˌwer]  n.银器；餐具（刀、叉和匙）；（体育比赛中的）银杯

  Have you ever been in or had a nightmare about  this  situation? Don't worry! This article will help  steer you through the rocks and reefs of Anglo-American table manners so  that if you are ever abroad in Canada or the United States, or  at someone's home from  one of  those countries,you will  feel right at home.

steer    美: [stɪr]     v.引导；控制；操纵；驾驶（船、汽车等）      n.建议；劝告；忠告；阉公牛     网络掌舵；掌握方向
ever     美: [ˈevər]     adv.曾经；从来；总是；到底  网络永远；究竟；在任何时候    

  It is  important to distinguish   what kind of  occasion you will be attending before you plan for a pleasant  evening. Most  Anglo-Americas enjoy  entertaining  at home, but they don't  enjoy stuffy, formal dinners. They invite their friendss over  for a fun evening , not as a  test of one's knowledge of cultural  traditions. If, however, you are  invited to a formal affair, such as a so-calld "sit-down" dinner,you may  want to know  in advance some basic rules of "black tie" etiquette.

occasion     美: [əˈkeɪʒ(ə)n] n.时机；理由；原因；某次 v.使发生；造成；导致  场合
entertain     美: [ˌentərˈteɪn]      v.娱乐；款待；使有兴趣；使快乐 网络招待；使娱乐；怀抱
attend      美: [əˈtend] v.参加；出席；注意
invite    美: [ˈɪnˌvaɪt]  v.邀请；要求；招致（尤指坏事） n.邀请；请柬
affair     美: [əˈfer] n.事件；事情；风流韵事；公共事务    网络绯闻；私通；恋爱事件

  The first thing  to remember when  attending a dinner at a Western home is  that you  are the guest and that you are a foreigner. No one will invite you if he does  not really want you  enter his "castle," so you can be sure that you are wanted. Additionally, as you do not come from the same country or culture as you host , he or she or they will surely  be aware  of this, and will  be very forgiving if you unintentionally do or  say  something  which  would  otherwise offend them. Keeping these  two simple tips  in mind  should greatly ease your concern about  being present at a dinner in someone  else's  home.

  wanted     美: [ˈwɑntəd]  adj.受通缉的  v.“want”的过去式和过去分词
  additionally     美: [əˈdɪʃ(ə)nəli] adv.另外 
  unintentionally  美 [ˌʌnɪnˈtenʃənəli]    adv. 无意地；非故意地；非存心地
aware     美: [əˈwer] adj.意识到；知道；明白；发现
forgiving     美: [fərˈɡɪvɪŋ]  adj.宽宏大量的；宽容的 v.“forgive”的现在分词
otherwise     美: [ˈʌðərˌwaɪz] adv.否则；不然；另；除此以外conj.否则
offend     美: [əˈfend]  v.冒犯；得罪；犯罪；令人不适
concern      美: [kənˈsɜrn]   n.关心；忧虑；公司；企业 v.涉及；影响；牵涉；与…有关
present      美: [ˈprezənt]   n.目前；现在；礼物；礼品

  Before arriving at your  host's home. you may want to make sure of three things. First, be a few minutes late,say,about  five to ten  minutes if possible. Never be early, as the host may not have everythng prepared yet. Nor should you  be more than  20 minutes late.Your host may begin to worry about  whether  you are able to attend  the dinner or not. Next , as to whether  to bring a gift, in most informal gatherings,  it is not necessary. If you like, you can bring some fruit or sweets, or , especially  if there is a hostess, some flowers. These are thoughtful, cheerful gifts sure to  please. Do not  bring alcoholic  beverages  unless you are  sure  of your host's  or hostess's preferences in drinks. Above  all , do not spend a lot of money, and never give money. As we say in English ,"it's the thought that counts."
Finally, wear  comfortable clothing. One  can overdress as well as appear sloppy.  For a special occasion  or religious holiday, such as a retirement  party or  Christmas, a tie and jacket would be suitalbe  for the gentlemen and dress  or sweater and skirt for the ladies.

gathering      美: [ˈɡæð(ə)rɪŋ] n.收集；采集；聚会；聚集 v.“gather”的现在分词  
hostess      美: [ˈhoʊstəs]  n.女主人；女房东；（夜总会的）女招待；（电视或广播节目的）女主持人
beverage     美: [ˈbev(ə)rɪdʒ]      n.饮料；餐费；〈英方〉筵宴     网络饮品；饮料类；饮料篇
appear     美: [əˈpɪr]  v.出现；显现；呈现；出版 linkv.似乎；显得；看来
sloppy adj. 草率的；粗心的；泥泞的；肥大的；稀薄的
religious     美: [rəˈlɪdʒəs]   n.修女 adj.宗教信仰的；宗教的；笃信宗教的；虔诚的
retirement     美: [rɪˈtaɪrmənt]  n.退休；退休生活；退职；退休年龄

  For  more formal affairs, you will  probably be told what to wear, such as "formal dress requested," etc. A tie  and jacket or tuxedo for the gents and an evening gown for the ladies would  be in order here. If you are  unsure what  to wear, you can  always ask the  host. Gifts are seldom appropriate for these affairs, unless for a wedding reception, at which  gifts are more customary than cash.
  
  Your  host in  his home will usually motion  you where to sit. At formal gatherings, name cards are sometimes  provided, or  you will  be told  where to sit.Do not be alarmed by a great deal of cutlery simply start from the outside and work your way in.  Formal affairs often have several courses  of food with the appropriate cutlery for each dish. There is no harm in  checking with your neighbor to see what implement he is using. After all, "When in Rome, do as  the Romans do." It is  customary to ask others to pass dishes to you  for self-serving; at a formal dinner party, there is  usually catering(service). Again, do not hesitate to  ask others  for information or advice. They are usually  pleased to help you.

provided      美: [prəˈvaɪdəd]    conj.如果；假如；在…条件下  adj.预备好的；由…供给的 v.“provide”的过去分词和过去式  
cutlery      美: [ˈkʌtləri]   n.餐具（刀、叉和匙）；刀具
appropriate      美: [əˈproʊpriˌeɪt]   v.拨款；剽窃；挪用；〈正式〉非法占有 adj.恰当的
course     美: [kɔː(r)s]  n.过程；球场；【教】课程；航线 v.流动；(某种感觉)突然
implement     美: [ˈɪmpləmənt]  v.实施；执行；贯彻；使生效 n.工具 器 具
hesitate      美: [ˈhezɪˌteɪt]  v.（对某事）犹豫；顾虑；疑虑
advice     美: [ədˈvaɪs]  n.建议；意见；忠告；劝告
again     美: [əˈɡen]  adv.再一次；又一次；再说；复原

 The most important  piece of advice is this: enjoy  yourself. No host enjoys seeing nervous or fearful guests who are struggling to "do the right thing" at his home  or expensive  formal dinner party. Watch  other or ask for  their advice, and join in the conversation  and  good times as  best as you can . if you  do , after the first  such evening out,you will certainly look forward to the next!

 fearful    美: [ˈfɪrf(ə)l]      adj.担心；担忧；忧虑；可怕的    网络害怕的；担心的；吓人的
struggle     美: [ˈstrʌɡ(ə)l]  v.挣扎；斗争；努力奋斗；争取 n.努力；斗争；奋斗；抗争
conversation     美: [ˌkɑnvərˈseɪʃ(ə)n]      n.（非正式）交谈     网络谈话；会话；对话
 
**  Lesson 7 The  Delights of  South Island
  One  of the odder coincidences  of physical  geography  is the  fact that  there are two  double islands, roughly the same   size, positioned at each other's antipodes , or farthest-distant point. The  islands of English  and Ireland in the Northern   hemisphere  and the islands of North Island  and South Island in the Southern Hemisphere  are just such a coincidence. The first two islands comprise the United Kingdom and the Republic of Ireland (or Eire) ,and the second two islands comprise New Zealand. Among these  four islands, there can be no  doubt that South Island  is the least polluted and most spectacularly scenic of them all.
  
  delight     美: [dɪˈlaɪt]  v.快乐；使欢喜 n.欢喜；爱好的事物；嗜好
  odd     美: [ɑd]  adj.奇怪的；怪异的；反常的；（某方面）怪异的 n.【高】让转弱的对手从
  physical 美 [ˈfɪzɪk(ə)l] n.体检；体格检查  自然 adj.身体的；肉体的；躯体的；客观存在的
  geography 美 [dʒiˈɑɡrəfi]  .地理环境；地形；地势；地理（学） 
oughly  美 [ˈrʌfli]  adv.大约；大致；差不多；粗暴地
position  美 [pəˈzɪʃ(ə)n]  n.位置；地位；职位；立场
antipodes  美 [æn'tɪpədi:z]  n.【化】对映体；恰恰相反的事物；【无线】对蹠点
hemisphere  美 [ˈhemɪˌsfɪr]  n.（地球的）半球；
comprise  美 [kəmˈpraɪz]  v.组成；构成；包括；包含
spectacularly 壮观地；引人注目地；引人入胜地
scenic 美 [ˈsinɪk]  n.风景影片；实景电影；风景照片[图片] adj.风景优美的；舞台布景
among  美 [əˈmʌŋ]  prep.在…中；周围是；在（其）中；…之一

  There is much competition to  make such  a claim. The  island of  English , politically  constituting English, Scotland,and  Wales  of the United Kingdom , is dotted with country  villages set alongside rivers and lakes.  There are not very  tall but nonetheless rugged mountains in the north, and endless miles of rocky coastline  that  seem mystical. Ireland , too, is a paradise of greenery, with far fewer  people than  populous    English and even  more quaint villages scattered  among its low-lying hills and forever green fields. North Island in New Zealand sports a  balmy climate and the beaches to make use of it;  One beach alone is more that 150 kilometers long, and with  relatively few people on its shores, on cant  pretend  one is  at the very end of the earth. Volcanoes,large lakes, and quickly flowing rivers traverse  the land. Given the beauty of these three islands, what makes South  Island so special ?

  climate  美 [ˈklaɪmət] n.气候；地带；水土；(社会思想等的)趋势 
  claim   [kleɪm] n.索赔；宣称；声明；断言  夺走生命
politically  美 [pəˈlɪtɪkli]  adv.政治上
  dot
美 [dɑt]  n.点；圆点；句点；【乐】附点  v.点缀；打点于；用点线表示；〈俚
paradise  美 [ˈperəˌdaɪs] n.天堂；伊甸园；天国；极乐
populous  美 [ˈpɑpjələs]  adj.人口众多的；人口密集的

nonetheless     美: [ˌnʌnðəˈles] adv.尽管如此

  Plenty. For  those who like mountains, South Island is  sure to please.Mt. Cook at 3.764 meters is its highest peak, with  16 others above 3,000 meters. Naturally, many local and foreign mountain climbers come here for  the  challenge of  these Southern Alps. In addition, there is an  extensive glacier system, endless forests,and innumerable lakes throughout this highland area. Some  of the world's best mountain  scenery is available within the 500-kilometer long chain of  the Southern Alps.

scenery      美: [ˈsin(ə)ri]       n.风景；景色；风光；舞台布景      网络景物；景观；景致

  Perhaps you prefer the  sea? South  Island is not only an  island, but many  tiny islets can be found  off its coastline.Great deep-sea fishing, scuba diving, and snorkeling can be had, though the waters here are cooler than those of North Island, (Remember, in the Southern Hemisphere, as we go north, it gets warmer.) As  fewer people  live on South Island than on North Island, those who crave  solitude and pristine beaches will be  amazed at their  luck here. With almost no heavy industry on SOuth Island,the  air, water, and land are all free of  pollution. The local seafood is therefore clean, plentiful, and never-ending.

  Of course, South Island is not for everyone. For those who  need busy, crowded,noisy, and polluted cities.this Southern outpost will surely disappoint. For those who enjoy pressure  and stress, South Island will leave them empty-handed. And for those who would rather stay at home or in an  office in  front of a computer screen or in the thumping,smoke-filled dance floors of discos, some of the world's best natural scenery will never  entice them away. For the rest of us, though,South Island is the world's best-kept secret.If Nature's paradise sounds alluring, make a point of visiting South Island.


  Do healthful climates interest you ? South Island is the place to be. Its temperate  climate sees little snow except in the highlands and mountains areas. Like Ireland and English, there are no extremes of temperature, either. Summers are warm, not hot, and winters are brisk ranther than  freezing. The fresh air is sometimes humid from the abundant rainfall  of this area.Every season invite the nature lover to get out  and be active in the countryside.



  


  中级的可以抄一下  初级直接读就好了呢 

  
** Lesson 8 Ireland's Contribution  to English
   Nearly  everyone knows  that countries such as the United Kingdom, the United States of America,Canada, Australia, and New Zealand  are primary English-speaking countries;  that is  English  is the mother tongue used in these countries. What  is less well known  is that English is also  the mother tongue in countries such as the Republic of Ireland (officially called Eire), Barbados,Jamaica,Trinidad, and Guyana. Among these latter few, the Irish have made contributions to the English  language in both  its lexicon and literature  which  can be considered second to none.
latter     美: [ˈlætər]   后者 刚刚提到
lexicon     美: [ˈleksɪˌkɑn]  n.字典；（某语言或学科、某人或群体使用的）全部词汇
   literature     美: [ˈlɪt(ə)rəˌtʃʊr]  n.文学；文学作品；资料
consider      美: [kənˈsɪdər]  v.认为；觉得；以为；顾及

  Virtually every  aspect of  English  literature has been graced by the  writings  of  the Irish. This  face  is all the more amazing because Ireland is a relatively  small country,with  never more than  four million people throughout its long history. Yea  many great "English" writers were indeed  born and often  raised in Ireland, though many, too, emigrated to the united Kingdom  at some point in their lives.Among these pillars of  English literature were Jonathan Swift,William Butler Yeats,James Joyce, Samuel Beckett, Oscar WIde,George Bernard Shaw,and  Edmund Burke. Many other lesser-known figures have punctuated English literature as well. These men's contributions to the English  language and to Western thought in general are immeasurable. A review of two of these writers' major works will reveal why.

  virtually      美: [ˈvɜrtʃuəli]   adv.几乎；实际上；事实上；虚拟
  aspect     美: [ˈæspekt]  n.方面；层面；外观；方位
literature     美: [ˈlɪt(ə)rəˌtʃʊr]  n.文学；文学作品；资料
grace     美: [ɡreɪs] n.恩典；优雅；宽限期；优美 v.装饰；为…增色；为…锦上添花；使荣耀
million    美: [ˈmɪljən]  num.一百万；大量 n.无数；百万元；百万(镑,

09:00  第三 段

emigrate    美: [ˈemɪˌɡreɪt] v.移居(外国)；迁出；使移居
pillar     美: [ˈpɪlər]  n.柱；栋梁；纪念柱；(柱)墩 v.用柱子装饰[支持]；成为…的栋梁
punctuate      美: [ˈpʌŋktʃuˌeɪt]     v.不时打断；给…加标点符号    网络强调；加标点于；不时介入
immeasurable      美: [ɪˈmeʒərəb(ə)l]   adj.不可估量的；无限的；无穷的
review    美: [rɪˈvju] n.回顾；述评；审查；评论
reveal     美: [rɪˈvil]  v.透露；揭示；显示；展示 n.启示；【建】窗侧壁；门侧；(汽车的)窗框
satire 讽刺


**  Lesson 9 Why  Is Basketball  So Popular?   Tuesday  July twnety-sixth 2022
    Soccer and baseball  have  more fans, but no other sport has increased in popularity so quickly  over the pass 30 years than  has basketball. What accounts for the sudden meteoric rise in a sport which, after all, is  played best by people who are  unusually tall ? The secret to  basketball's  success lies is three particular sources: the celebrities  in  game; commercial sponsorship of  those players and the game itself; and  the mushrooming of crowded, urban environments around the world.

increase     美: [ɪnˈkris]  n.增加；增长；增多  v.增加；增多

meteoric      美: [ˌmitiˈɔrɪk]       adj.迅速成功的；流星的

lie       美: [laɪ]   n.谎言；休息；虚伪；诺言  v.躺；在于；欺骗；位于
particular      美: [pərˈtɪkjələr]   adj.讲究；挑剔；专指的；不寻常的  n.（正式记下的）细节

celebrity       美: [səˈlebrəti]       n.名人；名声     网络名流；社会名流；明星

commercial     美: [kəˈmɜrʃ(ə)l]  adj.贸易的；商业的；赢利的；以获利为目的的
n.（电台或电视播放的）广告
sponsorship      美: [ˈspɑnsərʃɪp]   n.资助；主办；赞助款；倡议

    mushroom  美: [ˈmʌʃˌrum]   n.蘑菇；蘑菇状物；蘑菇状烟云；〈口〉(女用)蘑菇形草帽 v.迅速增长；采集蘑菇；子弹打扁成蘑菇形；〈美〉(火)猛然的扩大

  All sports have their heroes. Current, baseball has Mark McGuire and  Sammy Sosa, the home  runhitting kings, Tennis has Martina Hingus and  Pete Sampras,the darlings of the courts, Soccer has players so popular that  they are mobbed by fans wherever they appear, especially in Europe and South America. ONly basketball, however,has celebrities who have caught the attention of the world like no others. Michael JORDAN is popular even  after having officially retired from  the game that there is talk of  his running for public  office in the United States. Dennis Rodman,the muscular,tattooed, and much ballyhooed player formerly of  the Chicago Bulls, make headlines whenever he pulls  another of his crazy but fun-loving publicity stunts. Former players like Larry Byrd and Magic Johnson continue to command respect for their personal integrity and unparalleled sportsmanship. Basketball shoes, T-shirts, and  even movies are make with  these basketball superstar icons. No other sport figures can compete with their popular recognition and appeal.

  be mobbed by 包围

  retired     美: [rɪˈtaɪrd]       adj.已退休的；已退职的      v.“retire”的过去分词和过去式
  run for 竞选
muscular      美: [ˈmʌskjələr]       adj.肌肉的；强壮的；肌肉发达的     网络强健的；肌的
  ballyhoo      美: [ˌbæliˈhu]   n.喧闹；大吹大擂的广告[文章,演说] v.大肆宣传；为…大吹大擂

  Is this international superstar status solely due to  these men's  talents and contributions? In no small part,of course,it is , but  other leading athletes with equally commendable skills or who have performed  attention-grabbing antics rarely  reach the stratospheric level of stardom that basketball players  enjoy. This special privilege is due  to a concerted effort by the players behind  the basketball players, that is, the basketball leagues' owners and sponsors.

solely     美: [ˈsoʊlli]  adv.只；仅；唯；单独地
  privilege     美: [ˈprɪvəlɪdʒ]      n.荣幸；荣耀；特殊利益；优惠待遇      v.给予特权；特别优待     网络权限；特别待遇；特免
  

  Basketball has  always  been a distant third in sports rankings in the United Status behind baseball and American  football. Basketball league owners and managers wanted to change this traditional perception of the immutability of these statistics and in the 1960s began a concerted effort to make basketball the game  of choice by hand-picking more colorful as well as professional players and  by making alliances with  the commercial sponsors of athletic equipment. By the 1970s, basketball team recognition in the U.S. had soared, with dedicated fans in the millions. Teams like the Los Angeles Lakers, the Chicago Bulls, and the Boston Celtics had become household names. Players like  Magic Johnson  and Michael Jordan were  worth milions of dollars in commercial advertising  spots for  athletic equipment  manufacturers, a trend which  continues to this  day. Today , basketball is  a billion-dollar business.

  distant     美: [ˈdɪstənt]   adj.遥远的；远处的；久远的；不相似的   athletic     美: [æθˈletɪk]  adj.健壮的；体育运动的；田径运动的
ranking     美: [ˈræŋkɪŋ]      adj.第一流的；首席的；高级的；干部的     n.顺序；【统】秩评定     v.“rank”的现在分词
    网络排行榜；排名资料；当地前十名的排名
league     美: [liɡ]   n.联赛；联盟；协会；种类  v.(使)结盟；(使)联合[团结]；一鼻
perception     美: [pərˈsepʃən]      n.感知；知觉；看法；洞察力     网络感觉；认知；理解
immutability     美: [ɪˌmjutə'bɪlətɪ]   n.不变性
statistics     美: [stə'tɪstɪks]  n.统计学；统计数字[资料]；
alliance     美: [əˈlaɪəns]  n.联盟；联姻；同盟条约；同盟者
commercial     美: [kəˈmɜrʃ(ə)l]   adj.贸易的；商业的；赢利
manufacturers, 制造商 
  equipment 英 [ɪˈkwɪpmənt] 美 [ɪˈkwɪpmənt] CET4 TEM4 
    n. 设备，用具；（对某人或某物的）装备
trend     美: [trend]  n.趋势；动向；趋向；动态    
    
   No amount of advertising,  however, can account for  the number of fans who  not only double as spectators  but as  players themselves. Basketball
   courts, whether in schools,parks, or abandoned  city lots, have sprouted throughout the urban landscape.  A child is never far from a basketball ball and hoop.  With land becoming more expensive in ever more crowded cities, city governments  are fat more likely  to construct basketball courts than  baseball diamonds or soccer fields. As basketball equipment is minimal and inexpensive , it is no wonder that the game  has become more and more popular around the world.

   spectator     美: [ˈspekˌteɪtər]  n.旁观者；(看比赛等的)

   What young boy doesn't dream of becoming as tall  as a  basketball player, or at least of having  as much money or fame? Basketball's quick pace and dynamic plays are in contrast to the much slower moves in baseball or even   in much of soccer and American football. This dynamism is part of the pulse of our times, and so long as  we live in  a fast-chang-ing  world,basketball  and  its players will continue to appeal to sports lovers around the wold. 

   dynamic     美: [daɪˈnæmɪk]  
    n.动力；动力学；推动变化的力量
    adj.充满活力的；活跃的；精力充沛的；不断变化的
    网络动态；动态的；动力的

    pulse    美: [pʌls]  n.脉冲；脉搏；脉率；强劲的音乐节拍 v.搏动；跳动；震动；洋溢着

    appeal     美: [əˈpil]  n.上诉；吸引力；申诉；魅力
    





    
** Lesson 10(tenth)  Marlena  Smalls  and  the Gullah: The Revival of a  Unique  Community  
  Sunday  auguest twenty-first

   Does  the name  Marlena Smalls   ring a   bell? Probably  not, At least not yet. If  this large woman  with an even larger  smile and sparking eyes has   her way,  however , the language,  customs, and songs of  the Gullah will  become happily familiar  to millions of  people  outside of the Sea Islands. For  it is Mrs. Smalls' dream  that through her  and her performing troupe's  efforts their Gulah community will no longer  be an  isolated,  anachronistic hangover from the days of slavery in the United  States, but a  vibrant cultural addition to the 21st century  global village.
  
Gullah  ['gʌlə]n.古勒语  spark [spɑrk] n.火花；火星；(钻石等的)闪光；(目光的)闪耀
revival   [rɪˈvaɪv(ə)l] n.复兴 community  [kəˈmjunəti] n.社区
unique  [juˈnik] adj.唯一的  shell 中的就常用   performing [pərˈfɔːrmɪŋ]    adj.表演的；演奏的；完成的；(狗等)会玩把戏的 v.“perform”的现在分词
troupe  [trup] 剧团；歌唱团 isolated  [ˈaɪsəˌleɪtəd] v.分离
anachronistic  [əˌnækrə'nɪstɪk] adj.时代错误的 过时的；落伍的；不合时宜
hangover [ˈhæŋˌoʊvər] n.宿醉（过量喝酒后第二天的头痛以及恶心反应）；遗留的感觉
vibrant [ˈvaɪbrənt] adj.充满生机的；生气勃勃的  addition  [əˈdɪʃ(ə)n]n.添加；增加；

   The  Sea Islands  comprise a group of islands just off  the  southeast  U.S. Atlantic coast of South Carolina and Georgia.    Descendants of slaves settled  here  tilling the fertile land of these  islands  and the adjacent coastline. A rich overlay  of a  mixture of West  African  languages  onto 17th and 18 th  century   colonial English  has resulted  in Gullah, a creole  language featuring its  unique  blend  of African  tongues  and  pidgin English . Thousands of distinct African words  coming  from various West African languages  have  been identified  by  linguists. A few  words  have been added into  contemporary  mainstream  American English . These include  goober(peanut), gumbo(okra), and voodoo(witchcraft). The word Gullah  itself also  hails from West Africa.  Many  of this  ethnic group's  given names are taken directly from languages passed down  for  hundreds of years,  such as Abiona and Ptitiap.  American English is the language  used  when  dealing with  outsiders, but Gullah is  the  language  of the marketplace and the home. 

   settle   [ˈset(ə)l]v.定居；                                                                                                                                                    
 comprise [kəmˈpraɪz] v.组成；构成 Carolina   [ˌkærə'laɪnə]n.(美国)卡罗来纳                                                                                                  
 descendant  [dɪˈsendənt]n.后代；弟子后裔  fertile [ˈfɜrt(ə)l] adj.肥沃的；富饶                                                                                              
 adjacent  [əˈdʒeɪs(ə)nt] adj.与…毗连的；邻近的   contemporary  [kənˈtɛmpəˌrɛri] adj.现代的；当代的                                                                          
 creole  [ˈkriˌoʊl]n.克利奥尔人 unique  [juˈnik]     adj.唯一的                                                                                                              
 hail from 来自    blend [blend]v.混合；  pidgin: [ˈpɪdʒɪn] 混杂语言； pigeon [ˈpɪdʒən] n.【鸟】鸽子                                                                         
 distinct [dɪˈstɪŋkt] adj.清晰的；清楚的；明白的 不同的   mainstream  [ˈmeɪnˌstrim]  主流 (看词组成就知)
 linguist  [ˈlɪŋɡwɪst]语言学家   ethnic  [ˈeθnɪk]    adj.民族的；种族的 
   
   As  with most African cultures, the  Gullah have a  rich  tradition of music. The  banjo, a stringed musical instrument, was   an African invention  brought over with  
 the slaves to the New World. It has  been popularized   in both  North America  and   Europe   over   the past  200 years. A great  variety  of drums,  too, accompanied    African music  to the colonies in  North  and South  America. Singing  both solo and a  cappella  with  rich harmonies  was also part of the slave heritage. Despite their   demanding  and depressing lives, the slaves  held their  original languages   and music  as  well  as their  masters'  Christianity close to  their   hearts.        Much  of the music  today  involves church music, also referred  to as spirituals or gospel music.  


 stringed  [strɪŋd]adj.有弦(乐器)  instrument  [ˈɪnstrəmənt] n.仪器；仪表；                                                                                                  
 invention  美 [ɪnˈvenʃ(ə)n] n. 发明物；发明，创造；虚构，编造 popularize  [ˈpɑpjələˌraɪz]v.推广；使通俗化；使大众化；使流行                                                 
 variety  [vəˈraɪəti] n.品种；变化  drum [drʌm]n.鼓；滚筒 colony [ˈkɑləni]n.殖民地                                                                                           
 accompany   [əˈkʌmpəni]v.陪伴；陪同； a  cappella  /ˌɑː kəˈpel.ə/  伴奏；合唱团                                                                                             
 harmony  [ˈhɑrməni] n.【乐】谐调； 和声 调和；融洽；适应  heritage [ˈherɪtɪdʒ] n.遗产                                                                                       
 despite  [dɪˈspaɪt]prep.尽管；即使 demanding  [dɪˈmændɪŋ] adj.要求高的；需要高技能（或耐性等）的；费力的；要求极严的                                                        
 depressing [dɪˈpresɪŋ]    adj.令人抑郁的；令人沮丧的；令人消沉的  involve  [ɪnˈvɑlv]    v.涉及；含有…的意义；使陷入；围住                                                   
 refer [rɪˈfɜr]v.提到；引用 spiritual  [ˈspɪrɪtʃuəl]     adj.神的；信仰上的；精神(上)的；心灵的                                                                              
 gospel  [ˈɡɑsp(ə)l]    n.福音  

 
stringed  [strɪŋd]adj.有弦(乐器)  instrument  [ˈɪnstrəmənt] n.仪器；仪表；  
invention  美 [ɪnˈvenʃ(ə)n] n. 发明物；发明，创造；虚构，编造 popularize  [ˈpɑpjələˌraɪz]v.推广；使通俗化；使大众化；使流行
variety  [vəˈraɪəti] n.品种；变化  drum [drʌm]n.鼓；滚筒 colony [ˈkɑləni]n.殖民地
accompany   [əˈkʌmpəni]v.陪伴；陪同； a  cappella  /ˌɑː kəˈpel.ə/  伴奏；合唱团
harmony  [ˈhɑrməni] n.【乐】谐调； 和声 调和；融洽；适应  heritage [ˈherɪtɪdʒ] n.遗产
despite  [dɪˈspaɪt]prep.尽管；即使 demanding  [dɪˈmændɪŋ] adj.要求高的；需要高技能（或耐性等）的；费力的；要求极严的
depressing [dɪˈpresɪŋ]    adj.令人抑郁的；令人沮丧的；令人消沉的  involve  [ɪnˈvɑlv]    v.涉及；含有…的意义；使陷入；围住
refer [rɪˈfɜr]v.提到；引用 spiritual  [ˈspɪrɪtʃuəl]     adj.神的；信仰上的；精神(上)的；心灵的
gospel  [ˈɡɑsp(ə)l]    n.福音 

   An  evening  with Marlena Smalls  and her Hallelujah  Singers is nothing  short  of inspirational. They  are dressed  at times  in  traditional  African clothing, and at other  times  in the  simple  and conservative  rural  dress  of Southern U.S. society .  This  unusual performance  includes much singing frequent samples of Gullah as  used in  the marketplace or  between women gossiping. A great  deal of emphatic  body  language, and even occasional tribal dance steps to thumping drums and enthusiastic  shouting are also features  of the performance. Mrs.  Smalls  introduces  the background to  indivadual songs or other performances to help the audience -- often  peppered with overseas tourists   -- have a clearer  idea  of how the Gullah communicate to each other. Even without  the helpful introductions , howerve, music  lovers will appreciate the peerless singing quality of the Hallelujah Singers as they  render their  traditional folk songs with obvious love and pride. Interspersed with Mrs. Smalls with and  classy narrative, the evening passes all  too quickly.

hallelujah  [ˌhæləˈlujə]n.哈利路亚（意为赞美上帝）  inspirational  [ˌɪnspɪˈreɪʃən(ə)l]adj.启发灵感的；鼓舞人心的
conservative [kənˈsɜrvətiv] n.守旧派；简单 保守的人；守旧的人 rural [ˈrʊrəl] adj.乡村的；农村的；似农
society  [səˈsaɪəti]n.学会；协会；社团；交往  frequent  [friˈkwent]adj.频繁的；经常发生的
gossip  [ˈɡɑsɪp]v.说长道短  emphatic [emˈfætɪk]adj.强调的；有力的；明确表示的；加强语气的
occasional  [əˈkeɪʒən(ə)l] adj.偶尔的；偶然的  tribal  [ˈtraɪb(ə)l]    adj.部落的；部族的
thumping  ['θʌmpɪŋ]adj.很大的；巨大的 drum [drʌm]n.鼓；滚筒
enthusiastic  [ɪnˌθuziˈæstɪk]adj.热情的；热心的；热烈的 individual [ˌɪndɪˈvɪdʒuəl]n.个人；与众不同的人；有个性的人
audience  [ˈɔdiəns]n.观众；读者  pepper [ˈpepər] v. 混合n.胡椒粉；甜椒；柿
tourist [ˈtʊrɪst]n.游客； appreciate  [əˈpriʃiˌeɪt]v.欣赏；感谢；感激；升值
peerless [ˈpɪrləs]    adj.无双的；杰出   render [ˈrendər]v.提供；给予  演出
folk  [foʊk] n.人们；民间音乐；亲属；各位 obvious  [ˈɑbviəs]adj.明显的；显然的
classy [ˈklæsi] adj.上等的；豪华的；时髦的网络优等的；漂亮的；优雅 narrative [ˈnerətɪv]n.叙述；讲故事；叙事技巧

   It is  refreshing to know that some ethnic groups are proudly clinging to their  priceless legacies. Despite the tragedy  of their  origins in slavery, the Gullah have survived and revived  to produce a viable , enviable  folk  culture even amidst the  technological  wonders of the 21st century. We can  be thankful that in concert or on recorded media, Marlena Smalls and the Hallejujah Singers will  touch all fo us listeners with their  heartfelt oral tradition throught the magic of music.

refreshing  [rɪˈfreʃɪŋ]adj.令人耳目一新的     ethnic [ˈeθnɪk]adj.民族的
proudly  ['praʊdli]    adv.骄傲地  clinging [ˈklɪŋɪŋ]adj.紧身的；贴身的 紧握不放 to
legacy  [ˈleɡəsi]    n.遗产 priceless 无阶
tragedy [ˈtrædʒədi] n.悲剧 slavery  [ˈsleɪv(ə)ri]n.奴隶制；奴隶身份
survive  [sərˈvaɪv]v.在…之后还活着；经受得住；网络幸存  revive [rɪˈvaɪv]    v.复活；恢复
viable [ˈvaɪəb(ə)l] adj.可实施的；切实可  amidst [əˈmɪdst]prep.在…的当中
wonder  [ˈwʌndə(r)]n.奇迹；惊奇；惊叹 
oral [ˈɔrəl]adj.口头的；用口的；口腔的；口服的
produce [prəˈdus]v.生产；制造；制作；出示n.产品；（尤指）农产品网络产生；出产；产物

   Auguest 22  21:25 --   23  11:50
   
**  Lesson  12  The Louvre:  The  World's  Best  Museum?
   Paris, City of Light, and  of art.  A playland for  lovers and a painter's  dream. What  better  place  to situate the louvre, considered by many to be the world's  best  museum of  art? What  makes this museum so worthy fo that honor?

situate  [ˈsɪtʃuˌeɪt] v.使位于；使坐落于
  properly  [ˈprɑpərli] adv.正确地；适当地；恰当地；得体地
  complex [ˈkɑmˌpleks]n.情结；（类型相似的）建筑群；相关联的一组事物；不正常的精神状态
    adj.复杂的；
formerly  [ˈfɔrmərli]  adv.以前；从前；原来；过去 finest 最好的
redesign [ˌri:dɪ'zaɪn]n.新设计 v.重新设计 fortress  [ˈfɔrtrəs]  n.堡垒；要塞；城堡；设防的地方
subsequent  [ˈsʌbsɪkwənt] adj.随后的 后来的  minister [ˈmɪnɪstə(r)] n.部长；牧师；公使
stock  [stɒk] n.库存；储备 revolution  [ˌrevəˈluʃ(ə)n]     n.革命；旋转；巨
controversial  [ˌkɑntrəˈvɜrʃ(ə)l]adj.引起争论的；有争议的
pyramid-shaped  金字塔   pyramid  [ˈpɪrəmɪd]     n.锥体；（古埃及的）金字塔；
architect  [ˈɑrkɪˌtekt]  n.建筑师；设计师；缔造者；创造者 网络架构师；                                                                              
consequence  [ˈkɑnsəkwəns] n.后果；结果  continuous  [kənˈtɪnjuːəs] adj.连续的；不间断的；
construction  [kənˈstrʌkʃ(ə)n] n.施工；建筑  amass  [əˈmæs] v.积聚；收集
treasure  [ˈtreʒər] n.宝藏；财富

  The  museum building,  or, more properly, the  complex of buildings  themselves is a good place to start. As  with  most Western  and a few Asian and   South  American museums, large  palaces or other  traditional architecture are used   to house   museums  of  art and of natural science.  In  the case   of the Louvre,  officially known as   Paris du  Louvre (the Palace of the Louvre),  the main building used  today was  formerly the fortress of King  Philip Augustus in the 12th  century. Not until 1546 did  King Francis I begin  to redesign and add onto  the fortress. Subsequent kings  did   the same, especially  during the 17th century  with  major additions by  Louis XIII and Louis XIV.  Not only did  these  kings and their ministers add to the buildings , they also  stocked within their rooms  the finest art  that  money could buy.   After the  French  Revolution, the  Palais du Louvre  was   opened to the public. In the early 19th  century, both Napoleon and Napoleon III  added to both the structures and the collections . A controversial see-through glass  pyramid-shaped structure  was added by the architect I.m.Pet in the 1980s. As a  consequence of centuries  of continuous construction and amassing of art  treasures, today the Louvre offers a  world-class  collection   of both  French and foreign  art.

The  outer shell of a museum, however, no matter  how artistic or historic, cannot  alone make a museum truly great. The inner collections are of course of  paramount interest to both the   art researcher and art lover alike.  The Lovre does  not disappoint them.  Three  of the West's premier works of art are here: the statues VIctory of Samothrece and Venus de Milo accompany Leonardo DA vinci's  most famous painting,  the Mona Lisa. These alone  attract art devotees from around  the world, but far more awaits them. The French  painting  collection is ,  not  surprisingly, unsurpassed. Other major  painting collections include works from the middle ages and Renaissance. The treasures of the French royalty are on display here, too, such as their bronzes, miniatures, potery, tapestries, jewelry, and furniture. Greek, Roman, Egyptian , and Mesopotamian  antiquities as well as early Christian   artifacts  are also  considered important  collections. This  clearly is not a  museum to be seen in one morning!

shell [ʃel] n.壳；炮弹； inner [ˈɪnər]n.内部；射中接近靶心部分的一发adj.里面的
course  [kɔː(r)s]     adv.〈口〉当然n.过程；航向；球场；【教】课程
paramount [ˈperəˌmaʊnt] n.最高元首；首长adj.至为重要的；首要的  premier [prɪˈmɪr] n.总理；地区总理  adj.首要的；
devotee  [ˌdevoʊˈti] n.热爱者 surprisingly  [sərˈpraɪzɪŋli] adv.令人惊讶地
unsurpassed  [ˌʌnsərˈpæst] adj.无比的；卓绝的  renaissance  [rɪˈneɪsəns] n.文艺复兴（欧洲 1
royalty  [ˈrɔɪəlti]n.版税；王室成员  皇室；皇族   bronze [brɑnz] n.青铜；青铜制品
miniature  [ˈmɪnɪtʃər] (象牙等上的)微小画像   pottery  [ˈpɑtəri] n.陶器
tapestry [ˈtæpəstri] n.壁毡；家具的绣[织]花罩毯 挂毯；挂毡；壁毯
jewelry  美 [ˈdʒuːəlri]      n.珠宝；首  furniture [ˈfɜrnɪtʃər] n.（可移动的）家具
antiquity  [ænˈtɪkwəti]n.古物；古

 Finaly, the site of the museum complex  contributes to  the  mysigue of the Louvre. Paris has long been considered one of the world's most charming cities, with  its endless winding  streets amidst spectacular royal and religious architecture. The  fortress built by King Philip Auguestus was situated on  the right bank of the Seine, overlooking -- at that  time -- splendid  bucolic scenery. Today  this prime location is within walking   distance of many major Parisian tourist attractions, like the Cathedral of Notre Dame, the Royal Palace, and the National Library. One  could  easily spend a whold week touring the heart of  Paris centered around the Louvre.

attraction  [əˈtrækʃ(ə)n] n.吸引；魅力；引人注意的东西 景点
contribute  [ˈkɑntrɪˌbjut] 有助于 v.投稿；捐款；  mystique [mɪˈstik] n.神秘性
spectacular  [spekˈtækjələr] adj.壮观的；壮丽的 fortress [ˈfɔrtrəs]n.堡垒；要塞；城堡
tourist  [ˈtʊrɪst] n.游客  attraction  [əˈtrækʃ(ə)n] 景点n.吸引；魅力

  Taken  altogether, then , the Louvre holds its own as on  of the best museums -- if not  the best --among the dozens  of major  and internationally famous art museums  around the world. Its many and varied buildings, the unparalleled collection of prestigious works of art, and the delightful site of the grounds  overlooking France's  most famous river all contribute to make the Palais duLouvre a must-see  attraction for the serious art connoisseur and art museum-goer alike. Meet you at the Louvre . 

unparalleled  [ʌnˈpɛrəˌlɛld] adj.无可匹敌的  prestigious  [preˈstidʒəs] adj.有威望的；声誉高的

dozen  [ˈdʌz(ə)n] n.若干；十二个 varied  [ˈverid] adj.各种各样的；形形色色的；不相同的；变化的     v.“vary”的过去式和过去分词
delightful  [dɪˈlaɪtfəl] adj.使人快乐的；令人愉快的；宜人的


**  Lesson 13 The Ivy League Schools: Excellence in Education
lineage [ˈlɪniɪdʒ] n.世系；血统   league [liɡ] n.联赛；联盟

 The first permanent English settlement in the New World was  at Plymouth Bay in what  is now  the state  of Massachusetts  in 1620. Merely 16 years later, a group of successful settlers in New Town(renamed Cambridge after their  alma mater) started a college. They named it after the Puritan minister  who  willed half his  estate and all his books to  the college  This  clergyman's  name was John  Harvard, and  his namesake  remains the most prestigious among the more than 2,000  institutes of higher  education  in the United States today.

permanent [ˈpɜrmənənt] adj.永久性 settlement [ˈset(ə)lmənt] n.解决；移民
merely [ˈmɪrli] adv.仅仅；只不过 只是；仅仅地  alma mater 母校
puritan [ˈpjʊrɪt(ə)n] adj.清教徒的；  minister [ˈmɪnɪstə(r)] n.部长；牧师；公使
clergyman ['klɜ:dʒimən] 牧师 神父
will [wɪl] v.想要；希望；喜欢 遗嘱 立遗嘱  estate [ɪˈsteɪt] 财产； 产业
namesake [ˈneɪmˌseɪk] 依某人名取名者 prestigious [preˈstidʒəs] adj.有威望的 有声望的；有名望的
institute [ˈɪnstɪˌtut] n.学院；学会； 学府   at will .任意；随意 随心所欲；任意地；随意地

 Harvard is  not the only great school in the U.S. , of course. A  small industry has  grown  up around the ranking of the best tertiary schools,and year  after year,seven  schools dominate  most of these Top Twenty or Top Fifty lists. Harvard is nearly  always at or close to the top, joined frequently by Yale(in Connecticut),Princeton(in New Jersey), Dartmouth(in New Hampshire),Cornell(in New York State), Columbia(in New York City), the University  of Pennsylvania, and Brown(in Rhode  Island).  These eight private universities are collectively referred to  as the Ivy League schools.

ranking [ˈræŋkɪŋ] n.排名adj.地位高的；高级的；最高级的；…级别的v.“rank”的现在分词
tertiary [ˈtɜrʃəri] adj.第三的；大学的  dominate [ˈdɑmɪˌneɪt] v.控制；支配；影响
frequently [ˈfrikwəntli] adv.频繁地；时常
collectively [kəˈlektɪvli]adv.集体；总称 refer [rɪˈfɜr] v.提到；引用 
top-notch adj.最好的；卓越的；第一流的


 Why  the name ? Ivy  is a vine; that is, a plant which grows  up or along the surface of other plants such as trees, or , in the  human landscape,  along the sides of stone buildings. As these  eight  universities are old(the youngest among them,Cornell, was  founded in 1853),ivy has had  plenty of time to decorate the outsides of the more historic buildings on these campuses. The  word league, however, is more an invention of imagination  than  a reality . Though  there is an association called the Ivy League, it refers to the above schools's  participation in an Amercan  football   athletic conference rather  than  to any academic alliance. Further, despite the  lengthy academic  lineage of these  schools,  the footballing Ivy League was not  formally formed until 1956, though highly competitive football and other athletic games have been hotly contested among the schools for many generations.

vine [vaɪn] n.藤；藤蔓   ivy  [ˈaɪvi] n.【植】常春藤
surface [ˈsɜrfəs] n.表面；地面；表层  landscape  [ˈlændˌskeɪp] n.景色；景观
decorate [ˈdekəˌreɪt] v.装饰； historic [hiˈstɒrik] adj.历史上有名的；具有历史价值的
campus [ˈkæmpəs] n.〈美〉校园；大学 校区  invention [ɪnˈvenʃ(ə)n] n.发明；创造；虚构；编造
imagination [ɪˌmædʒɪˈneɪʃ(ə)n] n.想象；association [əˌsoʊʃiˈeɪʃ(ə)n] n.协会；社团
participation [pɑrˌtɪsɪˈpeɪʃ(ə)n] n.参与；参加   athletic [æθˈletɪk] adj.体育运动的；田径运动的  结盟
conference [ˈkɑnf(ə)rəns] n.研讨会；  rather than 而不 而不是

academic [ˌækəˈdemɪk] adj.教学的；学术性的（与实践性、技术性相对）学术的
alliance  [əˈlaɪəns] n.联盟；  further [ˈfɜrðər] adv.进一步；况且  此外；更远；而且
despite [dɪˈspaɪt].尽管；即使 lengthy [ˈleŋθi] adj.漫长的； 历史悠久
lineage [ˈlɪniɪdʒ] n.世系；血统  formally adv.正式地； 正式的 
form [fɔrm] v.形成；成立   highly [ˈhaɪli]adv.非常；很；高标准地
highly competitive 高度竞争；富有竞争力；竞争多元化
competitive [kəmˈpetətɪv] adj.竞争的有竞争力的 比赛的
contest [kənˈtest] v.竞争n.竞争；竞赛   hotly [ˈhɑtli] adv.热烈地 激动地
 
    Since  these institutes of higher  learning   had such an early  start in the  history of the United States,  it  is  not surprising  that they  should individually and collectively have  exerted  a great influence on American society. Their status within   national scholarly circles is unparalleled .  Admission to these  universities is  highly demanding: many  students apply for every  one lucky enough to be accepted. As these  universities are  private, they are relatively expensive. Offsetting the extremely  high  tuition are many opportunities for scholarships. These  scholarships are awarded to meritorious students regardless of their  backgrounds.

institute [ˈɪnstɪˌtut] n.学院；学会   higher learning 高等教育 高等学府
individually [ˌɪndɪˈvɪdʒuəli] adv.单独地；分别地；各别地
collectively [kəˈlektɪvli] adv.集体；共同      exert  [ɪɡˈzɜrt]v.使受(影响等)
status [ˈstætəs] n.地位；身份            scholarly [ˈskɑlərli] adj.学术的；学术性的
circle [ˈsɜrk(ə)l] n.圈；圆；圈子；社交圈  unparalleled [ʌnˈpɛrəˌlɛld] adj.无可匹敌的 
admission[ədˈmɪʃ(ə)n]n.允许进入;入学 地许可 demanding [dɪˈmændɪŋ]adj.要求高的
apply for  v.寻求；申请  apply [əˈplaɪ]v.应用申请；适用；套用
accept [əkˈsept]v.承认；接纳；同意； relatively [ˈrelətɪvli]adv.相当程度上；相当地
offset [ˈɔfˌset]v.抵消；弥补；补偿  extremely [ɪkˈstrimli]adv.非常；极其
tuition  [tuˈɪʃ(ə)n]n.指导；（尤指大专院校的）学费
opportunity [ˌɑpərˈtunəti]n.机会；方便  scholarship [ˈskɑlərˌʃɪp]n.奖学金
award [əˈwɔrd]n.奖品 v.授与   meritorious [ˌmerɪˈtɔriəs]adj.值得赞扬的 一等奖；有功
regardless [rɪˈɡɑrdləs]adv.不顾；不管 

  Additionally,  the  roster of the faculties of these  schools  reads  like  a  Who's Who list of   important Americans(and  quite  a few foreigners, as well).  Their  intellectual  integrity  shows in the number  of Nobel and other  major prizes  awarded  which  they  have garnered over  the years. Some  of the country's  most famous  doctors, statesmen, engineers, scientists, and educationists  have studied and taught within  these  ivy-covered walls.  No fewer  than 14 U.S. presidents have  earned degrees here,including six at Harvard, six at Yale,and two  at Princeton.

additionally [əˈdɪʃ(ə)nəli]adv.另外  roster [ˈrɑstər]n.花名册
faculty [ˈfæk(ə)lti]n.全院[系]教授 院系学校  intellectual [ˌɪnt(ə)lˈektʃuəl]n.知识分子
integrity [ɪnˈteɡrəti]n.完整；诚实正直；完好  garner [ˈɡɑrnər]收集

  
  Though  only a   select few  can join the  ranks as Ivy Leaguers each year, Americans are endowed  with a  world-class  tertiary  educational  system  second  to none.  Note every  graduate from an Ivy League  school "makes the grade" in life;   even   a first-rate education is no guarantee  of success. Still, those  who do  enter  and leave  the Ivy  League  universities in the  northeastern  United States  have a much  better   than   average  chance  to join  the ranks fo the movers and shakers of   not only the U.S. society, but,once  back  in their   home countries, of their  native   lands as well. 

rank [ræŋk]n.队伍   endow [ɪnˈdaʊ] 使ju有某种特质
tertiary [ˈtɜrʃəri 高等 first-rate adj.第一流的
guarantee [ˌɡerənˈti]v.保证；保障  
grade [ɡreɪd]n.品级；水平   




  



 

** Lesson 15  Webcames: Electronics Tools  or  the End of Privacy?
  What are webcams? The  word webcam  is a  compound word formed from  two abbreviations, "web" from the World Wide Web and "cam" from camera. Webcams are cameras which  are situated at various places and  linked to the  World Wide Web. They allow 24-hour viewing of a wide array of places and activities around the world. They can be as educational as they  are fascinating, entertaining as they are eye-opening. Not everyone raves about this new technology,   however. Some cite sinister implications in a technology which  can unobtrusively spy  on our goings-on without our permission.  Others note  that with  rapid increases in telephotography and the science of acoustics, the days of privacy are numbered. Anyone can mount a webcam with  a telephoto  lens and microphone, aim it at his neighbors's liveing room or bedroom, and the broadcast one's "private" life to the  whole world. A script for the next scifi film, or a  current reality? Are these doomsayers overreacting, or is  their  charge(指控) legitimate ?

compound  [ˈkɑmˌpaʊnd]a.混合；混合的；复合物合成的  form  [fɔrm]  v.形成；成立；产生；；组织；格式；形态
abbreviation [əˌbriviˈeɪʃ(ə)n]  n.缩写         situated [ˈsɪtʃuˌeɪtɪd] adj.位于；坐落在；处于…状况；处境…      
ascinate  [ˈfæsɪˌneɪt]   adj.极有吸引力的；迷人的 
various [ˈveriəs]      adj.各种不同的；各种各样的；具有多种特征的；多姿多彩的     网络各种的；多方面的；多样的
a wide array of  各式各样的
entertaining  [ˌentərˈteɪnɪŋ]n.招待 adj.有趣的；娱乐的 activity   [ækˈtɪvəti]   n.活动；活性；动作；功能
rave  [reɪv] n.(人,风,浪的)狂闹；怒吼v.(狂人一般)说胡话；咆哮；发狂似地讲；狂喜 (about of)
cite  [saɪt]   v.引用；援引；引述；提及（原因） n.引文
sinister  [ˈsɪnɪstər] adj.邪恶的；险恶的 implication  [ˌɪmplɪˈkeɪʃ(ə)n] n.暗示
unobtrusively  /ˌʌn.əbˈtruː.sɪv.li/  不引人注目地；悄悄地 rapid  [ˈræpɪd] adj.瞬间的；；迅速的；快速的
acoustics  [əˈkustɪks] n.声学；音响效果   lens  [lenz]  n.透镜；镜片；网络镜头
sci-fi  [ˈsaɪ faɪ] adj.同“science fiction”网络科幻频道  reality  [riˈæləti] n.现实；事实
legitimate      美: [ləˈdʒɪtəmət]       adj.正当合理的；合情合理的；合法的；法律认可的  v.使合法；认为正当；认为正统；承认(庶子)为嫡出      网络正当的；正统的；正当性
doomsayer  [ˈdumseɪər]  n.预言灾难者   doomsayers
charge  [tʃɑrdʒ]  n.收费；主管；指控；掌管 v.收费；充电；冲锋；指责网络费用；电荷；控告
legitimate  [ləˈdʒɪtəmət] adj.正当合理的；合情合理的；合法的；法律认可的 v.使合法；认为正当；

容易读错的词 
array  [əˈreɪ] n.数组；阵列；大量；大堆 v.排列；布
large  [lɑrdʒ]  adj.大的；大规模的

The pen is mightier than the sword.   笔比sword 更加有力
Multitude 多数 

洗澡完 21：30 升级一下 freebsd  应该是22:20 开始 搞到现在 23:24 学了一段 和完了lesson all 

     On one side of the  debate are those who point  out that webacms offer more  real  advantages thant supposed disadvantages. They  cite numerous websites on which people  can  observe the world around  them for educational or aesthetic purposes. Today one  can watch  urban scenes like  city streets and squares  or even haunted houses! Nature lovers   can revel in the undetectable  webcasting of bats, sharks, and  penguins at various sites around the world. A huge collection of webcams can be found at www.earthcam.com . Another  great  collection  can be viewed at www.discovery.com. Most educators, parents, and politicians  would  agree  that  these   websites allow  for a  better  understanding of both the human  and  natural environments in the world we all live in. Certainly, the world say, webcams provide an invaluable service and  should  not be restricted.

debate  [diˈbeɪt]  n.辩论；争论；考虑    those  [ðəʊz]  adj.那些(的)pron.那些(人)
effect  [ɪˈfekt] n.影响；作用；
effort  [ˈefərt] n.努力；工作；成就；
disadvantage [ˌdɪsədˈvæntɪdʒ] n.不利损失 v.使不利  numerous[ˈnuːmərəs] adj.许多；数量庞大的；数不清的
cite  [saɪt]   v.引用；援引；引述.引文   sinister  [ˈsɪnɪstər] adj.邪恶的；险恶的
observe  [əbˈzɜrv] v.观察；看到；aesthetic [esˈθetɪk] n.美学
urban  [ˈɜrbən] adj.城市的  scene [sin] n.现场；景色
haunted [ˈhɔntəd] adj.（被认为）闹鬼的     revel [ˈrev(ə)l] 尽情    网络陶醉；沉迷；狂喜
undetectable [ˌʌndɪ'tektəbl] adj.察觉不出的；发现不了的 webcasting  [ˈwebˌkæstɪŋ] n.【计】网络播放
invaluable [ɪnˈvæljuəb(ə)l] a.极有用的 无价的  restrict [rɪˈstrɪkt] v.限制；约束；
provide [prəˈvaɪd] v.提供；供应；给予 

be beneficial to  [bi ˌbɛnəˈfɪʃəl tu]  v.有益于；利于。

  Other   are not  so sure. Every technology cuts both ways.  Even  fire can cook food as it can burn our flesh.  Railroads  gave  us faster and more convenient  transportation as they  simultaneously signaled  the death knell of many  species of  migratory animals as well  as served up noise and air pollution. Nuclear energy gives millions heat, light, and power just as it  creates unwanted radioactive  side effects. Seemingly  harmless technologies such  as telecommunications  also have  their dark  side.

flesh [fleʃ] n.肉体；果肉；皮肉
fresh [freʃ]  adj.新鲜的；

convenient [kənˈviniənt] adj.实用的；便利的 simultaneously [ˌsaɪməlˈteɪniəsli]adv.同时；联立；急切地
signal [ˈsɪɡnəl] n.信号；信号器；预兆； knell [nel]  v.敲丧钟报丧；
migratory [ˈmaɪɡrəˌtɔri] adj.迁移的； serve up  na.端出(饭菜等)；上(菜)；同“serve” 提供；提出
unwanted [ʌnˈwɑntəd] adj.不需要的；多余的；不受欢迎   radioactive [ˌreɪdioʊˈæktɪv] adj.放射性的；有辐射的
telecommunications [ˌtelɪkəˌmjunɪˈkeɪʃ(ə)nz]  n.电信；电讯
side effects   副作用 

   Opponents of webcams  note  that  the sleazy, commercial instinct of some people   is unleashed with the offering of for-pay viewing of certain starlets  or other  celebrities' home    lives, which most people  prefer to think   of as their "private"   life. Perhaps not much longer. In some controversial cases, webcams have been mounted in  public  installations such as washrooms so that voyeurs may watch the intimate goings-on of anonymous people. Even  more sinister is the capacity for  the new technology  to be used in both economic espionage  and "good old"  state-to-state  spying. Webcams mounted surreptitiously in   business  offices or factories can reveal on-screen "secrets" from those unaware that they are being  bugged. Wich microelectronics technology reducing the size of  telecommunications devices, this is no paranoid fantasy any longer.

opponent: [əˈpoʊnənt] n.对手 adj.对立的反对者   sleazy  [ˈslizi]  adj.（尤指涉及性行为）肮脏的
commercial 美: [kəˈmɜrʃ(ə)l] adj.贸易的；商业的；赢利的；以获利为目的的 n.（电台或电视播放的）广告

controversial [ˌkɑntrəˈvɜrʃ(ə)l] adj.有争议的  intimate [ˈɪntɪmət] n.知己；密友；至交 v.暗示；透露；（间接）表示
adj.亲密的；密切的；个人隐私的
instinct [ˈɪnstɪŋkt] n.本能；  unleash  [ʌnˈliʃ] v.〈比喻〉解放；放纵；发动
certain [ˈsɜrt(ə)n] adj.肯定；确
voyeur [vwaɪˈər] n.有窥淫癖的人 
installation    美: [ˌɪnstəˈleɪʃ(ə)n] n.安装；install  [ɪnˈstɔl]  v.安装；
anonymous [əˈnɑnɪməs] adj.匿名的   sinister  [ˈsɪnɪstər]adj.邪恶的；险恶的
capacity [kəˈpæsəti]n.容量；生产能力 espionage  [ˈespiəˌnɑʒ]n.间谍活动；
surreptitiously  [ˌsʌrəpˈtɪʃəsli]adv.偷偷地；  reveal  [rɪˈvil]    v.透露；揭示；显示；展示
bug  [bʌɡ]    n.缺陷；虫子  paranoid [ˈperəˌnɔɪd]    n.偏执狂；妄想症患者    adj.多疑的；恐惧的；
   
    The human mind is as devious as the many progressive  devices it produces. No matter what technology mankind  develops in the future, we can be sure that it will offer and  opportunity to exercise the dark side of our potential. On balance, we must move forward and allow these new technologies.  Only by practicing them -- for good or bad --can we realize our human potential. On  balance, too, despite   the horrific deadly or sinister potential in  technology,  the world offers a more productive, comfortable, and progressive  environment today that in our previous low-tech centuries. At the end of the day, it is not our technology that we must learn  to control so much as ourselves.

cunning [ˈkʌnɪŋ] n.狡猾；诡诈    
devious [ˈdiviəs] adj.不诚实的  狡诈的 progressive [prəˈɡresɪv] adj.进步的；
opportunity [ˌɑpərˈtunəti] n.机会；时机  potential [pəˈtenʃ(ə)l] n.潜力；电位
balance [ˈbæləns] n.平衡；均衡  on balance 总的来说
despite [dɪˈspaɪt] prep.尽管；即使   horrific [həˈrɪfɪk] adj.极坏的；令人震惊的
deadly [ˈdedli] adv.非常；极其adj.（可能）致命的 网络 致死的 sinister [ˈsɪnɪstər] adj.邪恶的
productive [prəˈdʌktɪv] adj.生产的； previous [ˈpriviəs] adv.在先 adj.先前的
exercise [ˈeksərˌsaɪz] n.运动；练习；行使；演习 v.锻炼；行使；训练；运用



    
**  Lesson 16 When  Is the Best Time ?
  Some  poeple  go so far as to say that  time does not really exist; It is  all in the mind, they claim.Others note that according to  astrophysicists, time  really does exist; It is  inseparable from space,coexisting in what  these scientists call the "time-space continuum" . No  matter which view you may hold, time is of  relative importance in  different  cultures. However, when  traveling ,doing  business, or studying  in a German or English-speaking country, it is a good idea to consider time to be of the utmost importance. 
claim  美 [kleɪm]  n.索赔；宣称；声明；断言
  astrophysicist      美: [ˌæstroʊˈfɪzɪsɪst]   n.天体物理学
coexist     美: [ˌkoʊɪɡˈzɪst]   v.共存；（尤指）和平共处  网络同时存在；并存；同时
relative      美: [ˈrelətɪv]   n.亲属；亲戚；同类事物
utmost     美: [ˈʌtˌmoʊst]   n.极限；最大限度；最大量；最大可能 adj.最大的；极度的
consider      美: [kənˈsɪdər]   v.认为；觉得；以为；顾及

  Many people have noted that  the  germans  and English  are both  methodical and well-organized.  Naturally, not everyone among  them is ,but these peoples do seem to  share a penchant for orderliness  and  punctuality.      Clocks and time have played a great  part  in defining the character  of the  Anglo-Saxons. The  geographic use of time  began during the British  Empire  with  the world  divided by latitude and longitude , with  zero  degrees longitude    running through the observatory at Greenwich , in London. According to  the British of that day, the world began its  timekeeping from London  and  it still does.  Time is of paramount importance  to these  Europeans and their overseas descendants. If you are visiting or  staying  in these  countries, here  are a  few pieces of advice to help you make the transition to a time-centered civilization.

  methodical 美: [məˈθɑdɪk(ə)l] adj.有条理的；有条不紊的；办事有条不紊的   网络有方法的；有系统的；井然的
  well-organized  美[wel ˈɔːrɡənaɪzd]  有序的; 很有条理的
  naturally 美 [ˈnætʃ(ə)rəli]  adv.自然地
penchant      美: [ˈpenʃənt]   n.爱好；嗜爱
orderliness  美 ['ɔrdəlɪnəs] n.整洁；整齐；有秩序；守纪律 网络条理；井然有序；秩序井然
punctuality n.严守时间；敏捷
character 美: [ˈkerəktər] n.特征；特性；性格；角色 v.刻；画；表现…的特性；使具有特性 网络字符；人物；品格
define  美 [dɪˈfaɪn] v.限定；(弄)明确；定界说
latitude  美 [ˈlætəˌtud]  n.纬度；纬度地区；选择（做
longitude    美: [ˈlɑndʒɪˌtud]   n.经度
observatory 美 [əbˈzɜrvəˌtɔri]  n.天文台；气象
paramount  美 [ˈperəˌmaʊnt] n.最高；有最高权力的人；元首；首长  adj.至为重要的；首要的；至高无上的；至尊的
descendant 美 [dɪˈsendənt]  n.后代；弟子；从某一来源派生的东西；派生物

   As  you  probably already know, being  punctual --to the minute --- is held  in  high esteem among them. Time is the most valuable commodity  one can have,  according to the  doctrine of  the time worshippers . We are not given very much  of it whilst on this planet, and we should do our best to utilize it efficiently  each and every day, the say . Wasting  others' time by forcing them  to wait is a sign of disorganized living, a sort of admission  to being low-class. It is also  seem  as an insult to  those kept waiting, as if to say, "Your time is not that  important."To them, this attitude borders on sin itself! In business, being late even only a few times may make the difference between  your  getting a promotion and being kept "in your place." For social dates, it is a sign of slovenliness at best, rejection of those waiting at worst. In school, never  burst open the door of the lecture hall to announce, "I'm sorry  I'm late,sir" as is the custom in many countries, The  double crime of being tardy and interrupting the proceedings which  began on time  occurs, with a likely prejudiced  and  unfavorable grade awaiting  the hapless student.

   punctual 准时
esteem      美: [ɪˈstim]       v.尊重；敬重；认为；把…看作  n.尊重；敬重；好评      网络尊敬；自尊；尊严
commodity 美 [kəˈmɑdəti]  n.商品；产品；货物；商品经济
doctrine  美 [ˈdɑktrɪn]  n.学说；教义；信条；主义  网络教条；原则；教旨
worshipper  美 ['wɜrʃɪpər]  n.崇拜上帝（或神）的人；做礼拜的人；敬神者；拜神者
utilize  美 [ˈjut(ə)lˌaɪz]  v.利用；运用；使用；应用
sign  美 [saɪn]  v.签名；签署；叹息；预示
disorganized  美 [dɪsˈɒrɡəˌnaɪzd] adj.无组织的；混乱的
insult  美 [ɪnˈsʌlt]  n.侮辱；辱骂；冒犯  v.侮辱；辱骂；冒犯
attitude  美 [ˈætɪˌtud] n.态度；看法；我行我素的做派；姿势 网络心态；姿态；工作态度
sin 美 [sɪn] n.罪；罪行；过失；过错  abbr.正弦
slovenliness  网络马虎；不修边幅
rejection  美 [rɪˈdʒekʃ(ə)n] n.拒绝；否决；抛弃；拒斥
lecture  美 [ˈlektʃər]  n.演讲；训斥  v.讲课；训斥
tardy 美 [ˈtɑrdi] adj.行动缓慢的；拖拉的；迟缓的；迟到的 网络迟延的；迟的
interrupt 美 [ˌɪntəˈrʌpt] v.打扰；中断；打搅；打断(别人的话等)  网络打断他人；插入他人谈话；插话
proceedings  美 [prəˈsidɪŋz]  n.程序；学报；事项；会刊 网络会议录；论文集；诉讼
occur  美 [əˈkɜr]  v.出现；存在；想起；(事
prejudiced 美 [ˈpredʒədɪst]  adj.有偏见的；带成见的；偏爱的；偏心的
unfavorable  美 [ʌnˈfeɪv(ə)rəb(ə)l]adj.令人不快的；逆的；不适宜的；不顺利的
网络不利的；不宜的；不理想的
# 这段完成得不错 Friday July  twenty-ninth  2022 
  Of course, being  late can sometimes not be avoided , as in unexpected traffic jams,home  emergencies, or having   been  given the wrong  information of date or place. When  these  all-too-human  mishaps do occur ,  it is important to explain the reason for being late. It is also a good idea, Of course ,to apologize for the useless waiting and to assure  the other or  others that it  will never happen again. In this age of cell phones, every effort shoudl be made to call ahead if tardiness of more than ten minutes is unavoidable, especially for business or professional  appointments or important  dates. The  last phrase anyone  wants to hear is a frosty "You could  have called."  That  is the prelude to a ruined evening.
mishap     美: [ˈmɪsˌhæp]   n.灾难  
occur     美: [əˈkɜr]  v.发生；出现；存在于；出现在 
avoid     美: [əˈvɔɪd]      v.避免；防止；【法】使无效；撤销
assure      美: [əˈʃʊr]  v.确保；使确信；向…保证；弄清
tardiness     美: ['tɑrdɪnəs]  n.拖拉；缓慢；迟缓
anyone     美: [ˈeniˌwʌn]   pron.（用于否定句、疑问句，也用于 if 或 whether 之后，或紧接 prevent、forbid、avoid 等动词，代替 someone）任何人
phrase      美: [freɪz]   n.短语；词组；习语；成语
v.措辞；分乐节（尤指
frosty      美: [ˈfrɔsti]       adj.严寒的；霜冻的；结霜的；冷淡的
prelude     美: [ˈpreljud]  n.前奏；前奏曲；序幕；先声
ruined 美: [ˈruɪnd] adj.毁坏的；严重受损的  v.“ruin”的过去分词和过去式

 Not   everything  begins  exactly on time, even in  Anglo-Saxon  culture. Many  casual  parties are "open" concerning time; the party begins when you get  there. The  same  is generally true  of backyard  barbecues and picnics. Dinner parties, on the other hand , are obviously planned around a meal time; one should make every effort  to arrive  (not before). A friendly "Drop by this evening" invites common sense to interpret: too earyly during the evening may  embarrass the host who is  eating dinner, while too late  may disturb  those who  prefer  going  to bed earyl. A call first to make sure is never out of line .

 disturb      美: [dɪˈstɜrb]  v.打扰；干扰；弄乱；妨碍

  Remember that  time is relative in importance to people  within a  culture just  as it is between  cultures.  Nothing  is more importance than  human relations. If you  commit the "crime" of  being late  with Anglo-Germanic friends, simply apologize. Few  people intentionally keep  others waiting, after all. Remember, too, that, "When in Rome,do as the Romans do."  In  English-and German-speaking lands, this means "Time waits for no man!"

  relative     美: [ˈrelətɪv]  n.亲属；亲戚；同类事物  adj.相比较而言的；比较的；相对的；相关联的
  commit      美: [kəˈmɪt]       v.承诺；自杀；做出（错事）；犯（罪）      网络提交；提交完成；干


  
**  Lesson 18  Hot Animals Around the  World: The Koala
   Why  are all those people  standing in line in the hot sun at the zoo? Maybe  the zoo just opened  a koala exhibit. With  the survival rate  of native  Australian koalas on the rise,  more  and more  zoos around the world are  adding  a  "koala house" or  "koala exhibit" to their roster of special animals. And   the people  keep coming,  whether merely to catch a glimpse of one or , if really lucky  at zoos  which permit it , to hold  and be photographed with one.

   rate  [reɪt] n.率；速度；比率；价格
exhibit  US [ɪɡˈzɪbɪt] v.展览；表现；展出.  roster US [ˈrɑstər] n.值勤名单；候选名单
merely  US [ˈmɪrli]  adv.仅仅；只不过. glimpse US [ɡlɪmps] v.瞥见；〔诗〕闪现
permit US [pərˈmɪt] v.允许；准许；使有可能 n.许可证
luck n  
   
   Why   are  koalas among the  most beloved fo all animals ? At  times   referred to as " koala bear," this Australian marsupial is not a bear at all. It is one of  few tailless mammals besides  the apes and man. Yet  apes are not often  considered cuddly; indeed, they  are often  feared for being either too large or too naughty. This  Australian  real-life teddy  bear, instead , is the best of all worlds: it is quiet , soft, neither too large nor too small (adults are usually 65 to  80 cm. long), and really  cuddly! With  its  soft fur, leathery nose, rounded  ears, and big eyes, most people  seem  to melt when near one.  Its  disposition is  perfect  for   children and adults alike;   it rarely makes a fuss, even   when  being held. (Try  that  with  a baby  tiger!) No  wonder the  lines  to see,  hold, or just  touch the  koalas are always among the longest at zoos.

   refer to  v.查阅；提到 Web把某人叫作；被提及
   marsupial US [mɑrˈsupiəl] adj.【动】有袋(目)的；袋(状)的    n.有袋类动物（如袋鼠和树袋熊）
   mammal US [ˈmæm(ə)l] n.哺乳纲动物
ape     US: [eɪp]   n.猿；类人猿. cuddly US: [ˈkʌdli]   adj.令人想拥抱的；柔软而
fur US: [fɜr]      n.舌苔；毛皮衣服；（动物浓厚的）软毛；（动物的）毛皮
    v.用毛皮护覆；使生水垢；除去(锅上的)水垢；使长舌苔      Web皮草；皮毛；毛发
    leathery  [ˈleðəri]  adj.坚韧粗糙的；似皮革的 Web皮革味；皮似的；皮般强韧
melt  [melt] v.融化；（使）软化 . adult  [ˈædʌlt]  n.成人；长成体  adj.成年的；成熟的
fuss     US: [fʌs]  n.大惊小怪；无谓的激动（或忧虑
disposition     US: [ˌdɪspəˈzɪʃ(ə)n]      n.倾向；性情；性格；布置

   One  reason zoos  today  are able  to keep  koalas  is the  rise in the koala population  in its native habitat, the eucalyptus forests of  southeastern  Australia. This  nation, famous for its  unique  fauna and flora, is now allowing applications for the professional export of its  protected species to overseas  zoological gardens. Once   hunted for its fur, this arboreal leaf-eater  is today  protected by stringent laws and is making a slow but steady comeback.  Indeed , everything about   the koala  seems slow. It sleeps more than  12 hours a day(often  much more), eats only choice leaves from  eucalyptus(which  can now be grown  in many zoos  to provide the more than  one kilogram of leaves that  each adult koala needs per day), and rarely  if at all  descends to the ground because it is such a  slow runner(from wild Australian dogs called dingoes ro from human hunters). As  kialas  are such  a great draw for visitors,  many zoos are trying to include  them  among their species.

eucalyptus US [ˌjukəˈlɪptəs]  .桉树.  fauna  [ˈfɔnə]      n.（某地区或某时期的）动物群
flora  [ˈflɔrə] n.植物区系；植物群； zoological  [ˌzəʊə'lɒdʒɪkl]  adj.动物学的

   Mother koalas   give  birth to babies only  every other year. These young ones,as  with other  marsupials,spend a period of  time inside the mother's  "pouch"  before venturing out into  the world. In the case of the koala, this pouch  is located below and in back of the mother; the  small koals can climb out directly  from the puch and onto  the mother's  back  before learning to  feed  and feed for  themselves. With  all other  marsupials, the pouch is located in the front , perhaps most famously with  the kangaroo, where  the "joey"  can  sometimes be seen  popping  its head out of it soft, warm pouch to survey  the world  about it safely. 


   pouch US [paʊtʃ] n.荷包；邮袋；小袋子；（有袋目动物腹部的）育儿袋


   Until the 1980s, zoologists feared  that the  koala might go the way of some other   rare marsupials. Just  as their eucalyptus  habitat  was  being destroyed to make room  for the ever-increasing suburban Australians, diseases peculiar to koalas began  to  take their toll.  Combined with weak or non-existent  laws against the hunting or poaching of  this national treasure, the koala seemed doomed to extinction.  Today , the koala has climbed back from the brink  of extinction and is  thriving again.  Its main  enemy today is forest fires. This  slow-moving mammal  cannot move quickly enough to escape the  deadly fires  which  perennially ravage the land. With  more  land being  set aside to  protect this  and  other  Australian species, however, the future  of much of this special land's  animal wealth seems secure.

   All animals deserve man's  protection, but some  animals seem to attract the attention they  need. The  koala  , one of  the symbols of the great Down Under, is one of  these . Holding a  koala is fun, educational, and inspiring. If  Australians could cooperate to save  this special species, mankind  should be able  to prevent the extinction   of all other  animals, too.
   

   
**  Lesson  19  Asian Americans
  In the  last census  conducted  by  the U.S. government in 1990, one fact caught many people  by surprise; the  percentage  of Asian  Americans  had grown faster than  any other  segment  of the  population. European  Americans had, as expected, continued their  slow decline in percentage   of  the total U.S. population, though they were still dominant at about 76%.  Black Americans  had stabilized  at about 12% of  the population. Hispanics had  continued their fast growth and were, at 9%, aimed at  toppling  Black   Americans as the country's  largest  minority group. The growth in Asian  Americans, however,  surged from  only 2% of the  total U.S. population in the  1980 census  to  3% in 1990. By  the year 2000  at least 4% of Americans will be of  Asian ancestry. This  relatively huge  increase has caught  many demographers  by  surprise. Clearly  a  new force  is developing in U.S. demography, but few  people  seem  to appreciate its   implications .  The  Asian Americans are here  and are here  to stay, but exactly who are they, and what  does their rapid  increase mean for  the country as a whole ?

Asian  [ˈeɪʃ(ə)n] adj.亚洲的；亚洲人的
census [ˈsensəs] n.人口普查  conduct [ˈkɑnˌdʌkt] v.传导；指挥；带领；表现 n.指挥；带领；指导
percentage  [pərˈsentɪdʒ] n.百分比；百分率  segment  [ˈseɡmənt] n.段；部分；片；弓形
population  [ˌpɑpjəˈleɪʃ(ə)n] n.人口； expected  [ɪkˈspektəd]  adj.预料的
decline  [dɪˈklaɪn] v.下降；衰退；  dominant  [ˈdɑmɪnənt]  n.优势种；adj.首要的 占优势的；
stabilize  [ˈsteɪb(ə)lˌaɪz] v.稳定；使稳定    Hispanic  [hɪˈspænɪk]  adj.西班牙的；西班牙和葡萄牙的；拉丁美洲的    网络西班牙裔；拉丁美洲移民；西班牙人
aim  [eɪm]  v.针对；旨在；把…指向；把…掷向 n.目标；瞄准；目的；宗旨
topple [ˈtɑp(ə)l] v.倒下；打倒；推翻；颠覆   minority  [maɪˈnɔrəti] n.少数民族；少数人
surge  [sɜrdʒ] n.大浪 高涨   ancestry [ˈænˌsestri] n.祖先；网络世系；血统；家世
relatively [ˈrelətɪvli] adv.相当程度上；相当  demographer  [dɪ'mɒɡrəfə(r)]  n.人口统计学家
force  [fɔrs] n.力；力量；武力；部队v.强迫；用
demography [dɪˈmɑɡrəfi] n.人口学；人口统计    网络人口结构；宏观人口统计；人口组成
appreciate [əˈpriʃiˌeɪt] v.欣赏；感谢；感激；升值 网络赏识；鉴赏；增值
implication  [ˌɪmplɪˈkeɪʃ(ə)n]  n.含意；推断；牵连 含义；影响；
rapid [ˈræpɪd] n.急流；滩；湍流 adj.瞬间的；短时间内发生的；迅速的；快速的

   As  a multi-ethnic  nation, it should not be surprising that  Asian  Americans are becoming  an increasingly large  and important  sector  of the "rainbow nation"  some   
 Americans  prefer to  think  of their  country as.  Indeed  the only surprise   about  this segment growing so fast   is why  it has not  occurred   sooner. After all,Asia is home  to 60% of all the people  in the world. However , Asia  is also a vast land, encompassing East,  Southeast , South ,  and West Asia, each region   
 significantly  different  from  its  neighbors. Further, there is  no sense of unity within Asia, as there is , say ,among European or Latin American countries . Indeed ,   the term "Asian Americans" is    more  a fiction  of the European mind, since people  from this area unfailingly  refer to   themselves as Chinese, Japanese, Filipino , etc . rather  than   as Asian-Americans.

multiethnic [ˈmʌltaɪˌeθnɪk] adj.多民族 increasingly  [ɪnˈkrisɪŋli] adv.越来越多地；不断增加地 日益；
nainbow  [ˈreɪnˌboʊ] n.彩虹 彩虹色；七色彩虹  vast [væst] adj.辽阔的；巨大的
encompass  [ɪnˈkʌmpəs] v.包含；围绕；完成 region  [ˈridʒən] n.区域；行政区
significantly  [sɪɡˈnɪfɪkəntli] adv.极大地；显著地； further  [ˈfɜrðər] adv.进一步；此外；更远；而且
unity  [ˈjunəti] n.统一；联合  sense  [sens] n.意识；意义
fiction  [ˈfɪkʃ(ə)n] n.小说；虚构的事； unfailingly /ʌnˈfeɪ.lɪŋ.li/网络无穷尽地，不倦地；对应的应该是

  For more than   100 years, three primary groups of Asians  emigrated to the  United States: Japanese,Chinese,and Filipino. However, since the end of the  Vietnam War, other groups from  Asia  have  become increasingly  prominent, especially those  from Vietnam, Korea,  and India. In addition,  Iranians  and Israelis from Southwestern Asia have also  entered  the U.S. in large  numbers.

immigrate  [ˈɪmɪˌɡreɪt]  v.（从外地）移居；移民  移居入境；移来；移居入本国 
emigrate [ˈemɪˌɡreɪt] v.移居(外国)；迁出； prominent  [ˈprɑmɪnənt] adj.重要的；著名的；杰出的
especially [ɪˈspeʃ(ə)li] adv.尤其；特别  addition  [əˈdɪʃ(ə)n] n.添加；增加；加法；增加物 网络附加物

  The patterns of Asian immigration  have changed  greatly  over  the past 30 years. In 1970, 96% of Asian Americans were  Chinese , Japanese, or Filipino; as of  1997, this percentage  had dropped to 55%! In that year, 24% of Asian Americans  claimed Chinese ancestry, 21% Filipino, and 10% Japanese.  The "newcomers" among Asian Americans  include  the Indians at 13 %, Vietnamese at 11%, and Koreans also at 11%.

pattern  [ˈpætərn] n.模式 形态方式；v.给…加花样 claim  [kleɪm] n.声称；认领
ancestry  [ˈænˌsestri] n.祖先 血统；家世   as of  到了 
  
  What  real numbers are we talking about? There were  estimated to be nearly 9,600,000 Asian Americans  in the U.S. in  1997. With such  a high  growth rate, there  will    be  more than  10 million of them this year and perhaps 32 million in 2050(about 8%  of  the total U.S. population at that time). Where  do   Asian Americans  live ?  Currently, an astounding 40% of this regional group  lives in California. Other  states with  relatively  large Asian American  populations  include  New York,Hawaii,Texas,New Jersey Washington (the state), and lllinois (which contains Chicago). Overall, the West is home  to 54% of all Asian Americans, the Northeast 19%, the South 16%, and the Midwest 11%.

estimate [ˈestɪmət] v.估计；估算 currently [ˈkʌrənt(ə)li] adv.当前；目前
astounding [əˈstaʊndɪŋ] adj.使大吃一惊的 regional [ˈridʒən(ə)l] adj.地区的；区域的
relatively [ˈrelətɪvli]  adv.相当程度上；相当地； contain  [kənˈteɪn] v.包含；能
Chicago [ʃɪ'kɑ:ɡoʊ] n.芝加哥 Overall 总体 
  
  What about future  trends ? As Asian nations continue  to prosper, it is likely  that  will contribute  more to U.S. immigration, especially from Southeast Asia and India.  All of  these groups continue to have above-average birth rates. On the other hand, Chinese and Japanese Americans have very  low birth rates; consequently, the percentage of these  ethnic  groups  among  the total will continue tho fall. All in all, American can look forward  to an  increasingly  large  number of Asians  enriching their new home  with their diligence, investment, and diverse cultural  contributions. 

trend  [trend] n.趋势；方向  nation  [ˈneɪʃ(ə)n] n.国家；民族；种族
prosper [ˈprɑspər] v.繁荣；成功；发达； contribute [ˈkɑntrɪˌbjut] v.捐助；捐献；是…的原因之一；增加
immigration  [ˌɪmɪˈɡreɪʃ(ə)n] n.移居；外来移民； especially  [ɪˈspeʃ(ə)li] adv.尤其；特别
consequently [ˈkɑnsəkwəntli] adv.因此；因而； fall  [fɔl] v. & n. 下降；跌倒；落下 adj.〈美〉秋天
enrich [ɪnˈrɪtʃ] v.丰富；充 diligence [ˈdɪlɪdʒəns] n.勤奋；用功
investment [ɪnˈvestmənt] n.投资；投资额；投资物   diverse  [daɪˈvɜrs] adj.不同的；相异的；多种多样的；



**  Lesson 20 Scourage  of the Plains:  Tornadoes 

scourge [skɜrdʒ] v.鞭打；鞭笞；折磨 n.祸害；灾害 plain [pleɪn] n.平原；
tornado [tɔrˈneɪdoʊ] 龙卷风

  Ellen Mae  stepped  out of  her  two-story home in central  Illinois  "Fine morning " she  said  to herself after checking the weather , and   then  went back inside. The radio  had  mentioned  a severe storm  advisory, but the sky was  clear, and it was  rather calm.  Still, she decided to be safe  and kept her radio on. 

  mentioned ['menʃ(ə)n]     v.“mention”的过去式和过去分词 网络提及；提及的；说起
advisory [ədˈvaɪz(ə)ri] adj.咨询的n.警报
calm [kɑm] adj.泰然自若的；(海洋,天气等)安静的；静寂的
n.平静；恬静；
severe [sɪˈvɪr]     adj.极为恶劣的；十分严重的；严厉的；苛刻的    网络剧烈的；严格的；重度

  About  noon  she felt a strange kind  of pressure. Looking out  her  window, she noticed the sky had become overcast.  Low, rounded, oddly colored clouds were  forming. It was  still  and  oppressvie. "Maybe I'd better    listen to the weather report again,"  she murmured to herself.

strange [streɪndʒ] adj.奇怪的；奇特的；异常的  pressure [ˈpreʃər] n.压力；压强
overcast [ˈoʊvərˌkæst] n.覆盖；阴暗的天空   round [ˈraʊndəd] v.绕过；拐过；使成圆形；把…四舍五入
prep.绕过；在…周围；始终 adv.环绕；附近；
oddly [ˈɑdli] adv.古怪地；怪异地；   form [fɔrm] v.形成；产生；构成；【语】构(词)n.形态；形状；
oppressive [əˈpresɪv] adj.压迫的；压制的 murmur [ˈmɜrmər] n.低语；

again [əˈɡen] adv.再一次  forecast [ˈfɔrˌkæst] n.预测；预报
siren [ˈsaɪrən] n.警报器；警笛；汽笛   seek [sik] v.寻求；寻找；谋求
shelter [ˈʃeltər] n.避难所；庇护所(我真的记得这个)  twister [ˈtwɪstər] n.旋风；龙卷风
doubt [daʊt] v.怀疑；不相信；     comfort [ˈkʌmfərt] n.安慰；愉快  


   Again the radio   forecast severe  weather, warning citizens  to listen for   the siren and seek shelter should a  twister, scourge  of the plains, come  down from the heavens like a  "Devil's tail" "I doubt  it'll  happen over Crossville," she comforted herself. "It always happens in other towns."
   

   By  two o'clock it started to  rain, and the wind picked  up,too. The  apple tree in front  of Ellen   Mae's house started to  pitch  back and forth violently. Her  dogs started  to bark  and howl,  and that  was when   she heard  that   awful sound.

pick [pɪk]    v.选择；  pick up v.拾起；重新开始 变强 速度加快 买东西  
pitch [pɪtʃ] v.投；；颠簸    forth [fɔrθ]    adv.向前；离去
violently [ˈvaɪələntli]    adv.激烈地；猛烈地  bark [bɑrk]    v.（狗）吠叫；
howl [haʊl]    v.怒号；呼啸；怒吼；长嚎  
   
locomotive [ˌloʊkəˈmoʊtɪv]n.机车；火车头  swirl  [swɜrl]n.漩涡；纷乱
mass [mæs]n.质量v.  聚集；集结  suck [sʌk]v.吮吸 sucking up  吸进  
hurl [hɜrl]用力投掷   object [ɑbˈdʒekt]n.物体；目的
horrific  [həˈrɪfɪk]adj.极坏的；令人震惊的   straight [streɪt]adj.直的  甩
cellar [ˈselər]    n.地窖；地下室  prepare [prɪˈper]    v.调制；使做好准备；把…预备好
corner  [ˈkɔrnər]    n.角；拐角；  
basement [ˈbeɪsmənt]    n.地下室  bolt [boʊlt]n.螺栓 用插销闩


   At first  she  thought it was  a locomotive, but she  quickly  remembered that  there  was no  railroad within  20 miles of her home.  She  looked  into the sky and then  noticed it, a dark,  swirling mass of black cloud sucking up everything  it  touched  and hurling objects  at horrific speeds straight  up  or straight  to the side.  Ellen  Mae  ran as fast as she could down into her  storm cellar, a special room  which   had  been prepared by  her father when  he was still  alive.  This  room  was  located in the south western corner  of the basement and  had  a door  with a  strong bolt. Ellen Mae  ran in , locked  the door behind her, and waited.

a peal  of thunder 


shriek [ʃrik] v.惊喊；引人注意  swoosh [swʊʃ] v.(使)哗哗地流；(使)嗖嗖地动[发射] n.嗖嗖声
hell [hel] n.地狱；见鬼  funnel  [ˈfʌn(ə)l] n.漏斗 漏斗云；
directly [daɪˈrektli] adv.正；立即 扫过  apart [əˈpɑrt] adv.分开；分离；相距；不在一起
enormous [ɪˈnɔrməs] adj.巨大的；大量的
vacuum [ˈvækjum] n.真空；真空状态；空虚；空白  cleaner  [ˈklinər] n.吸尘器；清洁工；清洁剂；去污剂
twister [ˈtwɪstər] n.旋风；龙卷风  blew [blu:] v.blow(吹)的过去式    网络吹气；吹的过去式；吹拂
scatter [ˈskætər] v.撒；四散；驱散；撒播  generation [ˌdʒenəˈreɪʃ(ə)n] n.世代；一代[一世]；产生；同时代的人
rural [ˈrʊrəl] adj.乡村的；农村的； eerie [ˈɪri] adj.怪异的；神秘的；恐怖的
silence [ˈsaɪləns] n.沉默；寂静；  cacophony [kəˈkɑfəni] n.刺耳的嘈杂声
venture [ˈventʃər] v.敢于去（危险或令人不快的地方）；小心地说   venture out 网络冒险出去
unbolted [ʌn'boʊltɪd]     adj.未上栓的；把门闩去掉的   peer [pɪr] v.朦胧出现；瞪着看；
perish [ˈperɪʃ] v.死亡；毁灭；  

   She  didn't   have long  to wait. With  shrieking and   swooshing   sounds right out  of hell, the funnel cloud  passed  directly over her house. An  enormous vacuum cleaner, the twister  blew   the house  apart, scattering five generations of Ellen Mae's family belongings over half  the rural county  she lived in. Within  minutes, the winds had stopped, and an eerie silence replaced  the cacophony of  moments earlier.  Feeling it was now   safe  to venture out , Ellen Mae unbolted the door, peered out, and started to cry. She could look straight up into the sky. Even thought  she  had lost her house and everyting in it, she felt lucky, She knew taht every year,  hunreds of poeple   could perish in  tornadoes .

    Just what are  these "devil storms"? They  go by many names  across the Great Plains of the United States and  Canada,not to mention many other  countries arond the world, but tornadoes are perennial plagues in central North  America. The conditions  there - flat land and proximity to cold  air masses(from the Rocky Mountains to the west) and  warm  and humid air masses(from  the Gulf of Mexico to the  south) provide the optimum   breeding ground for tornadoes. According to the U.S. National Weather Service, tornadoes form  from  thunderclouds  and can reach swirling  speeds in excess of 600  kilometers per hour.    They last from minutes to an hour or more and  can blast their way across as much as 150 kilometers  of terrain at about 50 kilometers per hour. They vary in width from  a few meters to 1,500 meters(average 200 meters). And  they  strike fear  into the hearts of everyone.

devil [ˈdev(ə)l] n.魔鬼；恶魔  perennial [pəˈreniəl] adj.长久的；持续的
proximity [prɑkˈsɪməti] n.邻近 网络接近  gulf  [ɡʌlf] n.海湾；
plague  [pleɪɡ]    n.瘟疫；鼠疫；祸患
mass [mæs] n.群众；大量  v.使成一团  condition [kənˈdɪʃ(ə)n] n.条件；情况；疾病 v.决定；
flat [flæt] n.公寓；单元房；平坦的  warm [wɔrm] adj.温暖的；暖和的
humid [ˈhjumɪd] adj.温暖潮湿的；湿热的   provide [prəˈvaɪd] v.提供；供应
optimum [ˈɑptɪməm] adj.最佳的；最适宜的  breed  [brid] 养育；产生
thundercloud [ˈθʌndərˌklaʊd]n.雷雨云  swirl [swɜrl]    n.漩涡；纷
excess [ˈekˌses]超过；过分；过多的量超越  blast [blæst]nint.（恼怒时说）该死    网络一阵；鼓风；疾风
terrain [təˈreɪn]    n.地形；地带；地势  达到 地域；地面；领域
vary[ˈveri]    v.不同；改变   strike [straɪk]    v.罢工；击；攻击；打
fear  [fɪr]v.害怕；担心；惧怕；担忧  

   
   The  safest place to be when a tornado is in one's area is a  basement, preferrably the sourthwest corner (where the tornado  normally comes from). If driving, track  due  north or south, as tornadoes usually move from west to east. Weather prediction  and tracking these days is far superior to earlier years, but  tornadoes can appear  without any warning at all, as a  large  one did  right in the heart of Salt Lake City  in 1999,leaving a trail  of shocked , wounded, and dead as well as pulverized property.

preferably [ˈpref(ə)rəbli]adv.最好；宁可  track [træk]    v.跟踪；追踪；（尤指用特殊电子设备）跟踪；跟踪（进展情况）     n.轨道；车辙；小
due  [du]adj.由于；因为； adv.正向；正对着  prediction [prɪˈdɪkʃ(ə)n]    n.预测；预言；预告
superior  [sʊˈpɪriər]n.上级；上司 adj.（在品质上）更好的；占优势的；更胜一筹的
trail [treɪl]v.跟踪；追踪；（被）拖；磨蹭    n.小径；路径；
shocked  [ʃɑkt]v.“shock”的过去式和过去分词    网络震惊的；震撼的；感到震惊的
wounded [ˈwundəd]    n.伤员；伤号；伤兵 pulverize 毁坏
property [ˈprɑpərti]    n.属性；财产；财产权； 

   Though relatively few people  have ever seen a  tornado, those who have wish  they hadn't. The "Finger of God"  is nature's  atmospheric fury at its worst.
   
atmospheric [ˌætməˈsferɪk]adj.大气的；大气层的  fury  [ˈfjʊri]    n.狂怒；狂暴

** Lesson  21   What's So  Big  about  Mody Dick
  其实最后一次听的 很多还是不太明白  September 02 2022

moby / 'mobɪ /  dick / dɪk /

  A pretty,young lady goes swimming alone off the  coast of New English in twilight. She in an agile swimmer, full of grace  and speed. Without warning, though, she disappears from sight, only to  reappear a  moment later, screaming in pain. A few shocking moments later, she is again dragged under  the water, this time only to reappear the next moring in pieces on the shore.

twilight [ˈtwaɪˌlaɪt]  n.黄昏；微光     agile [ˈæˌdʒəl]adj.敏捷的；灵活
grace [ɡreɪs]    n.恩典；优雅  scream [skrim]    n.尖叫；尖锐
pain  [peɪn]n.痛苦；苦恼  shocking [ˈʃɑkɪŋ] 令人震惊的
dragged / dræɡd /v.制动；拖动；  shore [ʃɔr]n.滨；“shear”的过去式    网络岸；海滨

 Sound familiar? By now  nearly everyone  has seen or heard the story of a killer Great White Shark in Jaws, a hit novel  turned into a  blockbuster movie. Few people realize ,however, that  the story broadly follows the events depicted in  what  many  people  consider one of the best of American novels. Published  in 1851, Moby Disk has been making waves ever since.

jaw [dʒɔ] 大白鲨         blockbuster [ˈblɑkˌbʌstər]非常成功的书（或电影）
broadly [ˈbrɔdli]adv.大体上；基本  depict  [dɪˈpɪkt]v.画；描写；叙述
waves ['weɪvz]   波浪

  The author, Herman Melville, was born in New York on  Auguest 1,1819.  As  a youth in a large family he suffered many  insecurities due to the family's  constantly  changing fortunes. As a young man he worked as a farmer and seaman, the latter providing most of the material for several of  his  later novels  and essays. In his 20s Melville found fame  with two novels based on   imaginary happenings in the South Pacific. Moby Dick, ironically, was not well received Afterwards, Melville produced another masterpiece, Billy Budd. He continued writing until his death in 1891 .

suffer [ˈsʌfər]v.遭受；受苦  insecurity [ˌɪnsɪˈkyʊərɪti]    n.不牢靠；不安定
constantly [ˈkɒnstəntli]adv.不断地；时常地   fortune [ˈfɔrtʃ(ə)n]    n.命运；运气；财产；幸运
providing [prəˈvaɪdɪŋ]conj.同“provided”    v.“provide”的现在分词    网络提供；假如；如果
material [məˈtɪriəl]n.材料；原料；素材；布料  several [ˈsev(ə)rəl]adv.一些；几个；数个
essay [ˈeˌseɪ]    n.小品文 文章   fame [feɪm]    n.名声；声誉
imaginary  [ɪˈmædʒɪˌneri]adj.想象中的；幻想的；虚构的  ironically [aɪˈrɑnɪkli]adv.讽刺地；
afterwards [ˈæftərwərdz]adv.后来；以后  masterpiece [ˈmæstərˌpis]    n.杰作；名著；

despite [dɪˈspaɪt] prep.尽管；即使；尽管 initial [ɪˈnɪʃ(ə)l] adj.最初的；开始的
lukewarm [ˈlukˌwɔrm] 不热心的；冷淡的  reception [rɪˈsepʃən] n.接待；招待会；欢迎；
keen [kin] 敏锐的；   condition [kənˈdɪʃ(ə)n] n.条件；状态；
tenor [ˈtenər]  进程,一般趋势 disadvantaged [ˌdɪsədˈvæntɪdʒd] adj.弱势的；社会地位低下的
mistreat [mɪsˈtrit] v.虐待   immigrant [ˈɪmɪɡrənt] n.侨民；从异地移入的动物[植物]adj.侨民的
sailor [ˈseɪlər] n.水手；海员  laborer [ˈleɪbərər] n.劳动者；工人
untrammeled [ʌnˈtræmld] na.“untrammelled”的变体 奔放；自由自在的  无限制的
capitalism [ˈkæpɪt(ə)lˌɪzəm] n.资本主义
crush [krʌʃ] v.压碎；压坏；n.迷恋  crushing [ˈkrʌʃɪŋ] adj.毁坏性的
underneath [ˌʌndərˈniθ] adv.在下面[底下]；在下部[下层]   exuberance [ɪɡˈzubərəns] n.丰富；充沛
stress [stres] n.压力；强调
individual [ˌɪndɪˈvɪdʒuəl] n.个人；与众不同的人   fate [feɪt] n.命运；天意；
pessimistically [ˌpesɪ'mɪstɪklɪ]    adv.悲观地   realistically [ˌriəˈlɪstɪkli] adv.实际地；切合实际地
harbinger [ˈhɑrbɪndʒər] n.先驱；预言者   literature [ˈlɪt(ə)rəˌtʃʊr] n.文学；文学作品

  Why has Moby  Dick since  become such  a  classic despite its  initial  lukewarm reception? Melville had a  keen eye  for not only the human  condition  but for  the tenor of his times: the United States was  in his  day a country of  disadvantaged and  mistreated immigrants (many of whom became sailors and laborers), with  untrammeled capitalism crushing both nature  and  man underneath its new country exuberance. His stress on the  individual and  fate -- often  pessimistically, or  at least  realistically - were harbingers of the future  of literature.

  Why  does the story of Moby Dick continue to enthrall generation after  generatio? The story line is  simple enough: a mad sea captain vows revenge against a white whale which, on a  previous expedition, bit off one of his legs.   In his  vain attempt at "justice" against nature, the captain meets the ultimate tragedy. This  was no documentary, however; the characters and setting become vehicles for far larger and more  universal themes of the setbacks and successes of the human  spirit as well as its darker urges. So  accurately does Melville  depict the whaling scenes and sea voyages that the reader is taken  on an  exhilarating  ride.Coupled with the absorbing,mad Captain Ahab, the book is "a good read" even by 20th  century standards.

enthrall [ɪnˈθrɔl]v.迷惑；使...入迷 vow [vaʊ]n.誓言；誓愿
revenge [rɪˈvendʒ]n.报复；报仇  expedition [ˌekspəˈdɪʃ(ə)n]n.探险；考察 远征
vain [veɪn]adj.徒劳的；枉然的；无结果的；自负的 attempt [əˈtempt]n.尝试；试图
justice [ˈdʒʌstɪs]n.公正；公平   ultimate [ˈʌltɪmət]adj.最后的；最终
tragedy [ˈtrædʒədi]n.悲剧；  documentary [ˌdɑkjəˈment(ə)ri]adj.纪实的；有文件记录的
vehicle [ˈviɪk(ə)l]n.车辆 媒介 setback [ˈsetˌbæk]n.挫折；倒退
urge [ɜrdʒ]    v.鼓励； accurately ['ækjərətlɪ]adv.精确；正确
depict [dɪˈpɪkt]v.描述；描   whale [ˈhweɪlɪŋ]    n.鲸鱼；捕鲸
scene [sin]n.现场；景色
voyage [ˈvɔɪɪdʒ]    n.航行； exhilarating [ɪɡˈzɪləˌreɪtɪŋ]adj.使人兴奋的；令人激动的
ride [raɪd]v.骑；乘坐；骑马；搭乘n.搭便车；（乘车或骑车的）短途旅程  之旅
couple [ˈkʌp(ə)l]v.结合；连接；使结婚；(使)交配n.配偶；  absorb [əbˈzɔrbɪŋ]v.吸收；吸附；吸引；
standard [ˈstændərd]n.标准

  17:20 
  Earlier last century, the Noble Prize winner Ernest  Hemingway penned The Old Man  and the Sea, another story of a man's struggle  with nature on the open ocean. This  theme strikes a chord in Americans,   whose culture  developed  along the Atlantic coast of North  America  and whose seaward  passage  from the Old World took them to the colonies of the 18th century or the young country of the 19th century by the millions. This fascination withe the maritime still holds today: over half the population of the United States lives in counties  touching the Atlantic, Pacific, or Gulf coasts. Perhaps some future wirter will once again use the metaphor of sailors and the sea  to create yet another Great American Novel. 
  
struggle [ˈstrʌɡ(ə)l]n.斗争；奋斗  strike [straɪk]v.罢工；击；攻击  共鸣
chord [kɔrd]n.弦；心弦   Atlantic美:  英: [æt'læntɪk]adj.大西洋的
seaward [ˈsiwərd] adj.向海的；朝海的  passage ['pæsɪdʒ] n.通道；通过；走廊
colony [ˈkɑləni] n.殖民地  million [ˈmɪljən] num.百万；百万
fascination [ˌfæsɪˈneɪʃ(ə)n] n.魅力；着迷；    maritime [ˈmerəˌtaɪm] adj.海的；海事的；海运的；
hold [hoʊld] n.抓；握；拿；支撑 v.拿着；抓住；抱住；托住 保持 存在 持有
metaphor [ˈmetəˌfɔr] n.隐喻；暗喻 网络比喻；譬喻；比
  
  
  



**  Lesson  22  Boston: Hearth of American Culture

 hearth [hɑrθ] n.壁炉炉床；壁炉前的地面；家和家庭生活 炉边；
 
  When people  think  of "American culture and values,"  they  are unconsciously  referring to a set of principles, a world view, and a lifestyle  which can  best be found in Boston,capital of the state of Massachusetts  and the major  city in all  of  New England, those six  relatively samll states tucked away in the northeastern  corner of the United States. Although  Boston is perhaps the seventh  or eighth  largest city in the U.S.,no  other  city in America  can compare  with the influence which Boston has  had  on the development of government, education, medicine, and the arts.

unconsciously [ʌn'kɒnʃəsli] adv.无意地；不知不觉地  refer to v.查阅；提到 指 
principle [ˈprɪnsəp(ə)l] n.原则；Massachusetts [ˌmæsə'tʃu:sits] n.马萨诸塞；
tuck [tʌk] 使隐藏 v.收藏； influence [ˈɪnfluəns] n.影响；作用；影响力  

  This  influence  is due  in no small part  to Boston's  central role  in the building of  a new nation.  Many people  think  that the United States was  established in 1776; however, that  was the year  of  the Declaration of Independence, a  revolutionary   document claiming self-rule from its mother  country , England.  Actual  independence--the formation of a  government with an acting president(George Washington) -- did not begin until 1789. Boston was nearly   middle-aged then, as it  had had its beginnings a  century  and  a half earlier,in 1630. It maintained its  position  as the colonies' pre-eminent  center for politics, education , and  commerce until  the  mid-18th century, when  both New York and Philadelphia(the young nation's first and second capitals,respectively) overtook Boston in size .

  Boston  was  settled by religious immigrants from  the Church of English. It was  with these  early settlers that the first  outlines of an American  culture  began: a  strict  adherence to religious dicta, diligence in work, educational aspirations,  and a conservative  lifestyle. Because Boston  is closer to Europe  than any  other  city  in the U.S., it  was the point  of entry to the colonies  until  the 19th century, when  New york became the  new magenet  for the "poor, tired, and huddled  masses"  who  were  to become  the backbone of the new  American  economy, Boston remained, however , and important commercial center until  the 20th century .

settled [ˈset(ə)ld] adj.开垦的 religious [rəˈlɪdʒəs] adj.宗教信仰的；宗教的；
immigrant [ˈɪmɪɡrənt] n.侨民adj.移民   outline [ˈaʊtˌlaɪn] n.要点；轮廓；

strict [strɪkt] adj.严格的 adherence [ədˈhɪrəns] n.坚持；遵守
dictum [ˈdɪktəm] n.名言；断言；  diligence [ˈdɪlɪdʒəns] n.勤奋；勤勉；用功努力
aspiration [ˌæspɪˈreɪʃ(ə)n] n.愿望 抱负；热望；  conservative [kənˈsɜrvətiv] n.守旧派
magnet [ˈmæɡnət] n.磁体；磁铁 吸引力 huddle [ˈhʌd(ə)l] 缩成一团 拥挤；蜷缩；挤作一团
mass [mæs] n.群众；民众；大量  backbone [ˈbækˌboʊn] n.骨干；支柱；
commercial [kəˈmɜrʃ(ə)l] adj.贸易的；商业的  

  #这个其实上一段落的
central [ˈsentrəl] adj.最重要的；首要的；主要的；  role [roʊl] n.作用；(演员扮演的)角色
established [ɪˈstæblɪʃt] adj.已确立的；已获确认的；确定的  revolutionary [ˌrevəˈluʃ(ə)nˌeri] adj.革命的；革命性的
formation [fɔrˈmeɪʃ(ə)n] n.形成；编队  eminent [ˈemɪnənt] adj.显赫的；非凡的；杰出的
commerce [ˈkɑˌmɜrs] n.商业；（尤指国际间的）贸易；商务
respectively [rɪˈspektɪvli] adv.分别；各自；顺序为；依次为  


  Today Boston  caters  to finance and  banking, education, and medicine, with some of the top international  mutual fund and insurance companies, world-renowned educational   institutes, and state-of-the-art  medical centers   and schools.  The  city has  also  managed to preserve  much of its earlier identity  as the  home of the American Revolution; thus  tourism is  an important sector in the economy of Boston as  well. Like  San Francisco or New  Orleans, Boston has a  reputation  for being a pleasant city  to admire while walking around it.


  What  can one do in Boston? Important   historic sites, well-preserved examples  of architecture from  the 17~20th centuries, and spacious parks  invite the  tourist or resident to "smell the roses"  while in Boston. Its unhurried but sophisticated citizens boast  not only  high incomes but also high  levels of education. Music flourished here: the Boston Symphony Orchestra, the New  England  Conservatory of Music  and the Boston Pops  Orchestra offer  first-class musical entertainment in both public and private venues. The  Museum of Fine  Arts is a major world gallery. Science Park, situated  midway between Boston and its major satellite city, Cambridge , offers the Museum  of  Science. Had  enough  of "high-brow  culture"? Boston  affords it s citizens and visitors many first-class  restaurants and shopping  dockside in Faneuil  Hall. HiSTORIC walking  tours are a  must for the tourist, especially   Boston Commons, a city  park, and Beacon Hill, with  its  roads  still paved with the   original stones from the 17th century.  Admirers  of university  campuses  steeped in  tradition  should  see Harvard, the nation's  oldest  university(1636), as  well as  the Massachusetts Institute  of Technology, Emerson College, Boston  College, and Boston  University, all in   the metropolitan area.

cater [ˈkeɪtər]v.承办餐宴 迎合；  finance [fɪˈnæns]n.金融；财务
mutual[ˈmjutʃuəl]adj.相互的；彼此的  fund [fʌnd]n.基金；
insurance [ɪnˈʃʊrəns]n.保险；保险业  renowned [rɪˈnaʊnd]adj.有名的；闻名的
institute [ˈɪnstɪˌtut]n.学院；学会  preserve [prɪˈzɜrv]v.保留；保护
identity [aɪˈdentəti]n.身份；同一性；一致；特征 认同；身分；识别
tourism [ˈtʊˌrɪzəm]n.旅游业；  sector [ˈsektər]n.行业；扇形；网络扇区
reputation [ˌrepjəˈteɪʃ(ə)n]n.名声；名誉  pleasant  [ˈplez(ə)nt]adj.令人愉快的；
admire [ədˈmaɪr]v.钦佩；欣赏  

resident [ˈrezɪdənt]n.居民；住户  unhurried [ʌnˈhʌrid]adj.从容的；不慌不忙的
sophisticated [səˈfɪstɪˌkeɪtəd]adj.见多识广的；老练的  boast [boʊst]n.夸耀；夸口v.自夸
income [ˈɪnˌkʌm]n.收益网络收入  flourish [ˈflɜrɪʃ]v.繁荣；兴旺
entertainment [ˌentərˈteɪnmənt]n.娱乐；娱乐活动  venue [ˈvenˌju]n.场地；(体育)场馆
gallery [ˈɡæləri]n.画廊；美术馆；  situated [ˈsɪtʃuˌeɪtɪd]adj.位于；坐落
midway [ˈmɪdˌweɪ]n.中途；娱乐场  satellite [ˈsæt(ə)lˌaɪt]    n.卫星；  很好记得这个
dockside [ˈdɑkˌsaɪd]n.码头边；坞边    网络码头前沿；港区；
commons [ˈkɑmənz]n.“common”的复数；公地；平民
pave [peɪv]v.铺设；  original [əˈrɪdʒən(ə)l]n.原件；正本
admirer [ədˈmaɪrər]n.敬慕者；情人  campus [ˈkæmpəs]n.〈美〉校园；大学
steep [stip]  使沉湎  metropolitan [ˌmetrəˈpɑlɪt(ə)n]adj.大城市的；大都会的；本土的
  
  
  In  short, no matter one's interest, any visitor is sure to enjoy  his stay  in  Boston , hearth of American culture  and still  a leader in education , medicine, and music.

  
  
** Lesson 23   Paper's Long March     long  march     n.【史,事】长征  
  Remember  when the  1980s  brought us  the first  wave  of the modern  computer and  electronics revolutions ? At  that  time , heady young technocrats foresaw  "the  paperless office."  It was claimed that paper would  become  a  thing of the past  as  everyone  would access  all information needed form video  screens.

  wave      美: [weɪv]   n.波浪；波动；风潮；射流  .波动；挥；起伏；挥手[
revolution     美: [ˌrevəˈluʃ(ə)n]   n.革命；剧烈的变革；回转；转数
heady     美: [ˈhedi]  冒失 adj.强烈作用于感官的；使兴奋的；使有信心的；冲动
technocrat     美: [ˈteknəˌkræt]   n.专家治国论者；(高级)技术人员
foresee     美: [fɔrˈsi]   v.预知；有先见之明
access    美: [ˈækˌses]  v.进入；〈正式〉到达；【IT】获得或储存(电脑文件) n.通道；入口；机会；权力
  technocrat      美: [ˈteknəˌkræt]   n.专家治国论者；(高级)技术人员
  The  reality today is quite different.   More   paper than even   is being  used in offices, schools,  and residential homes.  One's  first  possession in life is a  birth certificate, made  of paper.  Childhood  immunizations are recorder on  paper  and kept in the doctor's  office and at home. What  would  school be like  without  paper? Paper  follows most people  throughtout  their  education  and into  their  working life. Wedding  invitations  and marriage certificates are printed on paper, as are virtually  all major life passages and  social occasions. Finally,  a  death certificate on paper  will continue  to be  around long after the  person  named   on it. Perhaps  the one  item  which  defines  modern  civilization  more that  any other is  paper.
  reality  美 [riˈæləti]      n.现实；事实；实际情况；实际经历
  residential  美 [ˌrezɪˈdenʃ(ə)l]     adj.适合居住的；生活有关的,住宅的；需要在某地居住的；提供住宿的
  certificate  美 [sərˈtɪfɪkət]      n.证明；证明书；合格证书；文
  immunization 美 [ ˌɪmjʊnəˈzeɪʃən]     n.免疫；免疫作用；免疫法；免
virtually     美: [ˈvɜrtʃuəli]   adv.几乎；实际上；事实上；虚拟
occasion 美 [əˈkeɪʒ(ə)n]      n.时刻；机会；诱因    define  美 [dɪˈfaɪn]     v.规定；(弄)明确；为…下定义
possession  美 [pəˈzeʃ(ə)n]     n.拥有；具有；属地；个人财产

  The  world  paper derives from papyrus, the name  of a  riverside plant similar to grass, from which an   ancient form  of paper was used in Egypt and   Mesopotamia. It could be  argued  that  these  empires were  made  possible by the use  of official  records on papyrus. However, paper  as we know it today  has its origins in the Han  dynasty of China . In  about A.D. 105 , an  official in the imperial court produced the  forebear of what has become  today  the world's  most indispensable product.  The  art  of paper making reached  westwards to Baghdad, Iraq in the   8th  century at the  height of the  Islamic culture. From  there  it entered Europe , where is  was polished into its contemporary   form during the 19th   century.
   derive  美 [dɪˈraɪv]      v.得到；追寻起源；推论；由来
papyrus  美 [pəˈpaɪrəs]   n.纸莎草； riverside  美 [ˈrɪvərˌsaɪd]      n.河畔；河岸
ancient  美 [ˈeɪnʃənt]      adj.古代的；古老的；很老的 。 imperial  美 [ɪmˈpɪriəl]       adj.帝国的；
the imperial court  朝廷  court UK: [kɔː(r)t]n.法院；宫廷；院子；求婚
forebear  美 [ˈfɔrˌber]      n.祖先；祖宗
indispensable  美 [ˌɪndɪˈspensəb(ə)l]      adj.必不可少的      n.不可缺少的人或物
Islamic  英 [iz'læmik]      adj.穆斯林的  网络伊斯兰教；伊斯兰教的；
polished  美 [ˈpɑlɪʃt]      adj.抛光的；磨光的；擦亮的；优雅的      v.“polish”的过去式和过去分词
contemporary     美: [kənˈtɛmpəˌrɛri]   adj.现代的；当代的；当时的

   Paper can be  made from any plant,  but trees  are the best source of cellulose  for paper production.  In fact, earlier forms of paper were made from processed cotton waste and rags,  but trees contain a better proportion and type  of cellulost  than  any other plant. In countries with  a deficiency of  forest land,  other  natural fibers such as  sugar cane pulp ,bamboo, cereal straws , flax, and hemp are  used.  Today's paper  and paper product mills rely  on a steady inflow of wood  logs or chips. In  the United  States alone,  the  paper and paper  products industry   is  worth  more  thant  US$80 billion , with  world  production  well  over  1000,000,000  tons annually.
  cellulose 美 [ˈseljuloʊz]    n.纤维素； earlier forms  早期 
cotton 美 [ˈkɑt(ə)n]    n.棉；棉布 .   waste  美 [weɪst]    n.垃圾
contain  美 [kənˈteɪn]      v.包含；含有；控制；容纳 .  proportion   美 [prəˈpɔrʃ(ə)n]      n.比例；部分；
deficiency  美 [dɪˈfɪʃ(ə)nsi]      n.缺乏；不足；缺陷；    
fibers是fiber的复数  fiber  美 [ˈfaɪbər]     n.〈美〉同“fibre”      网络纤维；光纤；纤维发射器
cane 美 [keɪn]      n.手杖；藤条；藤杖；（某些植物，如竹或甘蔗的）茎     v.   pulp   美 [pʌlp]     n. 渣 纸浆；髓；浆状物
 cereal  美 [ˈsɪriəl]    n.谷物；   straw 美 [strɔ]      n.稻草；(吸冷饮用)麦秆状吸管           flax  美 [flæks]      n.亚麻；亚麻纤维
  Mills 美 [mɪl]  paper product mills  造纸工厂 ;  a steady inflow 固定 
  logs 圆木， 日记  ；  chips 片  ；油炸土豆条；炸薯条
  annually 美 [ˈænjuəli]     adv.一年一次地
   deforestation 美 [diˌfɔrəˈsteɪʃ(ə)n]      n.毁林；滥伐森林；烧林     网络森林砍伐；砍伐森林； 
  
    Everyone  knows what  paper is , since  most people  use at   least  one sheet of it a day , but few  people  stop  to consider the different kinds  of paper  available to us  today . Office  workers   are well aware  of the many  kinds of  paper they   use,  such as  regular typing or computer printing  or copier paper.  They  also  come into  contact with bond, a high-grade paper used for  important documents. It is  thicker and more durable than other  forms of paper.  Book paper comes in at least four different  finishes, These may be  seen in books, magazines, brochures,  and calendars, Newsprint is used  for newspapers and some  magazines or books, while kraft  paper  is used for shopping    bags.  Paperboard is seen  daily as  bo lunch containers,  cardboard boxes, and even  building materials. Finally ,sanitary  paper has been developed for use in tissue paper, paper toweling, and paper napkings. Carbon paper, postcards, and envelopes are also dialy  use items  made  of  paper.  Even a tea  bag  is made of paper!

sheet  美 [ʃit] n.薄板；床单；纸张；报纸    aware 美 [əˈwer]        adj.意识到；知道
regular   US [ˈreɡjələr] ；经常的；常规 规则的；有规律的
copier  US [ˈkɑpiər]      n.复印机；誊写笔；誊写[复写]员；抄录者 Web影印机；打印机
bond  US [bɑnd] n.债券；键；结合  铜    v.使牢固结合； grade  US [ɡreɪd]      n.品级；水平；评分等级；阶段      v.分等；给
thick  US [θɪk]      adj.充满；弥漫；厚的；粗的      n.最厚[粗]的部    durable  US [ˈdʊrəb(ə)l]     adj.耐用的  form 纸张
finish  US [ˈfɪnɪʃ] 完成, 材料  kraft US [kræft]      n.牛皮纸  .  paperboard   ['peɪpəˌbɔd]    na.卡纸板
material  US [məˈtɪriəl]      n.材料；资料   sanitary   US [ˈsænɪˌteri]      adj.卫生的；环境
tissue paper, paper toweling, and paper napkings
tissue  US [ˈtɪʃu]      n.绵纸；（人、动植物细胞的）组织；手巾纸
toweling  US [ˈtaʊəlɪŋ]      n.毛巾；手巾；纸巾
napkin  US [ˈnæpkɪn]      n.餐巾(纸)；   item US [ˈaɪtəm]      n.项目；(新闻的)一条；(戏剧的)节目 adv.同上      Web物品；道具；
    
    Paper and its products seem endless ,but conservation of even the  abundant resource of  trees is in everyone's interest.  Recycling of paper   and better  designed pulp and paper factories have helped decrease waste.  Many  offices encourage   the use of  both sides of  a piece of paper, for example , and  students  or private  organizations  sometimes collect  old newsprint to send to reprocessing center. By conserving paper, the average paper user in his lifetime  can  save at least one tree from being  felled. As valuable as trees  are,  and as valuable as paper is , everyone  should  cooperate  to use this essential  commodity wisely. 
    conservation  US [ˌkɑnsərˈveɪʃ(ə)n]      n.保护；保持；
    abundant      US: [əˈbʌndənt]       adj.大量的；丰盛的；充裕的
decrease  US [dɪˈkris]  .降低；减少；缩小  pulp US [pʌlp] n.纸浆  .降低；减少；缩小；减弱
fell  US [fel]   adj.邪恶的；残暴的  v.砍伐（树   ; newsprint   US [ˈnuzˌprɪnt]     n.新闻纸；白报纸
    essential  [ɪˈsenʃ(ə)l]      n.要点；要素；实质；必需品 adj.完全必要的；必不可少的；
    commodity  US [kəˈmɑdəti]     n.商品；产品；货物；商品经济      Web日用品；品名；  wisely 精明地；明智的
    
**  Lesson  25 Earthquake Precautions 
    17分后没声音了
   Bam! The  bathroom door  slamming against the wall woke me out of a  sound  sleep. Groggily wending my way  in the  dark  to the bathroom, I secured  the door  latch to make sure I would have no  further  interruptions of much-needed  sleep. I  then  lumbered back into  bed  and started to drift off .
precautions是precaution的复数
precaution  美 [prɪˈkɔʃ(ə)n]  n.预防；预防措施 v.使提防；预先警告
slam  美 [slæm]  v.（使…）砰地关上；用力一放；使劲一推；猛劲一摔
sound sleep n.熟睡    groggily 美 ['grɒdʒɪlɪ]  adv.摇摇晃晃地
wend  美 [wend]  v.  走
secure 美 [sɪˈkjʊr]  v.担保；获得；保证；得到
further  美 [ˈfɜrðər] dv.进一步；此外；更远；而且  v.促进；增进
drift 美 [drɪft]  v.漂移；漂流；  drift  off 睡着

  Not for long. My body , the bed and the whole bedroom  began shaking. After a few  confused  and frightening seconds, I realized   "Earthquake!" "Big one" I added, noting  that  the neighborhood dogs had joined in the weird sounds the hills around my house were making. Within  moments I was  out of  bed and on my feet, contemplating leaving the house. "I'll wait", I comforted myself. "Even these  big ones  pass in a few seconds."
contemplate  美 [ˈkɑntəmˌpleɪt]  v.考虑；沉思；思量；思忖  网络注视；凝视；打算

  This one wouldn't , It kept coming;everything was  shaking and trembling,  rattling,  I heard  a pane of glass crash  onto the floor. The walls of the house and the  things attached to them   seemed to heave, not just shudder.    I then  noticed that  the street lights had failed and  my heart was pounding harder than  when I used  to lift  weights. I acknowledged my fear.
  
tremble  美 [ˈtremb(ə)l]  v.颤抖；发抖；颤动；哆嗦
rattle  美 [ˈræt(ə)l]  n.拨浪鼓；一连串短促尖厉的撞击声；咔嗒声  v.（使）发出咔嗒咔嗒的声音；（运行时）发
pane     美: [peɪn]   v.嵌玻璃于；用染色小布片拼做(衣服)   n.（一片）窗玻璃
attached to 网络附属于；隶属于；  美: [əˈtætʃt] 
heave 美 [hiv] n.举；起伏；拖；拉  v.拖；（强烈而有节奏地）起伏；
shudder  美 [ˈʃʌdər]  n.战栗；强烈的震动；剧烈的抖动  v.战栗；强烈震动；剧烈抖动
pound     美: [paʊnd]  v.捣碎；反复击打；连续砰砰地猛击；咚咚地走  n.英镑（英国货币单位，等于 100 便士）
acknowledge 美 [ək'nɒlɪdʒd] v.承认；公认；认为；感谢  网络公认的；承认告知；得到承认的

   Realizing  that  there  was  no time  to flee  the house, I simply  waited and  waited.  The   nearly  one-minute long temblor finally subsided, and my  reasoning came back to me.  All  was  well, or  well enough. I walked unsteadily to another room  and looked  outside. A neighbor with  flashlight was checking on his and others'  homes for damage.
   flee      美: [fli]   v.逃跑；迅速离开
subside      美: [səbˈsaɪd]   v.沉降；消退；平息；减退
reasoning      美: [ˈriz(ə)nɪŋ]   n.推理；论证；推想；理性的观点
unsteadily  美[ʌn'stedɪlɪ] adv.拿不准地；不安定地；跌跌撞撞地
damage  美[ˈdæmɪdʒ]      v.      损坏; 伤害      n.    损坏; 伤害; 不良影响; 损害赔偿金

    I know  it had been a major quake, though not  centered  where I lived. The next day  I  learned that a 7.6 Richter-scale earthquake had devastated the lovely  rural communities  of central  Taiwan.  For  the next  few  weeks,  everyone's  life  was  centered around the quake due  to  the constant media coverage and electricity rationing.
    
Richter scale  美 ['rɪktə skeɪl]      na.【地】里氏地震强度表
devastate  美 [ˈdevəˌsteɪt]      v.摧毁；彻底破坏；毁灭；使震惊
rural  美 [ˈrʊrəl]      adj.乡村的；农村的；似农村的
community  美 [kəˈmjunəti]      n.社区；社团；社会团体；居民
constant  美 [ˈkɑnstənt]      n.常数；常量      adj.连续发生的；不断的；
ration 美 [ˈræʃ(ə)n]      n.定量；（给战士或食品短缺地区的人提供的）定量口粮；正常量；合理的量      v.配给；限定…的量；定量供应

    Taiwan  is but  one of  many places situated along the "Ring of Fire"  encircling nearly  half the globe around the Pacific   Ocean. Constant  volcanic and earthquake action occurs here.  sometimes with  cataclysmic results.  In   this  century alone. major  earthquakes have taken  more than  one million lives.  Many  more have been  injured and made homeless. The economic 经济, social, and personal costs  are immeasurable.

situated  美 [ˈsɪtʃuˌeɪtɪd]      adj.位于；坐落在；处于…状况；处境…
encircle 美 [ɪnˈsɜrk(ə)l]      v.包围；围绕；环绕
cataclysmic  美 [ˌkætəˈklɪzmɪk] 剧变
injured 美 [ˈɪndʒərd]      n.伤员；受伤的人；伤兵
immeasurable  美 [ɪˈmeʒərəb(ə)l]     adj.不可估量的；无限的；无穷的

Over  the pass  quarter century,  many  countries in earthquake-prone areas have  begun to educate their   citizens on how to take  appropriate precautions for earthquakes. The  following  list has been  compiled from experience.

appropriate 美 [əˈproʊpriˌeɪt]      v.拨款；剽窃；挪用 adj.恰当的
precaution  美 [prɪˈkɔʃ(ə)n]      n.预防；预防措施

    Before the earthquake:
    Prepare an "earthquake kit"(地震包))  near   everyone's  bed; these kits should  include  drinking  water, a flashlight with fresh batteries , and dry food.
    Place an extra pillow, blanket, or quilt near  the bed  to be placed over  the head during the earthquake and  for  warmth if  trapped  afterwards.
      trap    美: [træp]     n.圈套；牢笼；嘴；（捕捉动物的）陷阱    v.吸收；使落入险境；使陷入困境；卡住  afterwards      美: [ˈæftərwərdz] adv.后来；以后
 
    During  the earthquake:
    If possible, get out of the building you are inside of and into a clear area.
    If  escape from  building is impossible, get away from windows  and doors; try  to  find shelter under   structural beams  or under   any heavy piece of furniture, like  a large  table  or bed.
shelter    美: [ˈʃeltər] n.避难所；庇护所；躲避；住所v.躲避；保护；庇护；遮蔽
structural     美: [ˈstrʌktʃ(ə)rəl]  adj.结构（或构造）上的
beam    美: [bim]  n.梁；道；(船的)横梁；【物】波束  v.闪光；眉开  urniture      美: [ˈfɜrnɪtʃər] n.（可移动的）家具
    After  the major  earthquak (remember that  aftershocks will occur):    aftershock     美: [ˈæftərˌʃɑk] n.【地】余震；余悸

    When  shaking ends   or subsides, turn  off tag lines.
    Leave the building   ( never use elevators)  quickly but  not in  a panic.   panic    美: [ˈpænɪk] adj.恐慌的；(恐慌心理)没来由的；过度的；牧人之神的 n.惊恐；恐慌 快速而不是恐慌
    If  uninjured, be ready  to assist rescue workers with  information  or labor.
       assist    美: [əˈsɪst] v.协助；帮助；援助；促
       labor    美: [ˈleɪbər] n.劳动；分娩；工作；人工v.劳动；苦苦地干；颠簸
    When  a  Big  One happens, there  is little anyone  can do. The  above  contingency   preparations,  however, could  make the difference between   life   and death. 
    ontingency    美: [kənˈtɪndʒənsi] n.可能发生的事；偶发（或不测、意外）事件 网络偶然性；意外事故；意外事

    


** Lesson   26   Berries: Nature's Natural Desserts

  The last child has left  the house for school. The  table is clean and neatly set, and the  coffee is brewing . The  cool orange juice  stands like a sentry over the tableware. Mother sits down , pours cereal into  a bowl, and sprinkles  it lightly with sugar. She  is then  ready for the final masterpiece. She  carefully spoons pre-cut ruby strawberries onto the mound of golden corn flakes. Pouring ivory-white milk  over the  concoction, Mother smiles to herself. An attractive, nutritious  breakfast fit for a  queen. 

  neatly  [ˈnitlɪ] adv.整洁地；巧妙地；整整齐齐
brew   [bru] v.酝酿；沏   .  sentry  [ˈsentri] n.哨兵  v.站岗；
pour  [pɔr] v.倒；倾注； . cereal  [ˈsɪriəl]  麦片    n.谷物；谷类植物
sprinkle  [ˈsprɪŋk(ə)l] v.撒；洒；点 .   masterpiece  [ˈmæstərˌpis] n.杰作；名著；
spoon  [spun] n.匙；一匙的.  mound  [maʊnd] n.土墩；小丘；小山岗；一堆
flake [fleɪk] n.鳞片；薄片；絮片   pour  [pɔr] v.注；倾注；倾吐；流
attractive  [əˈtræktɪv] adj.迷人的；楚楚动人的；吸引人 . nutritious  [nuˈtrɪʃəs] adj.有营养的；

 Most  people  around the world  are now familiar  with and can enjoy  strawberries, but few are familiar with  other more exotic berries, such as   the  gooseberry, blackberry, and raspberry. Indeed, even  fewer  people realize  what the word berry  technically refers  to.  The  berry of the botanist and  the berry of the public  are often  two  quite different fruits.

 exotic  [ɪɡˈzɑtɪk] n.舶来品；外来物；adj.异国风味的
 gooseberry  [ˈɡusˌberi] 醋栗  raspberry  [ˈræzˌberi]
technically  [ˈteknɪkli] adv.根据确切意义地；在专业上
refer to v.查阅；提到 botanist  [ˈbɑt(ə)nɪst] n.植物学家  botanic garden  植物园 

 Those  whose  specialty is plants define a berry  as s simple, fleshy fruit with a thin wall and many seeds.  Under this classification  are several surprises.  One  would  expect that cranberries are berries, of  course, but  less obvious  members of this class are dates, grapes, tomatoes, and even potatoes,  bananas, and  asparagus! Indeed , according to  botanists, some popular "berries" are not true berries at all.  Experts in plant life  consider the blueberry an  "inferior berry"  and  the  strawberry, raspberry, and  blackberry an "aggregate fleshy fruit."  However no matter  how  scientists call them , most people think of berries as small, round sweet, and  delicious fruits.

 those  [ðəʊz] adj.那些(的) . fleshy  [ˈfleʃi] adj.多肉的；肥胖的；肉质的
expect [ɪkˈspekt] v.期望；预 .  expert  [ˈekˌspɜrt]  专家n.内行；技师

  Berries such as strawberries , blackberries, respberries, and blueberries prefer cool and moist growing  conditions. Though they  rarely thrive in tropical conditions ,they  can  be  grown on the sides of taller  hills  and mountains there. Several  species  of wildlife  forage  for berries , the largest of these being  the bear.  Some  smaller mammals and  birds, too, enjoy  berries ,not to mention  people. Wild berries are noticeable smaller than  their  domesticated  cousins,  but many people  prefer the full,  rich taste of  freshly  picked forest berries.

moist  [mɔɪst]     adj.微湿的； rarely  [ˈrerli] adv.很少；罕有
thrive  [θraɪv] v.繁荣；茁壮成长；蓬勃;  tropical  [ˈtrɑpɪk(ə)l]adj.热带的；来
condition  [kənˈdɪʃ(ə)n] n.条件；情况  forage [ˈfɔrɪdʒ]  为食物 n.牧草；饲料；粮秣；粮秣的搜索[征发]
    v.搜索[征发]粮秣；给(马)吃草料
noticeable [ˈnoʊtɪsəb(ə)l]    adj.显著的；显而  
domesticate [dəˈmestɪˌkeɪt] v.驯养；栽培； cousins [ˈkʌz(ə)n]n.堂[表]兄弟；亲戚
    
 Besides being  a condiment on breakfast  cereals(麦片), are there  any other  uses  for berries? Westerners make good  use of their local fruits.  Jellies, jams, and preserves can be easily made with berries, gelatin,  and sugar. These  three  sweetend foods differ only  in the process used to make them. Jellies are made  from the juice of a fruit, jams from the thoroughly crushed fruit, and preserves from the  partially  crushed or cut fruit.  They are all equally delicious!

 condiment  [ˈkɑndɪmənt] n.调味料；  cereal [ˈsɪriəl]n.谷物
jelly  [ˈdʒeli]  v.使成为胶质；使冻 果冻
jams [dʒæmz]n.果酱；堵塞；拥   preserve  [prɪˈzɜrv]v.保留；保护；蜜饯
partially  [ˈpɑrʃəli] adv.部分地；

  Berries are also  used  in baked goods. Pies and tarts often  contain  berries as do many other  pastries. These  small  fruits are also  added into  cakes  and  even  breads, especially after drying. In  addition ,  the concentrated juice of berries can be used to  make cool   summer drinks. Concentrated further, various  syrups can be added to foods as diverse as  pancakes and ice cream. As flavorings, they  are often added to candies and chocolates. In Western  cuisine, life  would be less  sweet  and interesting  without  the humble berry.

  bake  [beɪk]  v.烤；焙干  tart  [tɑrt] adj.酸的；尖酸刻薄的；严厉的 n.〈英〉(果)馅饼
  pastry  [ˈpeɪstri]n.油酥面  糕饼
  addition  美 [əˈdɪʃ(ə)n] n.添加；增加；  concentrated  [ˈkɑnsənˌtreɪtəd] adj.决心要做的；全力以赴的；浓缩的
further 美 [ˈfɜrðər] adv.进一步；此外；更远；而且 v.促进；增
various  [ˈveriəs]     adj.各种不同的；  syrup  [ˈsɪrəp] n.糖浆；
diverse  [daɪˈvɜrs]     adj.不同的；相异的；多种多样的；形形色色的
flavoring  [ˈfleɪvərɪŋ] n.香料；调味 ；  cuisine  [kwɪˈzin] n.烹饪；菜肴

  For  some  people, though, berries   are best  eaten fresh. They  say that  after washing and  refrigerating,   simply place  a  generous  portion of berries into a cereal  bowl, add chilled milk , and top with sugar.  Enjoy ! As the season for berries is  usually in the summer and fall, this  snack  or dessert really hits the spot. For  those  who  do not live where berries grow  naturally and plentifully, these natural  dessert fruits  can be enjoyed while visiting those areas  luck  enough  to have  them.

  refrigerate  [rɪˈfrɪdʒəˌreɪt] v.冷冻；解
  generous  [ˈdʒen(ə)rəs] adj.慷慨的；大方的； portion[ˈpɔrʃ(ə)n] n.部分；（食物的）一份；分享的部分；分担的责任
    v.把…分成若干份（或部分
cereal  [ˈsɪriəl]    n.谷物；谷类植物；（常加牛奶作早餐用的）谷类食物
    adj.谷类制成的
chilled  [tʃɪld]  adj.冷却了的；冷淬过的；经过冷藏的
snack  [snæk] n.小吃；快餐；点心 hits the spot  恰到好处
spot  [spɑt]  n.斑点；污迹；污渍；脏点     v.看见；看出；注意到；发现
    adj.现货交易的；立即支付的  网络地点；场所(BBG)

复数：spots  过去式：spotted  现在分词：spotting  

    
**  Lesson  27  The Global Proliferation of  English
 感觉主要是查看不认识的单词上 感觉理解比以前更加好了 

 02:56 
Everyone  knows that  there  are more speakers  of Mandarin  than  other language in the world. Just  over one billion  people speak Mandarin as their native tongue. Compared  to  the nearly for  hundred  million native speakers of English. there would appear to be "no contest"  Yet , it  is just  as well-known that English  ,not Mandarin, is the international language. Given  these  statistics, how can this be ? Looking  more closely  at these and other facts reveals how English has become the world's  most widespread  language.

mandarin  [ˈmændərɪn]n.柑橘 普通话；  no contest  没得比 不抗辩；
statistics  [stə'tɪstɪks] n.统计学； widespread  [ˈwaɪdˌspred]     adj.分布广的；普遍的；大
reveal  [rɪˈvil]v.启示；揭露；透露

   The  history of written Chinese goes  back at   least 4 000 years.  that   of English  little more than   1 000 years.  The language  called English  is actually a  hybrid of Scandinavian  and  German  tongues   created by  immigrants  to England   in the 5th century  A.D.  Over  the next  500 years, English developed into several major dialects spoken principally on most of the island of England. With  continuous invasions by  more  Scandinavians and   the French over the  next few centuries,  the English language  received a fresh stimulus  of foreign  words, including Latin and Greek, the preferred classical languages in  educational  and political circles at that  time in Europe. English as a  principal language of literature did  not evolve until the 14th  century(Chaucer).  By   the 16th  century, English was in full bloom, both  in  literature as well  as in science.

   England,  referred to  as  Great  Britain by   this time, was  amassing  political, economic, and military  power  at breath-taking(惊人的) speed.  The Industrial Revolution of  the next century  required foreign  resources;  imperialism  gave the go-ahead  for Britain and  other European powers to not only take  what  they  wanted  from foreign lands  but to  lay  conquest to those lands as well.      Additionally, the rapid  social changes engendered by the change from agriculture to manufacturing meant a surplus of farm workers, resulting in a  waiting army of  the dispossessed  to emigrate to Britain's  newfound colonies. In the  17th and  18th  centuries, millions of Englishmen left their mother  country  for  North America.  In the  18th century,hundreds of thousands more set sail for Australia and New Zealand, as  well as  South Asia(the British Raj)  and Africa(primarily South Africa).  At  the height  of the British Empire, one-fourth of the world's  people  and lands  were living under the Union Jack. Thus, by  the close of the 19th  century English  rule had extended to the six principal continents(including British Guyana in South America.)
refer to      v.查阅；提到  amass  [əˈmæs]v.积聚；收集；
union jack n.联合王国国旗   military [ˈmɪlɪˌteri]  n.军事 军队
imperialism  [ɪmˈpɪriəˌlɪzəm] n.帝国主义；帝国统治 conquest  [ˈkɑŋˌkwest] n.征服；占领
additionally  [əˈdɪʃ(ə)nəli]adv.另外 rapid [ˈræpɪd] n.急流；滩流adj.瞬间的；快速的
manufacturing  [ˌmænjəˈfæktʃərɪŋ] n.制造业  engender  [ɪnˈdʒendər]  v.产生；
surplus  [ˈsɜrpləs]  n.盈余；顺差；剩余；过剩  dispossessed  [ˌdɪspəˈzest] n. 无产 被剥夺财产者
emigrate  [ˈemɪˌɡreɪt]v.移民；移  colony  [ˈkɑləni]n.殖民地；【
sail for  [seɪl] v.驶向  extended  [ɪkˈstendəd]  延伸    adj.延长了的
principal  [ˈprɪnsəp(ə)l] n.本金；委托人；资本；主角     adj.最重要的；主要的
continent [ˈkɑntɪnənt]     n.大陆；陆地


hybrid  [ˈhaɪbrɪd]  n.杂种；杂种动物；杂交植物 adj.杂种的；混合的；  Scandinavian  [ˌskændɪˈneɪviən] n.北欧(人)的；斯堪的纳维亚语(的
immigrant  [ˈɪmɪɡrənt]    n.侨民； dialect  [ˈdaɪəˌlekt]n.方言；语调
principally  [ˈprɪnsəp(ə)li] adv.主要地 invasion  [ɪnˈveɪʒ(ə)n] n.侵略；侵犯
prefer [prɪˈfɜr]v. 偏爱,推荐；建议；申请
classical  [ˈklæsɪk(ə)l] adj.古典的；经典的   
stimulus  [ˈstɪmjələs] n.刺激物；促进因素   evolve  [ɪˈvɑlv]     v.进化；演
bloom  [blum] v.盛开；开花；繁殖；   literature  [ˈlɪt(ə)rəˌtʃʊr]     n.文学；文学作品
political  [pəˈlɪtɪk(ə)l]  adj.政治的  political circles  政坛

  This first-ever domination of the gobe by one language is the primary reason for the  international  use of English  today. A second reason  lies in the rise  of the United States of America  as a  leading world  power  just  as Britain's  power began to fade. At  The  close of  the 19th century, the U.S. fought with Spain(in 1898)   After the U.S. victory, Spain  ceded the Philippines, Guam ,and Puerto Rico .resulting in the further  introduction of English  into Asia  and the Caribbean. After U.S. involvement in both  World Wars, despite Britain's  continued decline, English became  more commonly used  around the world, especially  in continental  Europe and Japan. Since 1950,  the  rapidly growing U.S. economy as  well as  its academic and scientific  excellence has insured that  English  remains the language of commerce  and intellectual intercourse. The world of entertainment,most notably Hollywood, has  also contributed to  the popularization of English .
 first-ever    adj.首次的  domination  [ˌdɑmɪˈneɪʃ(ə)n] n.统治；优势
 lies in the rise  of  在于崛起  lie  [laɪ] n.谎言；诺言 v.躺；在于
fade  [feɪd] v.逐渐消失逐渐消逝  cede  [sid] v.割让；让给；转让
despite  [dɪˈspaɪt]prep.尽管；即使 decline   [dɪˈklaɪn]v.下降；衰退
rapidly  ['ræpɪdli]adv.迅速；高速   academic  [ˌækəˈdemɪk] adj.教学的；学术性的
commerce  [ˈkɑˌmɜrs] n.商业；intellectual  [ˌɪnt(ə)lˈektʃuəl]n.知识分子；脑力劳动者 intercourse  [ˈɪntərˌkɔrs]    n.交际
contribute  [ˈkɑntrɪˌbjut]  v.捐献；投稿； notably   [ˈnoʊtəbli]    adv.特别；非常
  
  It is estimated that  at least  300 million people around the world are now studying or using English  as a second language, for purposes of education, employment , or personal interest, Some 75% of all international communications  are in English , and with  the rise   of  the Internet , it is  doubtful that  this  figure  will decrease any time soon.  At the dawn of the new  millennium, the world has  on international language, English.

estimate  [ˈestɪmət]n.估计
doubtful  [ˈdaʊtfəl]adj.怀疑；拿不定主意  decrease  [dɪˈkris]v.降低；减少
dawn  [dɔn]     n.黎明；曙光；拂晓；破晓 v.开始；变得明朗；开始清楚
  domination  [ˌdɑmɪˈneɪʃ(ə)n]  n.统治；优势；【生】显性化     网络支配；控制



  
**  Lesson  28

现在分词 
Offsetting

  
** Lesson 30 New Orleans: Birthplace of Jazz
 Orleans : [ˈɔrliənz] n.奥尔良    jazz [dʒæz] n.爵士乐
 
  Welcome to  Crescent City, birthplace of Jazz!"Crescent City" ? Yes, the nickname  for New Orleans  is Crescent City, due  to its downtown location along a  particularly  deep bend of the   Mississippi River. No matter  what this unique American city is called, New  Orleans has  something for everyone. 

  crescent  [ˈkrez(ə)nt] n.新月形  particularly  [pərˈtɪkjələrli] adv.特别；尤其
bend [bend] v.弯曲；（使）倾斜     unique [juˈnik] adj.唯一的

  To understand why this  southern city is so different  from  any other  city of the United States, and perhaps also how it evolved the musical form Dixieland jazz, it is necessary  to give a  brief  description  of its history.  Founded in 1718 by  French developers, New Orleans grew  rather slowly. Although  ideal for  shipping(New Orleans is only 180 kilometers from   the mouth of the Mississippi, the world's fourth-longest river), the land around New Orleans is extremely low-lying(The city is  actually below sea level!) and was  at that time nothing  more than  a  swamp. Despite this , the city  attracted a  wide range of peoples, including Canadian  and European  French, slaves, American  Indians, and a  few  white British settlers, The area's  continued slow growth, however, convinced France that it should sell  all of its  extensive land holdings in North  America to Spain in 1763. Spain ruled this large area including  New Orleans until 1800, when  the whole area was again returned to French , only to be sold to the United States in 1803. The  early  French and Spanish cultures have remained with city, even  with approach of 200 years of American rule .
OB
  evolve [ɪˈvɑlv] v.进化；   description [dɪˈskrɪpʃ(ə)n] n.说明；形容；描述；
mouth [maʊθ] n.口；嘴；河口  mountain [ˈmaʊnt(ə)n] n.山；高山；
low-lying adj.低下的；低洼的； 
swamp [swɑmp] v.淹没； 沼泽地      despite [dɪˈspaɪt] prep.尽管
convinced [kənˈvɪnst] adj.确信；深信；说服 
approach [əˈproʊtʃ] n.方法；接近  

  The fortunes of  New  Orleans have always  depended on its riparian location. The city gained importance  in the War  of  1812 and later as the terminus  for shipping   along the Mississippi through  the Civil War.   As shipping declined   in importance  due to   the building  of the railroads near the end of  19th century, however, the Golden Age of New  Orleans  wound down .  At  this time , however, an artistic  creation particular to New Orleans would  resuscitate the  city's fortunes. 

fortune [ˈfɔrtʃ(ə)n] n.命运；运气；财产  美: [raɪ'peəriən]  adj河边的；堤岸（上）的；堤岸近处的
gain [ɡeɪn] v.获得；增加  terminus [ˈtɜrmɪnəs] n.（铁路或公共汽车路线的）终点站
decline [dɪˈklaɪn] v.拒绝；下降；  golden [ˈɡoʊld(ə)n]     adj.金质的；金的；金色的；金黄色的
creation [kriˈeɪʃ(ə)n] n.创作；创造；创  particular [pərˈtɪkjələr] adj.讲究；挑剔； 独特 专指的；不寻常的
resuscitate [rɪˈsʌsɪˌteɪt] v.使苏醒；使恢复知觉  

   Music has always   played an   important  part  in the daily lives of most Americans, and New Orleans  happend   to be home to some of the best   musicians in the country.  From  1880 to World War I, NEW Orleans with its cafe  and night  club  society  became host(大本营) to a  new form of music based mostly on  the blues, but also on  marches and ragtime music. In this style  of music, the trumpet, clarinet, and trombone form the basis  of instrumentation .  As  the  trumpet is  the loudest, it normally  carries the melody, with the clarinet and  trombone improvising  above  and below the trumpet, respectively. Sidney  Bechet, Buddy Bolden, King   Oliver, and most famously Louis Armstrong became  symbols of the new music , playing to packed houses  at first in the New Orleans  red light district, and  later to  fans  in music   halls all  around the world.

society [səˈsaɪəti] n.学会；协会；社团  marches [ˈmɑrtʃiz] n.“march”的复数；“March”的复数    v.“march”的第三人称单数 进行曲；行军；游行音乐
ragtime [ˈræɡˌtaɪm] n.雷格泰姆音乐（早期爵士音乐   trumpet [ˈtrʌmpət] n.喇叭；小号；
clarinet [ˌklerɪˈnet] n.单簧管；黑管  trombone [trɑmˈboʊn] n.长号
instrumentation [ˌɪnstrəmənˈteɪʃ(ə)n]n.仪表；乐器；工具 melody: [ˈmelədi] n.旋律；主旋律
improvise [ˈɪmprəˌvaɪz] v.临时拼凑；；即兴创作 respectively: [rɪˈspektɪvli] adv.分别地；各自地；个别地
symbol [ˈsɪmb(ə)l] n.符号；象征   district [ˈdɪstrɪkt] n.区；地区；区
hall [hɔl] n.会堂；走廊；展览厅 
penguin 


   Though  Dixieland jazz is today  a preserved form of music like classical music, it later spawned Big Band music  popular  until  the end of World War II, and  urban  jazz,  still popular in the United States  as well as  in other  countries, To hear   the   original Dixieland  jazz  one has   only to book a  hotle room in the Vieux Carre  district of  New  Orleans anytime of the year. The  French and Spanish  architecture and laid-back  lifestyle  there is  the perfect place to enjoy the  upbeat but relaxing  sounds of Dixieland jazz. Devotees of jazz  pack  Preservation   Hall, Dixieland Hal, and the night clubs along  Borubon Street  to hear  their  favorite songs. The  New Orleans jazz  Club  stages  many jazz events, as does  the city government, such as the International  Jazz and Heritage Festival.  If  you can  visit New  Orleans only once  in  your life, though, save it  for  the world famous Mardi Gras. You  can  then  enjoy  the best of New  Orleans's night life  with as many as one million   other party  revelers!

preserve [prɪˈzɜrv] v.保存；保留；保护；保持 spawn [spɔn]  大量出现
urban [ˈɜrbən] adj.城市的；都市的    original [əˈrɪdʒən(ə)l] n.原件；正本；原作
upbeat [ˈʌpˌbit]  adj.乐观的；快乐的；积极向上的  devotee [ˌdevoʊˈti]     n.热爱者；
pack[pæk] v.包装；打包 填满  stage [steɪdʒ] n.时期；舞台；v.举行；上演；
reveler [ˈrev(ə)lər] 逗乐者；寻欢客  狂欢者  event [ɪˈvent] n.事件；活动；事情；大事

   The city of New Orleans has so much  to offer. Its history,  unique cultural blend   including word-acclaimed  cuisines,  and, of course ,its  musical gift to the world , Dixieland jazz, are reasons enough  to place  New Orleans high on  everyone's  "must list" of places to visit, Whether you want to travel to  relax or join in  spirited partying, New  Orleans offers the tourist the best of  both  worlds. 

cuisine [kwɪˈzin]     n.厨房；烹调法；菜肴    网络烹饪；美食；美食篇
spirited: [ˈspɪrɪtəd] 狂欢  adj.精神饱满的；坚定的；勇猛的 v.“spirit”的过去分词和过去式

offer [ˈɑfər] n.报价；出价；建议；主动提议v.供应；奉献；主动提出；自愿给予
    网络 看头  提供；发盘；报盘
blend [blend] v.混合；融合；加入；相称  acclaim [əˈkleɪmd] n.欢呼；欢迎；赞扬




** Lesson 33  Did You Remember Your Tickets?
counter [ˈkaʊntər] n.计算器；（商店、银行等的）柜台；  

  Robert and Michael  leave  their  apartment in a rush  and find a  taxi  to take  them to the airport.  After   paying  the drive, Robert turns to Michael and says, "That  was close! I though wd'd  be late for sure. Come on , now , we have to take our luggage  into the terminal and check in at the counter." "Right," responds Michael, "did you  bring the tickets and out passport?"  "No,"  answers Robert, "I thought you did!"

  This  scene could be from  a TV sitcom or real-life. Every  traveler's nightmare is forgetting something  major like tickets, ID,passport, or money. This  is needless worry,however,if travel plans are made early and organized  efficiently. Since  travel for education, business, or pleasure is more and more common, knowing how to prepare for worry-free travel is  both important  and beneficial. This  lesson will help the novice or  experienced traveler avoid potential travel problems, allowing  for a pleasant  journey.

scene [sin]n.现场；景象；情景  sitcom [ˈsɪtˌkɑm]n.【影视】情景喜剧
needless [ˈnidləs]adj.不必要的；可以避免的  efficiently [ɪˈfɪʃəntlɪ]adv.效率高地; 有效地
beneficial [ˌbenəˈfɪʃ(ə)l]adj.有裨益的；有用的 novice [ˈnɑvɪs]n.新手；初学者
avoid [əˈvɔɪd]v.避免；避开  potential [pəˈtenʃ(ə)l]n.潜力；电位；电势；可能性adj.潜在的；
journey [ˈdʒɜrni]n.旅行；旅程
  
  Unless there is  an emergency, travel plans should be made well  in advance.  Never  wait  till the last minute  to try  to reserve airline tickets or hotel rooms. They may not  be available, or you may  be forced to choose an inconvenient or unnecessarily expensive flight or accommodation. The best day to book travel or lodging arrangements is the day you decide to go.
  
in advance 事先 advance[ədˈvæns]n.进展v.提前；进步 available [əˈveɪləb(ə)l]adj.可获得的；可购得的；；有空的
inconvenient [ˌɪnkənˈviniənt]adj.不方便的；引起麻烦的 accommodation [əˌkɑməˈdeɪʃ(ə)n]n.住宿；住处
lodging [ˈlɑdʒɪŋ]n.寄宿；借宿；暂住；租住的房间    v.“lodge”的现在分词
arrangement [əˈreɪndʒmənt]n.安排；布置；整理 

“学如逆水行舟，不进则退”的英语翻译是： Learning is like sailing against the current； if you don't advance, you will retreat.

  After  all travel arrangements have been secured , the next  step is to make sure your travel documents are in order. Is your passport valid? Remember  that  some countries do not  accept passprots which   have less than six  months' validity  remaining. Do you need an overseas driver's license? These  can be applied for at certain government or travel agencies  or  associations. Leave enough  time  to process any paperwork that is required. A travel agent or experienced friend or colleague can inform you of what steps need  to be taken and how best to take care of them.

secure [sɪˈkjʊr] v.取得 确保...的安全 validity [və'lɪdəti] 有效性；有效期
applied for 申请  applied [əˈplaɪd] adj.应用的；实用的 v.“apply”的过去分词和过去式
certain [ˈsɜrt(ə)n] adj.肯定；确定   agency [ˈeɪdʒənsi] n.机构；代理；局
association [əˌsoʊʃiˈeɪʃ(ə)n] n.协会 process [prəˈses] n.进程；流程 v.处理；加工；
paperwork [ˈpeɪpərˌwɜrk] n.文件；文书工作  colleague [ˈkɒˌliːɡ] n.同事；
  
  Preparing for packing is next. Even if the proposed trip  is a month away, certain items shoud be readied at once. The  most important of these is , of course, the luggage itself. Do not wait for a last-minute sale on the suitcase of your choice;  be ready with enough   good-quality luggage long befor you leave for  the airport or train station. In choosing baggage, make sure  that it is within regulations, especaally for air travel. Oversize  suitcases or carry-on baggage  can be a great headache later.

packing [ˈpækɪŋ] n.包装材料；收拾行囊；打行李 proposed [prə'poʊzd] adj.建议的；提出的；推荐的v.propose（建议、提出、求婚）的过去式和过去分词
certain [ˈsɜrt(ə)n] adj.肯定；确定 ready [ˈredi] adj.准备好；readied ready的过去式和过去分词
item [ˈaɪtəm] n a.项目 物品 sale [seɪl] n.销售；出售；大减价；销售量
within[wɪðˈɪn] n.内部   regulation [ˌreɡjəˈleɪʃ(ə)n]     n.条例；管理；调节规定
headache [ˈhedˌeɪk] n.头痛；麻烦；令人头痛的人（或事物）
  
  The rule of thumb of packing is pack less, not more. Most  travelers buy at least some items on the road , and some buy quite a few souvenirs or personal items, so leave enough  room  for them. Keeping  a toiletry kit permanently in a piece of luggage is a smart idea. In this way , you will never have to worry about  whether your razor or deodorant has  been packed. Casual clothing, including footwear, shoud be placed into bags  or suitcases the night  before. Formal wear can be packed in the last-minute to reduce wrinkling. Don't worry about taking reading or writing material for pleasure; newspapers and  magazines are widely available, as it stationery.

thumb [θʌm] n.拇指； rule of thumb  根据经验的做法
souvenir[ˌsuvəˈnɪr] n.纪念品   toiletry ['tɔɪlɪtrɪ] 〈美〉化妆品 盥洗用品
kit [kɪt] v.装备 n.成套工具；工具箱；  permanently ['pɜːmənəntli] adv.永久地；永远；长期
razor [ˈreɪzər] n.剃须刀   deodorant [diˈoʊdərənt] n.除臭剂 体香剂
casual [ˈkæʒuəl] n.临时工；便装 休闲装  footwear [ˈfʊtˌwer] n.鞋袜类
formal [ˈfɔrm(ə)l] adj.适合正式场合的；正规的   reduce [rɪˈdus] v.减少 降低；简化
wrinkle [ˈriŋk(ə)l] n.褶皱；皱纹  material [məˈtɪriəl] n.材料；原料
stationery [ˈsteɪʃ(ə)nˌeri] n.文具
  
  The day before leaving, reserve a cab for the day of departure if needed. This  is also the best time to ask a friend or relative for a wake-up  call for those leaving earlyh on  the day of departure; this is even better than one's  own alarm clock.  Leave a copy of the itinerary with lodging telephone numbers with a familyh or friend. Place all travel documents into one  briefcase or folder rather than in several places for ease of checking. After packing each piece of luggage, put it  near the door for easy exit These  simple advance steps will help reduce  stress on the day of travel.

reserve [rɪˈzɜrv] v.保留；预订 ==book    cab [kæb] n.出租车；计程车；的士
departure [dɪˈpɑrtʃər] n.离开；出发  itinerary [aɪˈtɪnəˌreri] n.行程；旅行日程
lodging [ˈlɑdʒɪŋ] n.寄宿；借宿；暂住；租住的房间 v.“lodge”的现在分词

  On the day of departure, the only steps remaining  should  be to packe one's  formal clothing and to recheck one's travel  documents and money. Whether for business, education, or  pleasure, travel can be an unforgettable experience, Whether you want to remember that experience fondly or try ot forget it depends on  the few simple steps outlined above. Bon voyage!
  
unforgettable [ˌʌnfərˈɡetəb(ə)l] adj.难以忘怀的；令人难忘的  fondly [ˈfɑndli] adv.深情地
outline [ˈaʊtˌlaɪn] n.轮廓；大纲  
  
** Lesson 35 Hot Animals Around the World: The Panda
   thirty-fifth   Aug 25 21:30 -                                                                                   
 panda [ˈpændə]  猫熊  moron  [ˈmɔˌrɑn]     n.笨蛋；蠢货 huggable  ˈhʌɡəbl   逗人喜爱的；冬季照明抱枕；令人想拥抱\\
 的                                                                                       
       Some  countries have  adopted  an animal as a  kind  of national mascot. The bald eagle is often  thought of as representing the United  States, for  example . New Zealanders  proudly display  their  kiwi, a native  flightless bird. Australians   cannot  seem to make  up their  minds whether the koala  or the  kangaroo should   represent them. China also  has  two animals  which  often  stand  out in everyone's  mind: the dragon and the giant panda. As the dragon is  a mythological animal, that leaves the giant panda as the only real animal  representative  of China. 

adopt [əˈdɑpt]adj. 采用的收养的； 选择   mascot [ˈmæsˌkɑt]n.吉祥物                                                
 bald [bɔld]adj.秃顶的         eagle  [ˈɪɡ(ə)l]    n.鹰；                                                          
 represent  [ˌreprɪˈzent]v.表示；代表   proudly ['praʊdli]adv.骄傲地                                               
 giant [ˈdʒaɪənt] n.巨人；巨兽  mythological  [ˌmɪθə'lɒdʒɪkl]    adj.神话的 
  
 Although  dragons have been associated with China for  thousands of  years, the panda's  inclusion into the Chinese  psyche is far more  recent. The giant  panda was not even  discovered until 1869; it was  already a rare animal at that time , living   in the  high bamboo forests of Sichuan  province  and neighboring parts of Tibet.  Its  more plentiful cousin, the lesser panda, is also referred to as the cat bear or bear cat; however, zoologically speaking , it is neither. The  lesser panda  is a member of  raccoon family, whereas  the giant panda's  classification  is still   dilemma: some authorities consider  it a  member   of the bear family while  others  maintain that  it belong  to the raccoon family, too


  associated [ə'səʊʃieɪtɪd]adj.有关联的；相关的  inclusion [ɪnˈkluʒ(ə)n]n.包含；                                    
 psyche [ˈsaɪki]n.心灵；心态 rare [rer]adv.极adj.稀少的                                                            
 plentiful [ˈplentɪf(ə)l]adj.大量的；众多 zoologically/ zoəˈlɑdʒɪkli /adv.动物学上                                 
 raccoon  [ræˈkun]n.【动】浣熊 whereas [hwerˈæz]conj.尽管；    网络然而；                                          
 dilemma [daɪˈlemə]n.（进退两难的）窘境 网络困境；左右为难  authority [ɔˈθɔrəti]n.当局；权威；专家治国论者         
 maintain [meɪnˈteɪn]v.维护；保持；坚持    habitat 栖息地  

 The giant panda is well named.  Reaching a length of 1.5 meters and 160 kilograms, this  gentle omnivore is among the largest land animals of China.  Subsisting  on a diet  of bamboo  and other plants and even  small animals , it can  consume as much as 30 kilograms of food a day.  Now that's  a giant appetite!  Its  distinctive markings -- broad,  white  bands of fur alternating  with black , and small  black circles arond the eyes -- have  endeared the  giant  panda  to animal  lovers everywhere.

giant [ˈdʒaɪənt]n.巨 大   reach [ritʃ]    v.达到                                                                  
 gentle  [ˈdʒent(ə)l]〈古〉绅士adj.文静的；慈祥的；温柔的 网络温和的                                               
                                                                                                                   
 vegetarian  [ˌvedʒəˈteriən]    n.素食者；                                                                         
 carnivorous  [kɑrˈnɪvərəs] adj.【动】食肉(目)的  herbivory ['hɜbɪvərɪ] n.    食草                                 
 omnivore  [ˈɑmnɪˌvɔr]n.杂食动物    subsist [səbˈsɪst]  v.存在；（尤指靠有限的食物或钱）维持生活；网络生存；       
 consume  [kənˈsum]v.消耗；吃             appetite  [ˈæpəˌtaɪt]n.胃口；食欲                                        
 distinctive  [dɪˈstɪŋktɪv]adj.独特的；特别的   broad  [brɔd]    adj.宽阔的；广阔的                                
 band  [bænd]    n.带    fur  [fɜr]n.舌苔；毛皮衣服；（动物浓厚的）软毛；（动物的）毛皮                            
 alternate  [ɔlˈtɜrnət]     v.交替；轮流   endear  [ɪnˈdɪr]    v.使受喜爱 
 
  People may want  to hug this huge "teddy bear" but giant  pandas prefer  to live a  solitary life.  This  may account  for their  scarcity;  these   pandas are on all  official  lists of endangered  animals. Estimates of the wild panda population  are difficult  due to  the rugged  terrain they  live in, but most experts agree  that  fewer  than 1000  remain  free. As they birth to only one or two  cubs when mating is successful , the giant  panda's  survival in the wild  is anything  but a foregone conclusion.  The  Chinese  government  has set  aside 11 nature preserves  where  pandas  are know  to exist,  hoping to protect them from  the rapid encroachment of man.  Though  poaching is still a problem, strict  laws   have reduced this senseless carnage.

hug [hʌɡ] v.拥抱；   huge [hjudʒ] adj.巨大的
solitary [ˈsɑləˌteri] adj.独自的；单独的
account [əˈkaʊnt] n.账户；说明；   account  for  说明
scarcity [ˈskersəti] n.缺乏；不足；稀少 endanger  [ɪnˈdeɪndʒər] v.危害 网络濒危
due to un.由于     estimate [ˈestɪmət] n.估计；〈英〉预算
rugged [ˈrʌɡɪd] adj.崎岖的     terrain [təˈreɪn] n.地形；
remain [rɪˈmeɪn] v.逗留；剩余；遗留    cub [kʌb] n.〈美〉小熊；仔兽
mate  [ˈmeɪtɪŋ] n.伙伴，同事；老兄，配偶（男女任何一方） v.(使)交配 网络交尾；配套；配种
foregone ['fɔ:gɒn] adj.过去的；早先的  conclusion: [kənˈkluʒ(ə)n] n.结论；结束；
foregone conclusion  笃定的结果 
be anything  but + adj/n 绝不是
aside  [əˈsaɪd]     adv.留；存；到旁边；在旁    网络在一边；到一边；一旁
preserve [prɪˈzɜrv] v.保留；保护   protect [prəˈtekt] v.保护；防护
rapid [ˈræpɪd] n.急流；adj.瞬间的；短时间内发生的；迅速的；快速的
encroachment [ɪn'krəʊtʃmənt] n.侵害；侵略；  poach [poʊtʃ] v.〈英〉偷猎；
strict [strɪkt] adj.严格的 reduce [rɪˈdus] v.减少；降低
senseless [ˈsensləs]     adj.失去知觉；无意义的；无目的的；不明智的    网络愚蠢的；无知觉的；无感觉的
carnage [ˈkɑrnɪdʒ] n.大屠杀 网络杀戮


   Pandas in captivity  number(v)  less than  100, the largest  share, of course  , in China. Those  in Western zoos are treated  as royalty and are the object of intense scientific interest and care. Recently, veterinarians have given male giant pandas  Viagra, hoping  to increase the  animals'  reproductive efficiency. Results  are thus far inconclusive. Though births have been reported, they  are few  and far between. It seems  the  panda's  chance of survival is razor-thin.

captivity [kæpˈtɪvəti]  n.监禁；关押 动物园饲养 treat [trit] v.治疗；处理；对待；招待
royalty [ˈrɔɪəlti] 皇族    intense [ɪnˈtens] adj.很大的；十分强烈的
veterinarian [ˌvet(ə)rɪˈneriən] n.兽医    Viagra [vaɪˈæɡrə] 药物网络伟哥；
male [meɪl] n.男性；    reproductive [ˌriprəˈdʌktɪv] adj.生殖的；繁殖的
efficiency [ɪˈfɪʃ(ə)nsi] n.效率；效能     inconclusive  [ˌɪnkənˈklusɪv] adj.非决定性的；无定论的；
razor-thin  /ˌreɪ.zɚˈθɪn/  机会渺茫的   report  [rɪˈpɔrt] v.报告；报导；发表；呈报

   Its extinction would be a sad day for all mankind. These  playful and gentle creatures   never fail  to amuse adults  and children alike  lucky enough  to observe  them  in zoos. Every  plant and animal  that leaves the world due to human  intervention and encroachment of habitat diminishes the world  we live in. The  richness of the Earth's  original biodiversity  is being attacked. Will  future generations  of humanity be left with only a few  species of food plants,  and zoos exhibiting  cockroaches and rats?

extinction [ɪkˈstɪŋkʃ(ə)n] n.绝种    these  [ðiz] adj.这些(的) pron.这些
playful [ˈpleɪf(ə)l] adj.有趣的；爱玩的；网络顽皮的； creature  [ˈkritʃər] n.生物；东西
fail [feɪl] v.失败；   amuse  [əˈmjuz] v.逗乐；逗笑
adult [ˈædʌlt] n.成人；长成体   observe  [əbˈzɜrv] v.观察；看到；
intervention [ˌɪntərˈvenʃ(ə)n] n.干预；介入  encroachment : [ɪn'krəʊtʃmənt]n.侵害；侵略
diminish [dɪˈmɪnɪʃ] v.减少；减弱；  richness [ˈrɪtʃnəs] n.丰富；富
original  [əˈrɪdʒən(ə)l] n.原件； 原生  biodiversity  [ˌbaɪoʊdaɪˈvɜrsəti] n.生物多样性
generation [ˌdʒenəˈreɪʃ(ə)n] n.世代；一代 humanity  [hjuˈmænəti] n.人性；人类；
species [ˈspisiz] n.种 网络物种  exhibit  [ɪɡˈzɪbɪt] v.展览；显示
   
   Hopefully, men will learn the excesses  of their  ways  and strive  to protect  the remaining natural habitats as an  investment  not only in the flora  and fauna remaining but  in the  quality of  life, present  and future , of all those  on this plant. "Extinction is forever"  and "There is only one world"  need  no longer be heard if one becomes conscious  of preserving the beauty of the natural  world  around us.

excess  [ˈekˌses] n.过度；过分行为；过量  strive [straɪv] v.努力；奋斗
habitat [ˈhæbɪˌtæt] n.聚集处 栖息地  
investment  [ɪnˈvestmənt]     n.投资；投资额；投资物；值得买的东西    网络投入；投资学；投资理财
flora [ˈflɔrə] n.植物区系；植物群   fauna [ˈfɔnə] 动物群
present [ˈprezənt] n.目前；现在； extinction [ɪkˈstɪŋkʃ(ə)n] n.绝种
preserve [prɪˈzɜrv] v.保留；保持  



** Lesson 36  Vancouver: Asia's   Newest city

 [vænˈkuːvə(r)
  What ?  Wait a  minute! Did I read that right? I thought   Vancouver was  in Canada,  not   in Asia.  Why  is the title of this  article "Vancouver: Asia's  Newest City" ?
  Relax, everyone.  Yes ,Vancouver is still in Canada, North America's largest country, not in Asia. Over the past  twenty years, however, Asians from China, Taiwan, Hong Kong, Thailand, the Philippines, and other  countries across the ocean have flocked into this  largest city on Canada's  Pacific coast. By some accounts, as many as 30% of  households in Vancouver speak Mandarin  or Cantonese, making  the Chinese  there   the largest minority by far.  Just  what  is the attraction of   this  English-speaking city, however?

flock [flɑk] v.聚集；群集；蜂入  minority  [maɪˈnɔrəti] n.少数民族；少数人
Chinese descent 华裔 heritage

04:21
  A visit to  Vancouver quickly reveals her  charms. Situated on the ocean and possessing a fine, deep-water port, British Columbia's largest city faces Vancouver Island  to the west  and mountains to the east and north. Most of the city is relatively new,having been rebuilt after  a great fire in 1886.(here)The   completion of the Panama Canal in 1915 during  World War I helped spur growth all along the West  Coast of North America, as products from  the western  states  of the United States and  the western provinces of Canada could be profitably shipped to Europe. By  the  1930s Vancouver  had become  Canada's  third-largest city, a position it maintains today. Lumber from  the extensive forested areas within  the province, minerals, seafood, and assorted industries, including  tourism,give the million-plus  residents of  metropolitan Vancouver  a  high  standard of living.

reveal [rɪˈvil]展现  charm  [tʃɑrm] n.风韵； 魅力 situated   [ˈsɪtʃuˌeɪtɪd]  adj.位于
possess  [pəˈzes]  v.占有；具有(能力,性质等)；使占有；(在身心方面)克制      网络拥有；占有的；所有
completion [kəmˈpliʃ(ə)n] n.完成；结束   canal  [kəˈnæl]n.管；运河
relatively [ˈrelətɪvli]  adv.相当程度上；相当地 maintain [meɪnˈteɪn] v.维护；保持；
spur [spɜr]  v.刺激；激励 profitably  [ˈprɑːfɪtəbli] adv. 有利地；有益地
Lumber  木材 林,  extensive  [ɪkˈstensɪv]  adj.广阔的
mineral [ˈmɪn(ə)rəl] n.矿物；   tourism  [ˈtʊˌrɪzəm]n.旅游业
resident  [ˈrezɪdənt] n.居民；  metropolitan  [ˌmetrəˈpɑlɪt(ə)n]  adj.大城市的

10:00
   The  city itself  is comfortable  and  attractive. A large central park called Stanley Park  includes a  zoo,  gardens, arboretum, and aquarium! The  University  of  British Columbia and Simon Fraser University  are located in the greater Vancouver area,  as are many small  and quaint farming and fishing villages within  a  few  hours' drive.  Scenic, unpolluted, and prosperous:  who  could ask for anything more ?

  Certainly not  the Chinese.  Although limited immigration  from the Far East began as early as the 19th century, it was not until  the 1970s  that  immigration to both Canada and the United States began  to increase significantly. By the  1980s, the steady stream had become a flood. Today,  Vancouver's  Chinatown is said to be North America's  second largest. Given  the large  numbers of Chinese living in the much larger cities  of New  York, Toronto, Los Angeles, and San Francisco, that   represents astronomical  growth.

attractive  [əˈtræktɪv] adj.迷人的  arboretum  [ˌɑrbəˈritəm] n.  植物园
aquarium  [əˈkweriəm] n.水族馆    quaint  [kweɪnt] adj.稀奇古怪的；古雅的
unpolluted  [ˌʌnpə'lu:tɪd] adj.未被污染的  prosperous [ˈprɑsp(ə)rəs] adj.繁荣的


limited  [ˈlɪmɪtəd] adj.有限的；    given [ˈɡɪv(ə)n] prep.鉴于；考虑到  adj.已经安排好的；规定的；指定的
immigration  [ˌɪmɪˈɡreɪʃ(ə)n] n.移居；   increase  [ɪnˈkris] n.增加
significantly  [sɪɡˈnɪfɪkəntli] adv.极大地；显著地  steady  [ˈstedi] v.稳住；使稳
stream  [strim]  n.流；溪；小河  flood  [flʌd] n.洪水；水灾     v.淹没；泛滥
represent  [ˌreprɪˈzent] v.表示；代表；象征   astronomical  好像在哪学过 [ˌæstrəˈnɑmɪk(ə)l] adj.天文学的；天文的 庞大


  Vancouver's  Chinatown is located  within walking distance  of the downtown area, as are most  Chinatowns in North America. Here one  can find both traditional  Chinese herbal stores and fresh food markets as well as small retail and service businesses. From mid-May to September, Friday  to Sunday evenings from 6:30 to 11:30, both  Chinese  and "foreign" visitors to this area might mistake themselves as  begin in Shanghai or Hong Kong. For  daytime visitors, the Dr. Sun Yat-Sen Classical Chinese Gardents is must, offering  beautifully landscaped  floral gardens. The  nearby Chinese  Cultural Center conducts walking  tours of the historic district and even a   slide show  revealing the historic  development of the  area.

herbal  [ˈɜrb(ə)l] adj.药草的；香草的 草药 retail   [ˈriteɪl]     v.零售
landscape  [ˈlændˌskeɪp] n.【地】景观；景致；  floral  [ˈflɔrəl] adj.绘有花的 花卉
conduct  [ˈkɑnˌdʌkt]  n.行为；经营  historic   [hiˈstɒrik]       adj.历史上有名的；具有历史价值的；历史性的
district  [ˈdɪstrɪkt] n.区；地区；  revealing   [rɪˈviːlɪŋ] adj.透露真情的
  
  Of course,Vancouver has much more  to offer its residents and out-of-town and overseas visitors, Though -- or  perhaps  because -- it lacks the manic energy of East Coast cities of North America or those of modern Asia, Vancouver continues  to attract new residents with its serenne, safe, and , well, sane lifestyle.

resident  [ˈrezɪdənt] n.居民；驻    lack  [læk] v.缺乏； 
manic [ˈmænɪk] adj.狂热的；兴   serene   [səˈrin]     v.宁静；
sane [seɪn] adj.精神健全的；神志正常的；明智的；理智的

**  Lesson 37   The Germanic Languages
   Most people have heard  of the Tower  of Babel   story in the Bible.  According to  this story, long ago all  people  spoke  the same  language.  Later, however, they  were  punished by  speaking a  great  number of different  tongues. Today , there  are literally thousands of   different languages(defined as mutually  unintelligible tongues)  around the world, though  many   are related to  one another.  Indeed, the two  largest language  families, the Indo-European(the language family with the  largest number of speakers)  and  Sino-Tibetan(containing the Chinese languages, Thai, Vietnamese, and TIbetan)  include  hundreds  of languages with over  half the world's  population.
   
 [dʒərˈmænɪk] adj.德国的；德国人的；日耳曼语（族）的 n.日耳曼语(系
bible  [ˈbaɪb(ə)l]n.《圣经》  literally   [ˈlɪt(ə)rəli] adv.字面上；确实地

  Because  there  are so many languages within the above  two   super-categories of language families, linguists have further divided these linguistically rich and geographically  diverse families into sub-groups,  one of  which , the Germanic  language  group , has the second-largest number of speakers(Chinese being first). Within this  group of over 500,000,000 speakers is the world's foremost international language,   English, foremost in  terms of  its geographic spread and  number  of second-language users. German, spoken  by just over 100,000,000 people, is one of the world's  ten-largest  languages  in  terms of population . As  English  and German  speakers constitute the majorities in several  of the world's  most economically, militarily, and technologically developed  countries, it is important   to be familiar with this  particular language grouping.

category  [ˈkætəɡəri] n.类别 分类；种类；范畴  linguist [ˈlɪŋɡwɪst]n.通晓数国语言的人；语言学家
divide  [dɪˈvaɪd]v.分割；除；分隔；分配  diverse [daɪˈvɜrs]  [daɪˈvɜː(r)s]     adj.不同的；相异的
foremost  [ˈfɔrˌmoʊst] adv.第一 adj.最重要的    geographic  [ˌdʒiəˈɡræfɪk] adj.地理学的
spread  [spred] n.传播；蔓延  term  [tɜrm] n.条款；说法；价钱；措辞
v.把…称为网络术语；条件
in terms of    na.依…；从…方面；用…特有的字眼   根据；在...方面；按照
particular  [pərˈtɪkjələr]  adj.讲究；挑剔；专指的；不寻常的 n.（正式记下的）细节；详

08:35 好像对不上   中间我是少了一段了么 
 14：10
Take for example the two largest languages with this  group, English and German.  The word  Haus in German is  house   in  English , with nearly the same pronunciation. Some  names  of German family members are instantly   recognizable to  English  mother, brothe, and uncle (all German nouns are capitalized in print). Other  German family members are easily learned:  Vater, Schwester, and Tante for  the English  father, sister, and aunt. Thus, those who know Englihs and want to study German find  their  first year  of learning vocabulary to be  relatively easy. The  same is true, of course,  for those  who want  to learn Dutch  or Danish from an  English  or German background; these  many similarities are due  to the  single   common parent  language of all the  the  Germanic tongues, even though this "grandfather"    language no longer exists.

noun  [naʊn] n.【语】名词；名词代

  Speakers and writers of the Germanic languages account  for  a great  deal of the world's output  in everything from economics to literature to  military to science and technology. Hardly an  aspect of modern life does not benefit from the contributions made by those using these languages, as  in  the Internet, Hollywood entertainment, Dutch(Phillips) and  Scandinavian  consumer goods  design(Ericsson,maker  of cellular  phones,is a  Swedish company, as are Volvo and Saab) ,  and even  the Noble prizes(awarded by  both Norwegian and Swedish institutes). More than  one-third of the world's  economic production originates in these  countries, too.

literature  [ˈlɪt(ə)rəˌtʃʊr]  n.文学；文学作品；资料     网络文献；文艺；著作
benefit  [ˈbenəfɪt] n.益处；优势；成效   


  For any  speaker of a language outside the Germanic language group  preparing to  choose a useful second language for the future, English  is probably the best bet. German, too,  is very  useful  in the fields of medicine, economics, military, and science and technology.  Being able  to communicate with  others in this  far-reaching linguistic group  will  offer the user immeasurable benefits.

  bet  [bet] n.打赌；赌注；预计；估计 the best bet 喜从天降；最好的选择
far-reaching  [ˌfɑr ˈritʃɪŋ] adj.影响深远的；广泛  immeasurable 美 [ɪˈmeʒərəb(ə)l]  adj.不可估量的；无限的
  benefit [ˈbenəfɪt]     n.益处；优势  linguistic group  语言族群
field  [fild] n.田野；田地；油田；  方面 

感觉到这个时候可以很多可以看得明白了 

**    Lesson 38   Learning How  to  Apologize
  What are the  hardest words  to pronounce in English?  It seems  that "I'm sorry"  are  the two  most difficult words  for  most people  to say.  Perhaps  this difficulty  lies  in the so-called "losing  of face"; when a  person   apologize, he lowers  himself  before  another. Yet  no one is  perfect;everyone makes mistakes.  After  making  a mistake, people should apologize  to set things   straight with  others.
  
apologize  [əˈpɒləˌdʒaɪz]  v.道歉；表示歉  pronounce  [prəˈnaʊns]v.发音；读（音）；
straight [streɪt]  adj.直的；直筒型（非紧身）的；准的；正

  Two  phrases in English  often  confuse  no-native users of this  languages. These  phrases are "I'm sorry"  and "Excuse me."  The latter is used to  ask for information, as  in "Excuse me,(but) do you have the time?"  or "Excuse me,(but) can you  tell me  whether there is a post  office near hear?" "Excuse me " is also used when   it is  necessary to disturb other,  as  when  one person interrupts  two others  speaking: "Excuse me for interrupting,(but) I have  to  leave now.  Another example of  the proper usage of this phrase is when, as s  stranger, you want to point something  out of  benefit  to  someone, as  in "Excuse me,(but) I believe  you dropped something  out of your wallet."  Another  common  instance of  using "Excuse me"  is  in  crowded elevators, stores, or lines when a  person needs to get through  or get out, "Excuse me,(but) this is my floor" is a very handy phrase to learn when in crowded elevators, In all these  cases, "Pardon me" may also  be used; however, it is  more often used  in British than in America  English .
  
  phrase  [freɪz]  n.成语；用语；习惯  perhaps 可能 
disturb  [dɪˈstɜrb] v.打扰；干扰；   interrupt [ˌɪntəˈrʌpt] v.中断；打扰
proper [ˈprɑpər]     adv.非常；好好地；完完全全地；彻底地     adj.正确的；恰当
benefit  [ˈbenəfɪt]     n.益处；优势；成效；福利费（政府对失业者、病人等提供的补助金）
floor  [flɔr] n.地板；地面；楼层  handy  [ˈhændi]adj.便利；手巧；易使用的；容易做的     网络方便的；手边的；便利的
 complain  except 

   When  is "I'm sorry"  used?   For more serious incidents.  Stepping on someone's  toes on  a crowded bus, though not intentional, should elicit an  immediate "I'm sorry."  Bumping  into someone even on a crowded street where it is  difficult  not to also  calls for "I'm sorry."  Careless or late work in school or in the office requires out  apology to teachers, colleagues, or employers. Being late for meetings or dates needs both  an apology and often  either  a reason for the  tardiness or  an  explanation  of what   course of action will  be taken  to eliminate  any future  possibility    of recurrence.  No  one   likes to be  wronged, intentionally or otherwise. Saying "I'm  sorry" can go a  long way  towards rectifying  an awkward situation.

   Even  more  importantly, saying "I'm sorry"  is  necessary  when  intentional  harm has  been done. The  borrowing of an item  without first  informing the owner -- who  later  discovers  the "theft" - can be quite embarrassing. A  simple  but sincere "I'm sorry" might repair the damage done. Careless comments  or  insults which
   offend others may  be ameliorated with that simple phrase, though sincerity in voice and gesture make all the difference. Similarly, young  lovers, often exasperated in  unrequited love, may purposefully hurt each other, only later  to profoundly regret what they  had done.  At  these times, a  heartfelt "I'm sorry"  may redress the pain of the on inflicted by   love's arrows. Even better, "Please forgive me" may be used, as it is considered a stronger  expression of remorse.

incident [ˈɪnsɪdənt] 事变；偶发事件  toe  [toʊ]n.脚趾；(
intentional [ɪnˈtenʃən(ə)l] adj.故意的；有意的   elicit [ɪˈlɪsɪt] v.引出；探出；诱出
tardiness ['tɑrdɪnəs] n.拖拉；缓慢；迟缓 迟到；迟延；  explanation  [ˌekspləˈneɪʃ(ə)n]    n.解释；说明
eliminate [ɪˈlɪməˌnet]v.消除；消灭；   future  [ˈfjutʃər] n.未来
ecurrence  [rɪˈkʌrəns]n.复发；重现 rectify  [ˈrektəˌfaɪ]v.矫正；校正

intentional  [ɪnˈtenʃən(ə)l]     adj.故意的；有意的；存心  theft [θeft] n.偷窃
borrowing [ˈbɔroʊɪŋ] n.借贷；借款；贷款；借用的言语（或思想等）     v.“borrow”的现在分词
embarrassing  [ɪmˈberəsɪŋ]  adj.使人害羞的（或难堪的、惭愧的）；使显得愚蠢的（或不诚实的等）  v.“embarrass”的现在分词 网络令人尴尬的
sincere [sɪnˈsɪr] adj.真诚的；诚挚  damage [ˈdæmɪdʒ]v.损害；伤害；破坏；毁坏
comment  [ˈkɑˌment]n.评论；评语； 批评  insult  [ɪnˈsʌlt] n.侮辱；袭击；
offend  [əˈfend] v.冒犯；得罪；犯罪 ameliorate  [əˈmiliəˌreɪt]v.改良；变好
sincerity [sɪnˈserəti] n.诚意；真挚  gesture [ˈdʒestʃər]n.手势；表示；动作；举动
exasperated  [ɪɡˈzæspəˌreɪtəd] adj.恼火的v.exasperate的过去式和过去分词  unrequited [ˌʌnrɪˈkwaɪtəd]adj.没有回报的；单方面的；单相思的
purposefully /ˈpɝː.pəs.fəl.i/adv.有意 profoundly [prə'faʊndli] adv.深刻地；极大地；严重地；完全地网络深深地；深刻的；深切地
regret [rɪˈɡret]n.遗憾；懊悔 后悔 heartfelt  [ˈhɑrtˌfelt] adj.衷心的；真诚的
redress  [rɪˈdres] v.纠正；矫正；改正  inflict [ɪnˈflɪkt]v.加以(打击等)；使受(痛
arrow  [ˈæroʊ]n.箭；箭状物  remorse  [rɪˈmɔrs]     n.懊悔；非常遗憾；自责

    Learning  to apologize  in another language does not excuse speakers from practicing the same good  manners in  their mother tongue.  So many people  lament the coldness  of  modern society; human relationships  have  been worn thin from  constant urban  pressures. Part of this  problem seems to  be that people  no longer use such simple words as "please," " thank you,"   and "I'm sorry."  They  cost nothing, but can  bring a wealth  of pleasure or relief to those who  hear them. They require little  effort, yet these few syllables  can enliven  someone   else's day. So, why not use them whenever possible?


excuse 借口 lament  [ləˈment] n.挽歌；哀诗；悼辞v.对…感到悲痛；痛惜
constant [ˈkɑnstənt] n.常数；常量adj.连续发生的；不断的  urban   [ˈɜrbən]adj.城市的；都市
wealth  [welθ] n.财富；财产；富裕；丰富
relief [rɪˈlif]n.浮雕；解脱；轻松；消除 网络救济；减轻；解除
effort  [ˈefərt] n.努力；尽力；成就；气力 努力的成果；尝试；工作量 昨天右边的人刚刚问这个单词
syllable美 [ˈsɪləb(ə)l] n.音节；一言半字 enliven  [ɪnˈlaɪv(ə)n]  v.使更有生气（或活力）  else's 别人的

