*  English  conversation on the go 
** Lesson 20  twenty Checking into  Hotel


Good morning.  I'm  Mr. jack Wu. I have a reservation for a  suite.

oh, yes, Mr. Wu. Please  


background

gorgeous 好看 
wait
minute 

It's very easy to overspend when you  have a  credit card.

***   word and other


    
** Lesson 21 Changing Money
Monday June 06 2022

*** 课文
I  would  like to cash  these  traveler's checks,please

How much do you have ?

Five hundred US dollars.

Do you have any identification?

Will my passport do ?

That's be fine .

****  Dialogue B

What's the exchange rate for US dollars,please?

Which  currency do you want to change  your  money into?
 Hong Kong dollars ,please
It's 7.89 Hong Kong  dollars to  1 US dollar.
Can you  change US$100?
How do you  want your money?
Seven  hundreds,eight tens and the rest  is change, please
No problem.


***  word and other
bounce 跳票

go (went) to bed later 晚睡
sleep later  起床好晚

** Lesson 23  At  the Airport I 
   wednesday June eighth 08th  2022
***   Dialogue A
  This is the arrival lounge.
  I know, Where is the  departure lounge?
  Come .Follow  me.
  There! The check-in counters are over  there.
  Don't we have to go pay the airport tax first?
  No. We pay it after we check in.

***  Dialogu B
   Good morning . May I have your passport ,please?
   Here you are.
   Smoking or non-smoking.
   Non-smoking.
   Aisle  or window seat?
   Window seat,please.
   Do you have any luggage to check in ?
   Yes. This is my carry-on  luggage and I'll check in  these two suitcase.

   

   
*** Vocabulary
  section 区域 

  check in 美:  
    v.〈美〉报到；(旅馆)登记
    网络入住；办理登记手续；签到


    Laundromat    美: [ˈlɔndrəˌmæt] 英: [ˈlɔːndrəmæt]
    n.自动洗衣店；〈美〉自动洗衣店的招牌
    网络自助洗衣店；自助式洗衣店；自助洗衣房

    词形：

    
** Lesson 30 Emergency Calls

*** Dialogue A
 This is an emergency call! Get an ambulance here right away.
 Where are you calling from ?
 I'm at No.10 Zhong Hua Road.
 What's the  problem?
 A taxt ran into a truck.

 
***  Dialogue B
 Fire! There's a fire. Come quick!
 Where's the fire ?
 At No.7 Kaifeng Street.
 What's burning?
 My restaurant is on fire.
 How did it happen?
 A gas tank exploded.
 We'll be right there!

 
***  vocabulary

 calmly 冷静


 
** Lesson  28  Going to the  Movies
  Thursday June ninth 09th  2022

  
*** Dialogue  A
 Can I have two tickets for Titanic, please?
 For what time ?
 The 9:30 p.m. show , please.
 I'm afraid it's full. How about the midnight show ?
 That'll be fine. Can I have our seats up front, please ?
 Sure , That'll be twenty dollars,please.

 
***  Dialogue B
 Where were you last night?
 I was at the movies . I went to see titanic.
 How was it ?
 It was fantastic.  The  main actor  and actress really did a good job.
  Sounds like it  was a very goog movie.
  You can say that again.

  
***  vocabulary

main    美: [meɪn] 英: [meɪn]
n.总管；电源；（建筑物的）污水总管道；水源
adj.主要的；最重要的


14 

 wonderful 

    
* Basic English: Book1

**  Lesson 45   What a Nightmare!
    Tuesday  June seventh  2022 

    
*** Reading 
    Jeff had a  terrible day. He missed the train to work. Moreover, he had to wait a long time for the next train . As a matter of fact , he waited for two hours. To make matters worse , he left his briefcase on the train.  As a resul, he had to  go to the police station. Poor Jeff never got to  work  that day. What a  nightmare!

    
***   Vocabulary & idioms  word and 
terrific ==great 
take a  bus to work everyday
 I bike to work everyday 

 hurry up 快点


He sing very well .
Beats me! (难倒我了,问题是单数 所以 加了s) 

naughty 调皮

On the train 空间大可直立
In the taxi , 空间不大不可直立

He is stupid ,  to make matters worse,he don's study  


He don't study . as a result , he failed the exam.



* Intermediate English: Book 1

** Lesson 1  Rome  Wasn't Built in a day
  English is an internatinal languages. Therefore,  it is necessary for us  to learn it. It can be  rewarding  or just a  waster of time. It's up to you. It depends on  how you study it. Here are some tips about  learning  English.
   First , don't  be afraid ot make  mistakes.  You  will  learn  from them. Second, you must not be shy. Be thick-skinned and  speak up! Finally , you must  be patient. Remeber,"Rome wasn,t built in a day."
 
**  Lesson 2  How  to imporove your english 
Mack is talking  to his friends  don.
 Hi, Don, How are you doing in your English class?
 Not so well, I'm afraid.
 What's the problem?
 I'm  not improving . Tell me, how come your English is so good ?
Well,uh... I have an American girlfriend.
 Aha!That's it. Now I know what to do.(He runs off)
Hey, come back! I was just kidding!

** Lesson 3  The city of Song 
  Listening to music  is the favorite pastime  of many people all over the world . This is especially true  for people  living in Vienna, the city of song. Being  the home  of Mozart, this  city is the brithplace  of classical music  and the waltz.
  Music fills the  air in Vienna. Going  to public concerts is often  free  charge. And  don't forget, Vienna is also home to the world  famous Vienna Boys' Choir. No wonder people say Austra is  always alive with the sound of music.


**  Lesson 4   He Who  hesitates is lost 
Are you having  a  good time,Daisy?
Are you kidding? I'm having  the time of my life. I love the  concerts.
Concert going  is fantastic but what  else  can we do?
Biking along  the banks of the river Danuber could  be fun.
It sounds  like a great  idea!
Let's do it then.
You're right . As they say,"He who hesitates is lost."



*  Advanced English
** Lesson 1

advance美: [ədˈvæns]  d 音 弱化 
n.进展；进步；提高；预付款
v.提前；进步；促进；预付
adj.先遣队；预先的；事先的；先头

despite    美: [dɪˈspaɪt] 
    prep.尽管；即使；尽管（自己）不愿意
    n.怨恨；恶意；轻蔑；侮辱
    网络不管；不顾；任凭

 glaring    美: [ˈɡlerɪŋ] 
adj.显眼的；明显的；易见的；刺眼的
v.“glare”的现在分词


property    美: [ˈprɑpərti] 
    n.属性；财产；财产权；【戏】道具
    网络性质；特性；性能

    词形：
    properties



This river abound in fish.


**  Lesson 5  The animals  around the world: Chameleons
  Every few months this  program will feature an  animal which  has caught the eye of the world's public to become a  favorite or "hot"  animal. In  the first  of this  unusual series, we  will  look at the chameleon, one of  nature's strangest creatures.
  Perhaps no  other  group  of animals  has  caught mankind's  imagination like reptiles.  Among the several subclasses(or "orders" in biology) of  reptiles are snakes and lizards, turtles and tortoises ,crocodiles  and alligators, and the  tuatara, a marine lizard in  New Zealand. The dinosaurs, too, belonged to  the calss o f reptiles. Was it a  snake,lizard, or crocodile that caught the fancy of some Chinese in times gone by  to  create dragon? A perrennial  theme ,reptiles have  been featured over the past ten years in box-office hits and bombs alike as dinosaurs( JURASSIC Park and The lost world), corcodiles, and snakes(Anaconda). Though not nearly as large as these mighty reptiles,, the lowly chameleon nonetheless has amazed  countless generations   with  its special talents and skills.
  What is a  chameleon? Its  unusual name fits  this unusual animal perfectly, for  pit translates from  the ancient Greek as "lion on the ground." This is unexpected, since chameleons spend most  of their time in trees, and as  for looking  like a lion, a chameleon  looks like a .. well, a chameleon! No  other animal in Nature's  zoo looks quite as  bizarre as  they do. Where do they live? True  chameleons  are found  only in the tropical  forests  and jungles of the Old world, and  nearly half of its   species live on the African  island  of Madagascar.
  What's so special about  the chameleon? Plenty! From  its  tongue to its  tail the chameleon  offers a  storehouse  of specialites. The tongue  of this modern-day  dinosaur look-alike  can be  extended more than twice the  length  of its  body. This  type of tongue . also present in frogs and toads, is called an extensile tongue. The eyes of hte chameleon  are even  more remakable. Its eyes are turreted and can be moved independently  so that it can view two  different object simultaneously! This comes in especially handy as it is tree-dwelling. The chameleon can  keep  one eye on its prey  and the  other on its footing. Its head  is often  helmet-shaped, and some  species have horn-like structures  growing  out of  this  scaly helmet.

prey on sth  sth的猎物  
  
live on    na.以…为主食；靠…生活；继续活着；靠［吃］…生活
    网络以……为主食；靠……为生；以…为食
Most Chinese live on rice. 

dwelling    美: [ˈdwelɪŋ] n.住宅；住所；公寓 v.“dwell”的现在分词

storehouse    美: [ˈstɔrˌhaʊs]     n.仓库；货栈；（信息或知识等的）宝库     网络库房；储藏室；栈房

multitude    美: [ˈmʌltɪˌtud] n.众多；群众；人群；大量

An umbrella aAlways come in handy in the summer. 
伞在夏天总是派得上用场。

perfectly    美: [ˈpɜrfɪk(t)li] adv.非常；十分；完美地；完全地
ancient    美: [ˈeɪnʃənt] 英: [ˈeɪnʃ(ə)nt]adj.古代的；古老的；很老的n.（尤指古埃及、古希腊和罗马的）古代人
tropical    美: [ˈtrɑpɪk(ə)l]  adj.热带的；来自热带的；产于热带的
prey    美: [preɪ] n.猎物；受害者；受骗者 v.折磨；掠夺；捕食 (on, upon)；损害 (on, upon)
helmet     美: [ˈhelmət] n.头盔；防护帽v.给…戴上头盔
shaped    美: [ʃeɪpt]     adj.具有（或呈）…形状的
    v.“shape”的过去分词和过去式    网络成形；成形的；成型的 horn    美: [hɔrn] 英: [hɔː(r)n]
n.角质；（羊、牛等动物的）角；（乐器）号；（车辆的）喇叭
v.在…上装角；把…做成角状；(动物)用角抵触[刺挑]；把(牛角)截去
adj.角制的    

structure     美: [ˈstrʌktʃər]     n.结构；组织；石理；【心】(直接经验中显现的)结构性
    网络语言结构；结构体；建筑

    scaly    美: [ˈskeɪli]     adj.有鳞屑的；有皮屑的    网络有鳞的；鳞状；鳞状的

  The feet and   tail  of the chameleon are also special. Both  are prehensile; that is , they  are both perfectly adapted  to their sylvan  environment. The toes  of the chameleon's feet are bunched into  inside and outside groups of two  or  three to enable this reptile to grasp  tree  branches tightly. The chameleon can  thus  climb extraordinarily well  while  using its  tail  to  grab  objects for  further balance.

adapted    美: [əˈdæptəd] adj.适合…的；改编成…的
v.适应不同环境[情况等]；“

toe    美: [toʊ] n.脚趾；(鞋,袜等的)尖；蹄尖；蹄铁尖
v.用脚趾踩；装[修补]鞋尖[袜尖等]；用脚尖踢；【高】用棒尖打(球)
grasp    美: [ɡræsp] v.理解；领会；抓紧；明白
n.领会；紧握；控制；紧抓
thus    美: [ðʌs]     adv.因此；这样；如此；从而      网络因而；于是；由此

further    美: [ˈfɜrðər] adv.进一步；此外；更远；而且 v.促进；增进
    
  The above   inventory of  natural selection specializations would  be remarkable enough, but what  really  separates the  chameleon from its fellow reptiles is  the  fact  that  its  scales contain  the ability to change color. Though many people think  the chameleon  can change its color  at will  and that it can blend into any color, these are misconceptions. In fact,chameleons can  blend  into many  natural colors and even  patterns, but they cannot  do this at will. Instead, this  happens naturally according to  temperature, emotional state of the animal, and the triggering of certain  hormones within its body.

  pattern    美: [ˈpætərn]     n.模式；方式；格局；型
    v.给…加花样；照图样做；仿造；形成图案    网络模型；型态；句型
certain    美: [ˈsɜrt(ə)n] 
    adj.肯定；确定；确信；无疑    pron.（不提及人或事物的名称时用）某些    网络确定的；肯定的；一定的    

misconception    美: [ˌmɪskənˈsepʃ(ə)n] n.误解
    trigger    美: [ˈtrɪɡər] v.触发；扳动扳机射击；松开扳柄n.(枪上的)扳机；【物】触发器；【
    
  It is hard to imagine an animal more interesting than  the chemeleon,with  its weird appearance and special abilities. We should  always  remember,however, that these animals require their native habitat to flourish in, not zoos or individuals'  terrariums. If you want your grandchildren to see  this  gift  of nature, do not collect  it as s pet. These natural treasures evolved over millions of years without  mankind's help;they will continue to survive better if left alone.

  individual    美: [ˌɪndɪˈvɪdʒuəl] 
n.独立单位；〈俚〉人 adj.单一的；特有的；个体

appearance    美: [əˈpɪrəns] n.外观；外表；出现；外

habitat 美: [ˈhæbɪˌtæt] n.生境；栖息地；居住地；

treasure    美: [ˈtreʒər] 
n.宝藏；财富；宝贝；宝贵的人材 v.珍藏；珍重；爱护；热爱
  
*** vocabulary 
reptile美: [ˈreptɪl] n.爬行动物 adj.匍匐的；爬虫类的；卑劣的


perennial.多年生植物 永久的

SERIES      美: [ˈSꞮRIZ]     N.串联；一系列；连续；接连    网络级数；丛书；序列

program    美: [ˈPRƏƱˌꞬRÆM]     n.节目；计划；【计】程序；课程(表)    v.编写程序；为…制定计划；使…按安排进行

irresistible    美: [ˌɪrɪˈzɪstəb(ə)l] 
    adj.不可遏止的；无法抵制的；极诱人的；忍不住想要的
    网络不可抵抗的；不可抗拒的；无法抗拒

anaconda    美: [ˌænəˈkɑndə] n.水蚺（南美洲蟒蛇）      redhat 安装程序

nonetheless    美: [ˌnʌnðəˈles] adv.尽管如此

perfectly    美: [ˈpɜrfɪk(t)li] adv.非常；十分；完美地；完全地

ancient    美: [ˈeɪnʃənt] 英: [ˈeɪnʃ(ə)nt]adj.古代的；古老的；很老的n.（尤指古埃及、古希腊和罗马的）古代人

tropical    美: [ˈtrɑpɪk(ə)l]  adj.热带的；来自热带的；产于热带的
prey    美: [preɪ] n.猎物；受害者；受骗者 v.折磨；掠夺；捕食 (on, upon)；损害 (on, upon)

helmet     美: [ˈhelmət] n.头盔；防护帽v.给…戴上头盔

shaped    美: [ʃeɪpt]     adj.具有（或呈）…形状的
    v.“shape”的过去分词和过去式
    网络成形；成形的；成型的

horn    美: [hɔrn] 英: [hɔː(r)n]
n.角质；（羊、牛等动物的）角；（乐器）号；（车辆的）喇叭
v.在…上装角；把…做成角状；(动物)用角抵触[刺挑]；把(牛角)截去
adj.角制的    

**  Lesson 6 Table Manners in Anglo-America  June 28 2022 
  "Oh ,no Here I am at an American family's home at the dinner table.There are all kinks of plates, saucers,cups,and silverware at my place. Which  should I use  for which food? Should I sit down  first or wait  for the host to invite me? Should I have brought a gift? Someone please tell me what to do!"

manner    美: [ˈmænər]     n.礼貌；举止；习惯；方法
anglo-america     网络 英美；盎格鲁美洲；美利坚
spoon    美: [spun] n.勺；匙；调羹 v.用勺舀
silverware      美: [ˈsɪlvərˌwer]  n.银器；餐具（刀、叉和匙）；（体育比赛中的）银杯

  Have you ever been in or had a nightmare about  this  situation? Don't worry! This article will help  steer you through the rocks and reefs of Anglo-American table manners so  that if you are ever abroad in Canada or the United States, or  at someone's home from  one of  those countries,you will  feel right at home.

steer    美: [stɪr]     v.引导；控制；操纵；驾驶（船、汽车等）      n.建议；劝告；忠告；阉公牛     网络掌舵；掌握方向
ever     美: [ˈevər]     adv.曾经；从来；总是；到底  网络永远；究竟；在任何时候    

  It is  important to distinguish   what kind of  occasion you will be attending before you plan for a pleasant  evening. Most  Anglo-Americas enjoy  entertaining  at home, but they don't  enjoy stuffy, formal dinners. They invite their friendss over  for a fun evening , not as a  test of one's knowledge of cultural  traditions. If, however, you are  invited to a formal affair, such as a so-calld "sit-down" dinner,you may  want to know  in advance some basic rules of "black tie" etiquette.

occasion     美: [əˈkeɪʒ(ə)n] n.时机；理由；原因；某次 v.使发生；造成；导致  场合
entertain     美: [ˌentərˈteɪn]      v.娱乐；款待；使有兴趣；使快乐 网络招待；使娱乐；怀抱
attend      美: [əˈtend] v.参加；出席；注意
invite    美: [ˈɪnˌvaɪt]  v.邀请；要求；招致（尤指坏事） n.邀请；请柬
affair     美: [əˈfer] n.事件；事情；风流韵事；公共事务    网络绯闻；私通；恋爱事件

  The first thing  to remember when  attending a dinner at a Western home is  that you  are the guest and that you are a foreigner. No one will invite you if he does  not really want you  enter his "castle," so you can be sure that you are wanted. Additionally, as you do not come from the same country or culture as you host , he or she or they will surely  be aware  of this, and will  be very forgiving if you unintentionally do or  say  something  which  would  otherwise offend them. Keeping these  two simple tips  in mind  should greatly ease your concern about  being present at a dinner in someone  else's  home.

  wanted     美: [ˈwɑntəd]  adj.受通缉的  v.“want”的过去式和过去分词
  additionally     美: [əˈdɪʃ(ə)nəli] adv.另外 
  unintentionally  美 [ˌʌnɪnˈtenʃənəli]    adv. 无意地；非故意地；非存心地
aware     美: [əˈwer] adj.意识到；知道；明白；发现
forgiving     美: [fərˈɡɪvɪŋ]  adj.宽宏大量的；宽容的 v.“forgive”的现在分词
otherwise     美: [ˈʌðərˌwaɪz] adv.否则；不然；另；除此以外conj.否则
offend     美: [əˈfend]  v.冒犯；得罪；犯罪；令人不适
concern      美: [kənˈsɜrn]   n.关心；忧虑；公司；企业 v.涉及；影响；牵涉；与…有关
present      美: [ˈprezənt]   n.目前；现在；礼物；礼品

  Before arriving at your  host's home. you may want to make sure of three things. First, be a few minutes late,say,about  five to ten  minutes if possible. Never be early, as the host may not have everythng prepared yet. Nor should you  be more than  20 minutes late.Your host may begin to worry about  whether  you are able to attend  the dinner or not. Next , as to whether  to bring a gift, in most informal gatherings,  it is not necessary. If you like, you can bring some fruit or sweets, or , especially  if there is a hostess, some flowers. These are thoughtful, cheerful gifts sure to  please. Do not  bring alcoholic  beverages  unless you are  sure  of your host's  or hostess's preferences in drinks. Above  all , do not spend a lot of money, and never give money. As we say in English ,"it's the thought that counts."
Finally, wear  comfortable clothing. One  can overdress as well as appear sloppy.  For a special occasion  or religious holiday, such as a retirement  party or  Christmas, a tie and jacket would be suitalbe  for the gentlemen and dress  or sweater and skirt for the ladies.

gathering      美: [ˈɡæð(ə)rɪŋ] n.收集；采集；聚会；聚集 v.“gather”的现在分词  
hostess      美: [ˈhoʊstəs]  n.女主人；女房东；（夜总会的）女招待；（电视或广播节目的）女主持人
beverage     美: [ˈbev(ə)rɪdʒ]      n.饮料；餐费；〈英方〉筵宴     网络饮品；饮料类；饮料篇
appear     美: [əˈpɪr]  v.出现；显现；呈现；出版 linkv.似乎；显得；看来
sloppy adj. 草率的；粗心的；泥泞的；肥大的；稀薄的
religious     美: [rəˈlɪdʒəs]   n.修女 adj.宗教信仰的；宗教的；笃信宗教的；虔诚的
retirement     美: [rɪˈtaɪrmənt]  n.退休；退休生活；退职；退休年龄

  For  more formal affairs, you will  probably be told what to wear, such as "formal dress requested," etc. A tie  and jacket or tuxedo for the gents and an evening gown for the ladies would  be in order here. If you are  unsure what  to wear, you can  always ask the  host. Gifts are seldom appropriate for these affairs, unless for a wedding reception, at which  gifts are more customary than cash.
  
  Your  host in  his home will usually motion  you where to sit. At formal gatherings, name cards are sometimes  provided, or  you will  be told  where to sit.Do not be alarmed by a great deal of cutlery simply start from the outside and work your way in.  Formal affairs often have several courses  of food with the appropriate cutlery for each dish. There is no harm in  checking with your neighbor to see what implement he is using. After all, "When in Rome, do as  the Romans do." It is  customary to ask others to pass dishes to you  for self-serving; at a formal dinner party, there is  usually catering(service). Again, do not hesitate to  ask others  for information or advice. They are usually  pleased to help you.

provided      美: [prəˈvaɪdəd]    conj.如果；假如；在…条件下  adj.预备好的；由…供给的 v.“provide”的过去分词和过去式  
cutlery      美: [ˈkʌtləri]   n.餐具（刀、叉和匙）；刀具
appropriate      美: [əˈproʊpriˌeɪt]   v.拨款；剽窃；挪用；〈正式〉非法占有 adj.恰当的
course     美: [kɔː(r)s]  n.过程；球场；【教】课程；航线 v.流动；(某种感觉)突然
implement     美: [ˈɪmpləmənt]  v.实施；执行；贯彻；使生效 n.工具 器 具
hesitate      美: [ˈhezɪˌteɪt]  v.（对某事）犹豫；顾虑；疑虑
advice     美: [ədˈvaɪs]  n.建议；意见；忠告；劝告
again     美: [əˈɡen]  adv.再一次；又一次；再说；复原

 The most important  piece of advice is this: enjoy  yourself. No host enjoys seeing nervous or fearful guests who are struggling to "do the right thing" at his home  or expensive  formal dinner party. Watch  other or ask for  their advice, and join in the conversation  and  good times as  best as you can . if you  do , after the first  such evening out,you will certainly look forward to the next!

 fearful    美: [ˈfɪrf(ə)l]      adj.担心；担忧；忧虑；可怕的    网络害怕的；担心的；吓人的
struggle     美: [ˈstrʌɡ(ə)l]  v.挣扎；斗争；努力奋斗；争取 n.努力；斗争；奋斗；抗争
conversation     美: [ˌkɑnvərˈseɪʃ(ə)n]      n.（非正式）交谈     网络谈话；会话；对话
 
**  Lesson 7 The  Delights of  South Island
  One  of the odder coincidences  of physical  geography  is the  fact that  there are two  double islands, roughly the same   size, positioned at each other's antipodes , or farthest-distant point. The  islands of English  and Ireland in the Northern   hemisphere  and the islands of North Island  and South Island in the Southern Hemisphere  are just such a coincidence. The first two islands comprise the United Kingdom and the Republic of Ireland (or Eire) ,and the second two islands comprise New Zealand. Among these  four islands, there can be no  doubt that South Island  is the least polluted and most spectacularly scenic of them all.
  
  delight     美: [dɪˈlaɪt]  v.快乐；使欢喜 n.欢喜；爱好的事物；嗜好
  odd     美: [ɑd]  adj.奇怪的；怪异的；反常的；（某方面）怪异的 n.【高】让转弱的对手从
  physical 美 [ˈfɪzɪk(ə)l] n.体检；体格检查  自然 adj.身体的；肉体的；躯体的；客观存在的
  geography 美 [dʒiˈɑɡrəfi]  .地理环境；地形；地势；地理（学） 
oughly  美 [ˈrʌfli]  adv.大约；大致；差不多；粗暴地
position  美 [pəˈzɪʃ(ə)n]  n.位置；地位；职位；立场
antipodes  美 [æn'tɪpədi:z]  n.【化】对映体；恰恰相反的事物；【无线】对蹠点
hemisphere  美 [ˈhemɪˌsfɪr]  n.（地球的）半球；
comprise  美 [kəmˈpraɪz]  v.组成；构成；包括；包含
spectacularly 壮观地；引人注目地；引人入胜地
scenic 美 [ˈsinɪk]  n.风景影片；实景电影；风景照片[图片] adj.风景优美的；舞台布景
among  美 [əˈmʌŋ]  prep.在…中；周围是；在（其）中；…之一

  There is much competition to  make such  a claim. The  island of  English , politically  constituting English, Scotland,and  Wales  of the United Kingdom , is dotted with country  villages set alongside rivers and lakes.  There are not very  tall but nonetheless rugged mountains in the north, and endless miles of rocky coastline  that  seem mystical. Ireland , too, is a paradise of greenery, with far fewer  people than  populous    English and even  more quaint villages scattered  among its low-lying hills and forever green fields. North Island in New Zealand sports a  balmy climate and the beaches to make use of it;  One beach alone is more that 150 kilometers long, and with  relatively few people on its shores, on cant  pretend  one is  at the very end of the earth. Volcanoes,large lakes, and quickly flowing rivers traverse  the land. Given the beauty of these three islands, what makes South  Island so special ?

  climate  美 [ˈklaɪmət] n.气候；地带；水土；(社会思想等的)趋势 
  claim   [kleɪm] n.索赔；宣称；声明；断言  夺走生命
politically  美 [pəˈlɪtɪkli]  adv.政治上
  dot
美 [dɑt]  n.点；圆点；句点；【乐】附点  v.点缀；打点于；用点线表示；〈俚
paradise  美 [ˈperəˌdaɪs] n.天堂；伊甸园；天国；极乐
populous  美 [ˈpɑpjələs]  adj.人口众多的；人口密集的

nonetheless     美: [ˌnʌnðəˈles] adv.尽管如此

  Plenty. For  those who like mountains, South Island is  sure to please.Mt. Cook at 3.764 meters is its highest peak, with  16 others above 3,000 meters. Naturally, many local and foreign mountain climbers come here for  the  challenge of  these Southern Alps. In addition, there is an  extensive glacier system, endless forests,and innumerable lakes throughout this highland area. Some  of the world's best mountain  scenery is available within the 500-kilometer long chain of  the Southern Alps.

scenery      美: [ˈsin(ə)ri]       n.风景；景色；风光；舞台布景      网络景物；景观；景致

  Perhaps you prefer the  sea? South  Island is not only an  island, but many  tiny islets can be found  off its coastline.Great deep-sea fishing, scuba diving, and snorkeling can be had, though the waters here are cooler than those of North Island, (Remember, in the Southern Hemisphere, as we go north, it gets warmer.) As  fewer people  live on South Island than on North Island, those who crave  solitude and pristine beaches will be  amazed at their  luck here. With almost no heavy industry on SOuth Island,the  air, water, and land are all free of  pollution. The local seafood is therefore clean, plentiful, and never-ending.

  Of course, South Island is not for everyone. For those who  need busy, crowded,noisy, and polluted cities.this Southern outpost will surely disappoint. For those who enjoy pressure  and stress, South Island will leave them empty-handed. And for those who would rather stay at home or in an  office in  front of a computer screen or in the thumping,smoke-filled dance floors of discos, some of the world's best natural scenery will never  entice them away. For the rest of us, though,South Island is the world's best-kept secret.If Nature's paradise sounds alluring, make a point of visiting South Island.


  Do healthful climates interest you ? South Island is the place to be. Its temperate  climate sees little snow except in the highlands and mountains areas. Like Ireland and English, there are no extremes of temperature, either. Summers are warm, not hot, and winters are brisk ranther than  freezing. The fresh air is sometimes humid from the abundant rainfall  of this area.Every season invite the nature lover to get out  and be active in the countryside.



  


  中级的可以抄一下  初级直接读就好了呢 

  
** Lesson 8 Ireland's Contribution  to English
   Nearly  everyone knows  that countries such as the United Kingdom, the United States of America,Canada, Australia, and New Zealand  are primary English-speaking countries;  that is  English  is the mother tongue used in these countries. What  is less well known  is that English is also  the mother tongue in countries such as the Republic of Ireland (officially called Eire), Barbados,Jamaica,Trinidad, and Guyana. Among these latter few, the Irish have made contributions to the English  language in both  its lexicon and literature  which  can be considered second to none.
latter     美: [ˈlætər]   后者 刚刚提到
lexicon     美: [ˈleksɪˌkɑn]  n.字典；（某语言或学科、某人或群体使用的）全部词汇
   literature     美: [ˈlɪt(ə)rəˌtʃʊr]  n.文学；文学作品；资料
consider      美: [kənˈsɪdər]  v.认为；觉得；以为；顾及

  Virtually every  aspect of  English  literature has been graced by the  writings  of  the Irish. This  face  is all the more amazing because Ireland is a relatively  small country,with  never more than  four million people throughout its long history. Yea  many great "English" writers were indeed  born and often  raised in Ireland, though many, too, emigrated to the united Kingdom  at some point in their lives.Among these pillars of  English literature were Jonathan Swift,William Butler Yeats,James Joyce, Samuel Beckett, Oscar WIde,George Bernard Shaw,and  Edmund Burke. Many other lesser-known figures have punctuated English literature as well. These men's contributions to the English  language and to Western thought in general are immeasurable. A review of two of these writers' major works will reveal why.

  virtually      美: [ˈvɜrtʃuəli]   adv.几乎；实际上；事实上；虚拟
  aspect     美: [ˈæspekt]  n.方面；层面；外观；方位
literature     美: [ˈlɪt(ə)rəˌtʃʊr]  n.文学；文学作品；资料
grace     美: [ɡreɪs] n.恩典；优雅；宽限期；优美 v.装饰；为…增色；为…锦上添花；使荣耀
million    美: [ˈmɪljən]  num.一百万；大量 n.无数；百万元；百万(镑,

09:00  第三 段

emigrate    美: [ˈemɪˌɡreɪt] v.移居(外国)；迁出；使移居
pillar     美: [ˈpɪlər]  n.柱；栋梁；纪念柱；(柱)墩 v.用柱子装饰[支持]；成为…的栋梁
punctuate      美: [ˈpʌŋktʃuˌeɪt]     v.不时打断；给…加标点符号    网络强调；加标点于；不时介入
immeasurable      美: [ɪˈmeʒərəb(ə)l]   adj.不可估量的；无限的；无穷的
review    美: [rɪˈvju] n.回顾；述评；审查；评论
reveal     美: [rɪˈvil]  v.透露；揭示；显示；展示 n.启示；【建】窗侧壁；门侧；(汽车的)窗框
satire 讽刺


**  Lesson 9 Why  Is Basketball  So Popular?   Tuesday  July twnety-sixth 2022
    Soccer and baseball  have  more fans, but no other sport has increased in popularity so quickly  over the pass 30 years than  has basketball. What accounts for the sudden meteoric rise in a sport which, after all, is  played best by people who are  unusually tall ? The secret to  basketball's  success lies is three particular sources: the celebrities  in  game; commercial sponsorship of  those players and the game itself; and  the mushrooming of crowded, urban environments around the world.

increase     美: [ɪnˈkris]  n.增加；增长；增多  v.增加；增多

meteoric      美: [ˌmitiˈɔrɪk]       adj.迅速成功的；流星的

lie       美: [laɪ]   n.谎言；休息；虚伪；诺言  v.躺；在于；欺骗；位于
particular      美: [pərˈtɪkjələr]   adj.讲究；挑剔；专指的；不寻常的  n.（正式记下的）细节

celebrity       美: [səˈlebrəti]       n.名人；名声     网络名流；社会名流；明星

commercial     美: [kəˈmɜrʃ(ə)l]  adj.贸易的；商业的；赢利的；以获利为目的的
n.（电台或电视播放的）广告
sponsorship      美: [ˈspɑnsərʃɪp]   n.资助；主办；赞助款；倡议

    mushroom  美: [ˈmʌʃˌrum]   n.蘑菇；蘑菇状物；蘑菇状烟云；〈口〉(女用)蘑菇形草帽 v.迅速增长；采集蘑菇；子弹打扁成蘑菇形；〈美〉(火)猛然的扩大

  All sports have their heroes. Current, baseball has Mark McGuire and  Sammy Sosa, the home  runhitting kings, Tennis has Martina Hingus and  Pete Sampras,the darlings of the courts, Soccer has players so popular that  they are mobbed by fans wherever they appear, especially in Europe and South America. ONly basketball, however,has celebrities who have caught the attention of the world like no others. Michael JORDAN is popular even  after having officially retired from  the game that there is talk of  his running for public  office in the United States. Dennis Rodman,the muscular,tattooed, and much ballyhooed player formerly of  the Chicago Bulls, make headlines whenever he pulls  another of his crazy but fun-loving publicity stunts. Former players like Larry Byrd and Magic Johnson continue to command respect for their personal integrity and unparalleled sportsmanship. Basketball shoes, T-shirts, and  even movies are make with  these basketball superstar icons. No other sport figures can compete with their popular recognition and appeal.

  be mobbed by 包围

  retired     美: [rɪˈtaɪrd]       adj.已退休的；已退职的      v.“retire”的过去分词和过去式
  run for 竞选
muscular      美: [ˈmʌskjələr]       adj.肌肉的；强壮的；肌肉发达的     网络强健的；肌的
  ballyhoo      美: [ˌbæliˈhu]   n.喧闹；大吹大擂的广告[文章,演说] v.大肆宣传；为…大吹大擂

  Is this international superstar status solely due to  these men's  talents and contributions? In no small part,of course,it is , but  other leading athletes with equally commendable skills or who have performed  attention-grabbing antics rarely  reach the stratospheric level of stardom that basketball players  enjoy. This special privilege is due  to a concerted effort by the players behind  the basketball players, that is, the basketball leagues' owners and sponsors.

solely     美: [ˈsoʊlli]  adv.只；仅；唯；单独地
  privilege     美: [ˈprɪvəlɪdʒ]      n.荣幸；荣耀；特殊利益；优惠待遇      v.给予特权；特别优待     网络权限；特别待遇；特免
  

  Basketball has  always  been a distant third in sports rankings in the United Status behind baseball and American  football. Basketball league owners and managers wanted to change this traditional perception of the immutability of these statistics and in the 1960s began a concerted effort to make basketball the game  of choice by hand-picking more colorful as well as professional players and  by making alliances with  the commercial sponsors of athletic equipment. By the 1970s, basketball team recognition in the U.S. had soared, with dedicated fans in the millions. Teams like the Los Angeles Lakers, the Chicago Bulls, and the Boston Celtics had become household names. Players like  Magic Johnson  and Michael Jordan were  worth milions of dollars in commercial advertising  spots for  athletic equipment  manufacturers, a trend which  continues to this  day. Today , basketball is  a billion-dollar business.

  distant     美: [ˈdɪstənt]   adj.遥远的；远处的；久远的；不相似的   athletic     美: [æθˈletɪk]  adj.健壮的；体育运动的；田径运动的
ranking     美: [ˈræŋkɪŋ]      adj.第一流的；首席的；高级的；干部的     n.顺序；【统】秩评定     v.“rank”的现在分词
    网络排行榜；排名资料；当地前十名的排名
league     美: [liɡ]   n.联赛；联盟；协会；种类  v.(使)结盟；(使)联合[团结]；一鼻
perception     美: [pərˈsepʃən]      n.感知；知觉；看法；洞察力     网络感觉；认知；理解
immutability     美: [ɪˌmjutə'bɪlətɪ]   n.不变性
statistics     美: [stə'tɪstɪks]  n.统计学；统计数字[资料]；
alliance     美: [əˈlaɪəns]  n.联盟；联姻；同盟条约；同盟者
commercial     美: [kəˈmɜrʃ(ə)l]   adj.贸易的；商业的；赢利
manufacturers, 制造商 
  equipment 英 [ɪˈkwɪpmənt] 美 [ɪˈkwɪpmənt] CET4 TEM4 
    n. 设备，用具；（对某人或某物的）装备
trend     美: [trend]  n.趋势；动向；趋向；动态    
    
   No amount of advertising,  however, can account for  the number of fans who  not only double as spectators  but as  players themselves. Basketball
   courts, whether in schools,parks, or abandoned  city lots, have sprouted throughout the urban landscape.  A child is never far from a basketball ball and hoop.  With land becoming more expensive in ever more crowded cities, city governments  are fat more likely  to construct basketball courts than  baseball diamonds or soccer fields. As basketball equipment is minimal and inexpensive , it is no wonder that the game  has become more and more popular around the world.

   spectator     美: [ˈspekˌteɪtər]  n.旁观者；(看比赛等的)

   What young boy doesn't dream of becoming as tall  as a  basketball player, or at least of having  as much money or fame? Basketball's quick pace and dynamic plays are in contrast to the much slower moves in baseball or even   in much of soccer and American football. This dynamism is part of the pulse of our times, and so long as  we live in  a fast-chang-ing  world,basketball  and  its players will continue to appeal to sports lovers around the wold. 

   dynamic     美: [daɪˈnæmɪk]  
    n.动力；动力学；推动变化的力量
    adj.充满活力的；活跃的；精力充沛的；不断变化的
    网络动态；动态的；动力的

    pulse    美: [pʌls]  n.脉冲；脉搏；脉率；强劲的音乐节拍 v.搏动；跳动；震动；洋溢着

    appeal     美: [əˈpil]  n.上诉；吸引力；申诉；魅力
    




    
**  Lesson  12  The Louvre:  The  World's  Best  Museum?
   Paris, City of Light, and  of art.  A playland for  lovers and a painter's  dream. What  better  place  to situate the louvre, considered by many to be the world's  best  museum of  art? What  makes this museum so worthy fo that honor?

situate  [ˈsɪtʃuˌeɪt] v.使位于；使坐落于

  The  museum building,  or, more properly, the  complex of buildings  themselves is a good place to start. As  with  most Western  and a few Asian and   South  American museums, large  palaces or other  traditional architecture are used   to house   museums  of  art and of natural science.  In  the case   of the Louvre,  officially known as   Paris du  Louvre (the Palace of the Louvre),  the main building used  today was  formerly the fortress of King  Philip Augustus in the 12th  century. Not until 1546 did  King Francis I begin  to redesign and add onto  the fortress. Subsequent kings  did   the same, especially  during the 17th century  with  major additions by  Louis XIII and Louis XIV.  Not only did  these  kings and their ministers add to the buildings , they also  stocked within their rooms  the finest art  that  money could buy.   After the  French  Revolution, the  Palais du Louvre  was   opened to the public. In the early 19th  century, both Napoleon and Napoleon III  added to both the structures and the collections . A controversial see-through glass  pyramid-shaped structure  was added by the architect I.m.Pet in the 1980s. As a  consequence of centuries  of continuous construction and amassing of art  treasures, today the Louvre offers a  world-class  collection   of both  French and foreign  art.

  properly  [ˈprɑpərli] adv.正确地；适当地；恰当地；得体地
  complex [ˈkɑmˌpleks]n.情结；（类型相似的）建筑群；相关联的一组事物；不正常的精神状态
    adj.复杂的；
formerly  [ˈfɔrmərli]  adv.以前；从前；原来；过去 finest 最好的
redesign [ˌri:dɪ'zaɪn]n.新设计 v.重新设计 fortress  [ˈfɔrtrəs]  n.堡垒；要塞；城堡；设防的地方
subsequent  [ˈsʌbsɪkwənt] adj.随后的 后来的  minister [ˈmɪnɪstə(r)] n.部长；牧师；公使
stock  [stɒk] n.库存；储备 revolution  [ˌrevəˈluʃ(ə)n]     n.革命；旋转；巨
controversial  [ˌkɑntrəˈvɜrʃ(ə)l]adj.引起争论的；有争议的
pyramid-shaped  金字塔   pyramid  [ˈpɪrəmɪd]     n.锥体；（古埃及的）金字塔；
architect  [ˈɑrkɪˌtekt]  n.建筑师；设计师；缔造者；创造者 网络架构师；                                                                              
consequence  [ˈkɑnsəkwəns] n.后果；结果  continuous  [kənˈtɪnjuːəs] adj.连续的；不间断的；
construction  [kənˈstrʌkʃ(ə)n] n.施工；建筑  amass  [əˈmæs] v.积聚；收集
treasure  [ˈtreʒər] n.宝藏；财富

The  outer shell of a museum, however, no matter  how artistic or historic, cannot  alone make a museum truly great. The inner collections are of course of  paramount interest to both the   art researcher and art lover alike.  The Lovre does  not disappoint them.  Three  of the West's premier works of art are here: the statues VIctory of Samothrece and Venus de Milo accompany Leonardo DA vinci's  most famous painting,  the Mona Lisa. These alone  attract art devotees from around  the world, but far more awaits them. The French  painting  collection is ,  not  surprisingly, unsurpassed. Other major  painting collections include works from the middle ages and Renaissance. The treasures of the French royalty are on display here, too, such as their bronzes, miniatures, potery, tapestries, jewelry, and furniture. Greek, Roman, Egyptian , and Mesopotamian  antiquities as well as early Christian   artifacts  are also  considered important  collections. This  clearly is not a  museum to be seen in one morning!

shell [ʃel] n.壳；炮弹； inner [ˈɪnər]n.内部；射中接近靶心部分的一发adj.里面的
course  [kɔː(r)s]     adv.〈口〉当然n.过程；航向；球场；【教】课程
paramount [ˈperəˌmaʊnt] n.最高元首；首长adj.至为重要的；首要的  premier [prɪˈmɪr] n.总理；地区总理  adj.首要的；
devotee  [ˌdevoʊˈti] n.热爱者 surprisingly  [sərˈpraɪzɪŋli] adv.令人惊讶地
unsurpassed  [ˌʌnsərˈpæst] adj.无比的；卓绝的  renaissance  [rɪˈneɪsəns] n.文艺复兴（欧洲 1
royalty  [ˈrɔɪəlti]n.版税；王室成员  皇室；皇族   bronze [brɑnz] n.青铜；青铜制品
miniature  [ˈmɪnɪtʃər] (象牙等上的)微小画像   pottery  [ˈpɑtəri] n.陶器
tapestry [ˈtæpəstri] n.壁毡；家具的绣[织]花罩毯 挂毯；挂毡；壁毯
jewelry  美 [ˈdʒuːəlri]      n.珠宝；首  furniture [ˈfɜrnɪtʃər] n.（可移动的）家具
antiquity  [ænˈtɪkwəti]n.古物；古

 Finaly, the site of the museum complex  contributes to  the  mysigue of the Louvre. Paris has long been considered one of the world's most charming cities, with  its endless winding  streets amidst spectacular royal and religious architecture. The  fortress built by King Philip Auguestus was situated on  the right bank of the Seine, overlooking -- at that  time -- splendid  bucolic scenery. Today  this prime location is within walking   distance of many major Parisian tourist attractions, like the Cathedral of Notre Dame, the Royal Palace, and the National Library. One  could  easily spend a whold week touring the heart of  Paris centered around the Louvre.

attraction  [əˈtrækʃ(ə)n] n.吸引；魅力；引人注意的东西 景点
contribute  [ˈkɑntrɪˌbjut] 有助于 v.投稿；捐款；  mystique [mɪˈstik] n.神秘性
spectacular  [spekˈtækjələr] adj.壮观的；壮丽的 fortress [ˈfɔrtrəs]n.堡垒；要塞；城堡
tourist  [ˈtʊrɪst] n.游客  attraction  [əˈtrækʃ(ə)n] 景点n.吸引；魅力

  Taken  altogether, then , the Louvre holds its own as on  of the best museums -- if not  the best --among the dozens  of major  and internationally famous art museums  around the world. Its many and varied buildings, the unparalleled collection of prestigious works of art, and the delightful site of the grounds  overlooking France's  most famous river all contribute to make the Palais duLouvre a must-see  attraction for the serious art connoisseur and art museum-goer alike. Meet you at the Louvre . 

unparalleled  [ʌnˈpɛrəˌlɛld] adj.无可匹敌的  prestigious  [preˈstidʒəs] adj.有威望的；声誉高的

dozen  [ˈdʌz(ə)n] n.若干；十二个 varied  [ˈverid] adj.各种各样的；形形色色的；不相同的；变化的     v.“vary”的过去式和过去分词
delightful  [dɪˈlaɪtfəl] adj.使人快乐的；令人愉快的；宜人的
  
** Lesson 15  Webcames: Electronics Tools  or  the End of Privacy?
  What are webcams? The  word webcam  is a  compound word formed from  two abbreviations, "web" from the World Wide Web and "cam" from camera. Webcams are cameras which  are situated at various places and  linked to the  World Wide Web. They allow 24-hour viewing of a wide array of places and activities around the world. They can be as educational as they  are fascinating, entertaining as they are eye-opening. Not everyone raves about this new technology,   however. Some cite sinister implications in a technology which  can unobtrusively spy  on our goings-on without our permission.  Others note  that with  rapid increases in telephotography and the science of acoustics, the days of privacy are numbered. Anyone can mount a webcam with  a telephoto  lens and microphone, aim it at his neighbors's liveing room or bedroom, and the broadcast one's "private" life to the  whole world. A script for the next sci-fi film, or a  current reality? Are these doomsayers overreacting, or is  their  charge legitimate ?

  compound     美: [ˈkɑmˌpaʊnd]      v.合成；加重；构成；使…复杂化      adj.混合；混合的；复合物合成的；〔医〕哆开性     n.大院；混合物；合成物；合成词
  form     美: [fɔrm]  v.形成；成立；产生；编成 n.型；组织；格式；形态
  abbreviation     美: [əˌbriviˈeɪʃ(ə)n]  n.缩写；【数学】约分；【音乐】略号；〔数〕约分
  situated     美: [ˈsɪtʃuˌeɪtɪd]      adj.位于；坐落在；处于…状况；处境…      v.“situate”的过去分词和过去式      网络位于…的；坐落在…的；处于…境地的
  ascinate      美: [ˈfæsɪˌneɪt]   adj.极有吸引力的；迷人的
various     美: [ˈveriəs]      adj.各种不同的；各种各样的；具有多种特征的；多姿多彩的     网络各种的；多方面的；多样的
a wide array of  各式各样的
entertaining      美: [ˌentərˈteɪnɪŋ]   n.招待 adj.有趣的；娱乐的；使人愉快的
activity      美: [ækˈtɪvəti]   n.活动；活性；动作；功能
rave     美: [reɪv]      n.(人,风,浪的)狂闹；怒吼；狂闹声；锐舞      v.(狂人一般)说胡话；咆哮；发狂似地讲；狂喜 (about of)      网络锐舞聚会；锐舞聚尾；拉沃
cite     美: [saɪt]   v.引用；援引；引述；提及（原因） n.引文
sinister     美: [ˈsɪnɪstər]      adj.邪恶的；险恶的；不祥的；有凶兆的      网络阴险的；凶恶的
implication      美: [ˌɪmplɪˈkeɪʃ(ə)n]      n.含意；推断；牵连；【数】蕴涵      网络含义；影响；启示
unobtrusively       adv.谦虚谨慎地；小心翼翼地      网络不引人注目地；悄悄地；不引人注意地
rapid     美: [ˈræpɪd]     n.急流；滩；湍流      adj.瞬间的；短时间内发生的；迅速的；快速的      网络快的；急速
legitimate      美: [ləˈdʒɪtəmət]       adj.正当合理的；合情合理的；合法的；法律认可的  v.使合法；认为正当；认为正统；承认(庶子)为嫡出      网络正当的；正统的；正当性
doomsayer     美: [ˈdumseɪər]      n.预言灾难者      网络凶事预示者；凶事预言者；末日论者     词形：      doomsayers

04:00
     On one side of the  debate are those who point  out that webacms offer more  real  advantages thant supposed disadvantages. They  cite numerous websitres on which peole  can  observe the world around  them for educational or aesthetic purposes. Today one  can watch 


debate     美: [diˈbeɪt]  n.辩论；争论；考虑  v.辩论；争论；考虑     


**  Lesson 16 When  Is the Best Time ?
  Some  poeple  go so far as to say that  time does not really exist; It is  all in the mind, they claim.Others note that according to  astrophysicists, time  really does exist; It is  inseparable from space,coexisting in what  these scientists call the "time-space continuum" . No  matter which view you may hold, time is of  relative importance in  different  cultures. However, when  traveling ,doing  business, or studying  in a German or English-speaking country, it is a good idea to consider time to be of the utmost importance. 
claim  美 [kleɪm]  n.索赔；宣称；声明；断言
  astrophysicist      美: [ˌæstroʊˈfɪzɪsɪst]   n.天体物理学
coexist     美: [ˌkoʊɪɡˈzɪst]   v.共存；（尤指）和平共处  网络同时存在；并存；同时
relative      美: [ˈrelətɪv]   n.亲属；亲戚；同类事物
utmost     美: [ˈʌtˌmoʊst]   n.极限；最大限度；最大量；最大可能 adj.最大的；极度的
consider      美: [kənˈsɪdər]   v.认为；觉得；以为；顾及

  Many people have noted that  the  germans  and English  are both  methodical and well-organized.  Naturally, not everyone among  them is ,but these peoples do seem to  share a penchant for orderliness  and  punctuality.      Clocks and time have played a great  part  in defining the character  of the  Anglo-Saxons. The  geographic use of time  began during the British  Empire  with  the world  divided by latitude and longitude , with  zero  degrees longitude    running through the observatory at Greenwich , in London. According to  the British of that day, the world began its  timekeeping from London  and  it still does.  Time is of paramount importance  to these  Europeans and their overseas descendants. If you are visiting or  staying  in these  countries, here  are a  few pieces of advice to help you make the transition to a time-centered civilization.

  methodical 美: [məˈθɑdɪk(ə)l] adj.有条理的；有条不紊的；办事有条不紊的   网络有方法的；有系统的；井然的
  well-organized  美[wel ˈɔːrɡənaɪzd]  有序的; 很有条理的
  naturally 美 [ˈnætʃ(ə)rəli]  adv.自然地
penchant      美: [ˈpenʃənt]   n.爱好；嗜爱
orderliness  美 ['ɔrdəlɪnəs] n.整洁；整齐；有秩序；守纪律 网络条理；井然有序；秩序井然
punctuality n.严守时间；敏捷
character 美: [ˈkerəktər] n.特征；特性；性格；角色 v.刻；画；表现…的特性；使具有特性 网络字符；人物；品格
define  美 [dɪˈfaɪn] v.限定；(弄)明确；定界说
latitude  美 [ˈlætəˌtud]  n.纬度；纬度地区；选择（做
longitude    美: [ˈlɑndʒɪˌtud]   n.经度
observatory 美 [əbˈzɜrvəˌtɔri]  n.天文台；气象
paramount  美 [ˈperəˌmaʊnt] n.最高；有最高权力的人；元首；首长  adj.至为重要的；首要的；至高无上的；至尊的
descendant 美 [dɪˈsendənt]  n.后代；弟子；从某一来源派生的东西；派生物

   As  you  probably already know, being  punctual --to the minute --- is held  in  high esteem among them. Time is the most valuable commodity  one can have,  according to the  doctrine of  the time worshippers . We are not given very much  of it whilst on this planet, and we should do our best to utilize it efficiently  each and every day, the say . Wasting  others' time by forcing them  to wait is a sign of disorganized living, a sort of admission  to being low-class. It is also  seem  as an insult to  those kept waiting, as if to say, "Your time is not that  important."To them, this attitude borders on sin itself! In business, being late even only a few times may make the difference between  your  getting a promotion and being kept "in your place." For social dates, it is a sign of slovenliness at best, rejection of those waiting at worst. In school, never  burst open the door of the lecture hall to announce, "I'm sorry  I'm late,sir" as is the custom in many countries, The  double crime of being tardy and interrupting the proceedings which  began on time  occurs, with a likely prejudiced  and  unfavorable grade awaiting  the hapless student.

   punctual 准时
esteem      美: [ɪˈstim]       v.尊重；敬重；认为；把…看作  n.尊重；敬重；好评      网络尊敬；自尊；尊严
commodity 美 [kəˈmɑdəti]  n.商品；产品；货物；商品经济
doctrine  美 [ˈdɑktrɪn]  n.学说；教义；信条；主义  网络教条；原则；教旨
worshipper  美 ['wɜrʃɪpər]  n.崇拜上帝（或神）的人；做礼拜的人；敬神者；拜神者
utilize  美 [ˈjut(ə)lˌaɪz]  v.利用；运用；使用；应用
sign  美 [saɪn]  v.签名；签署；叹息；预示
disorganized  美 [dɪsˈɒrɡəˌnaɪzd] adj.无组织的；混乱的
insult  美 [ɪnˈsʌlt]  n.侮辱；辱骂；冒犯  v.侮辱；辱骂；冒犯
attitude  美 [ˈætɪˌtud] n.态度；看法；我行我素的做派；姿势 网络心态；姿态；工作态度
sin 美 [sɪn] n.罪；罪行；过失；过错  abbr.正弦
slovenliness  网络马虎；不修边幅
rejection  美 [rɪˈdʒekʃ(ə)n] n.拒绝；否决；抛弃；拒斥
lecture  美 [ˈlektʃər]  n.演讲；训斥  v.讲课；训斥
tardy 美 [ˈtɑrdi] adj.行动缓慢的；拖拉的；迟缓的；迟到的 网络迟延的；迟的
interrupt 美 [ˌɪntəˈrʌpt] v.打扰；中断；打搅；打断(别人的话等)  网络打断他人；插入他人谈话；插话
proceedings  美 [prəˈsidɪŋz]  n.程序；学报；事项；会刊 网络会议录；论文集；诉讼
occur  美 [əˈkɜr]  v.出现；存在；想起；(事
prejudiced 美 [ˈpredʒədɪst]  adj.有偏见的；带成见的；偏爱的；偏心的
unfavorable  美 [ʌnˈfeɪv(ə)rəb(ə)l]adj.令人不快的；逆的；不适宜的；不顺利的
网络不利的；不宜的；不理想的
# 这段完成得不错 Friday July  twenty-ninth  2022 
  Of course, being  late can sometimes not be avoided , as in unexpected traffic jams,home  emergencies, or having   been  given the wrong  information of date or place. When  these  all-too-human  mishaps do occur ,  it is important to explain the reason for being late. It is also a good idea, Of course ,to apologize for the useless waiting and to assure  the other or  others that it  will never happen again. In this age of cell phones, every effort shoudl be made to call ahead if tardiness of more than ten minutes is unavoidable, especially for business or professional  appointments or important  dates. The  last phrase anyone  wants to hear is a frosty "You could  have called."  That  is the prelude to a ruined evening.
mishap     美: [ˈmɪsˌhæp]   n.灾难  
occur     美: [əˈkɜr]  v.发生；出现；存在于；出现在 
avoid     美: [əˈvɔɪd]      v.避免；防止；【法】使无效；撤销
assure      美: [əˈʃʊr]  v.确保；使确信；向…保证；弄清
tardiness     美: ['tɑrdɪnəs]  n.拖拉；缓慢；迟缓
anyone     美: [ˈeniˌwʌn]   pron.（用于否定句、疑问句，也用于 if 或 whether 之后，或紧接 prevent、forbid、avoid 等动词，代替 someone）任何人
phrase      美: [freɪz]   n.短语；词组；习语；成语
v.措辞；分乐节（尤指
frosty      美: [ˈfrɔsti]       adj.严寒的；霜冻的；结霜的；冷淡的
prelude     美: [ˈpreljud]  n.前奏；前奏曲；序幕；先声
ruined 美: [ˈruɪnd] adj.毁坏的；严重受损的  v.“ruin”的过去分词和过去式

 Not   everything  begins  exactly on time, even in  Anglo-Saxon  culture. Many  casual  parties are "open" concerning time; the party begins when you get  there. The  same  is generally true  of backyard  barbecues and picnics. Dinner parties, on the other hand , are obviously planned around a meal time; one should make every effort  to arrive  (not before). A friendly "Drop by this evening" invites common sense to interpret: too earyly during the evening may  embarrass the host who is  eating dinner, while too late  may disturb  those who  prefer  going  to bed earyl. A call first to make sure is never out of line .

 disturb      美: [dɪˈstɜrb]  v.打扰；干扰；弄乱；妨碍

  Remember that  time is relative in importance to people  within a  culture just  as it is between  cultures.  Nothing  is more importance than  human relations. If you  commit the "crime" of  being late  with Anglo-Germanic friends, simply apologize. Few  people intentionally keep  others waiting, after all. Remember, too, that, "When in Rome,do as the Romans do."  In  English-and German-speaking lands, this means "Time waits for no man!"

  relative     美: [ˈrelətɪv]  n.亲属；亲戚；同类事物  adj.相比较而言的；比较的；相对的；相关联的
  commit      美: [kəˈmɪt]       v.承诺；自杀；做出（错事）；犯（罪）      网络提交；提交完成；干


  
**  Lesson 18  Hot Animals Around the  World: The Koala
   Why  are all those people  standing in line in the hot sun at the zoo? Maybe  the zoo just opened  a koala exhibit. With  the survival rate  of native  Australian koalas on the rise,  more  and more  zoos around the world are  adding  a  "koala house" or  "koala exhibit" to their roster of special animals. And   the people  keep coming,  whether merely to catch a glimpse of one or , if really lucky  at zoos  which permit it , to hold  and be photographed with one.

   rate  [reɪt] n.率；速度；比率；价格
exhibit  US [ɪɡˈzɪbɪt] v.展览；表现；展出.  roster US [ˈrɑstər] n.值勤名单；候选名单
merely  US [ˈmɪrli]  adv.仅仅；只不过. glimpse US [ɡlɪmps] v.瞥见；〔诗〕闪现
permit US [pərˈmɪt] v.允许；准许；使有可能 n.许可证
luck n  
   
   Why   are  koalas among the  most beloved fo all animals ? At  times   referred to as " koala bear," this Australian marsupial is not a bear at all. It is one of  few tailless mammals besides  the apes and man. Yet  apes are not often  considered cuddly; indeed, they  are often  feared for being either too large or too naughty. This  Australian  real-life teddy  bear, instead , is the best of all worlds: it is quiet , soft, neither too large nor too small (adults are usually 65 to  80 cm. long), and really  cuddly! With  its  soft fur, leathery nose, rounded  ears, and big eyes, most people  seem  to melt when near one.  Its  disposition is  perfect  for   children and adults alike;   it rarely makes a fuss, even   when  being held. (Try  that  with  a baby  tiger!) No  wonder the  lines  to see,  hold, or just  touch the  koalas are always among the longest at zoos.

   refer to  v.查阅；提到 Web把某人叫作；被提及
   marsupial US [mɑrˈsupiəl] adj.【动】有袋(目)的；袋(状)的    n.有袋类动物（如袋鼠和树袋熊）
   mammal US [ˈmæm(ə)l] n.哺乳纲动物
ape     US: [eɪp]   n.猿；类人猿. cuddly US: [ˈkʌdli]   adj.令人想拥抱的；柔软而
fur US: [fɜr]      n.舌苔；毛皮衣服；（动物浓厚的）软毛；（动物的）毛皮
    v.用毛皮护覆；使生水垢；除去(锅上的)水垢；使长舌苔      Web皮草；皮毛；毛发
    leathery  [ˈleðəri]  adj.坚韧粗糙的；似皮革的 Web皮革味；皮似的；皮般强韧
melt  [melt] v.融化；（使）软化 . adult  [ˈædʌlt]  n.成人；长成体  adj.成年的；成熟的
fuss     US: [fʌs]  n.大惊小怪；无谓的激动（或忧虑
disposition     US: [ˌdɪspəˈzɪʃ(ə)n]      n.倾向；性情；性格；布置

   One  reason zoos  today  are able  to keep  koalas  is the  rise in the koala population  in its native habitat, the eucalyptus forests of  southeastern  Australia. This  nation, famous for its  unique  fauna and flora, is now allowing applications for the professional export of its  protected species to overseas  zoological gardens. Once   hunted for its fur, this arboreal leaf-eater  is today  protected by stringent laws and is making a slow but steady comeback.  Indeed , everything about   the koala  seems slow. It sleeps more than  12 hours a day(often  much more), eats only choice leaves from  eucalyptus(which  can now be grown  in many zoos  to provide the more than  one kilogram of leaves that  each adult koala needs per day), and rarely  if at all  descends to the ground because it is such a  slow runner(from wild Australian dogs called dingoes ro from human hunters). As  kialas  are such  a great draw for visitors,  many zoos are trying to include  them  among their species.

eucalyptus US [ˌjukəˈlɪptəs]  .桉树.  fauna  [ˈfɔnə]      n.（某地区或某时期的）动物群
flora  [ˈflɔrə] n.植物区系；植物群； zoological  [ˌzəʊə'lɒdʒɪkl]  adj.动物学的

   Mother koalas   give  birth to babies only  every other year. These young ones,as  with other  marsupials,spend a period of  time inside the mother's  "pouch"  before venturing out into  the world. In the case of the koala, this pouch  is located below and in back of the mother; the  small koals can climb out directly  from the puch and onto  the mother's  back  before learning to  feed  and feed for  themselves. With  all other  marsupials, the pouch is located in the front , perhaps most famously with  the kangaroo, where  the "joey"  can  sometimes be seen  popping  its head out of it soft, warm pouch to survey  the world  about it safely. 


   pouch US [paʊtʃ] n.荷包；邮袋；小袋子；（有袋目动物腹部的）育儿袋


   Until the 1980s, zoologists feared  that the  koala might go the way of some other   rare marsupials. Just  as their eucalyptus  habitat  was  being destroyed to make room  for the ever-increasing suburban Australians, diseases peculiar to koalas began  to  take their toll.  Combined with weak or non-existent  laws against the hunting or poaching of  this national treasure, the koala seemed doomed to extinction.  Today , the koala has climbed back from the brink  of extinction and is  thriving again.  Its main  enemy today is forest fires. This  slow-moving mammal  cannot move quickly enough to escape the  deadly fires  which  perennially ravage the land. With  more  land being  set aside to  protect this  and  other  Australian species, however, the future  of much of this special land's  animal wealth seems secure.

   All animals deserve man's  protection, but some  animals seem to attract the attention they  need. The  koala  , one of  the symbols of the great Down Under, is one of  these . Holding a  koala is fun, educational, and inspiring. If  Australians could cooperate to save  this special species, mankind  should be able  to prevent the extinction   of all other  animals, too.
   

** Lesson 23   Paper's Long March     long  march     n.【史,事】长征  
  Remember  when the  1980s  brought us  the first  wave  of the modern  computer and  electronics revolutions ? At  that  time , heady young technocrats foresaw  "the  paperless office."  It was claimed that paper would  become  a  thing of the past  as  everyone  would access  all information needed form video  screens.

  wave      美: [weɪv]   n.波浪；波动；风潮；射流  .波动；挥；起伏；挥手[
revolution     美: [ˌrevəˈluʃ(ə)n]   n.革命；剧烈的变革；回转；转数
heady     美: [ˈhedi]  冒失 adj.强烈作用于感官的；使兴奋的；使有信心的；冲动
technocrat     美: [ˈteknəˌkræt]   n.专家治国论者；(高级)技术人员
foresee     美: [fɔrˈsi]   v.预知；有先见之明
access    美: [ˈækˌses]  v.进入；〈正式〉到达；【IT】获得或储存(电脑文件) n.通道；入口；机会；权力
  technocrat      美: [ˈteknəˌkræt]   n.专家治国论者；(高级)技术人员
  The  reality today is quite different.   More   paper than even   is being  used in offices, schools,  and residential homes.  One's  first  possession in life is a  birth certificate, made  of paper.  Childhood  immunizations are recorder on  paper  and kept in the doctor's  office and at home. What  would  school be like  without  paper? Paper  follows most people  throughtout  their  education  and into  their  working life. Wedding  invitations  and marriage certificates are printed on paper, as are virtually  all major life passages and  social occasions. Finally,  a  death certificate on paper  will continue  to be  around long after the  person  named   on it. Perhaps  the one  item  which  defines  modern  civilization  more that  any other is  paper.
  reality  美 [riˈæləti]      n.现实；事实；实际情况；实际经历
  residential  美 [ˌrezɪˈdenʃ(ə)l]     adj.适合居住的；生活有关的,住宅的；需要在某地居住的；提供住宿的
  certificate  美 [sərˈtɪfɪkət]      n.证明；证明书；合格证书；文
  immunization 美 [ ˌɪmjʊnəˈzeɪʃən]     n.免疫；免疫作用；免疫法；免
virtually     美: [ˈvɜrtʃuəli]   adv.几乎；实际上；事实上；虚拟
occasion 美 [əˈkeɪʒ(ə)n]      n.时刻；机会；诱因    define  美 [dɪˈfaɪn]     v.规定；(弄)明确；为…下定义
possession  美 [pəˈzeʃ(ə)n]     n.拥有；具有；属地；个人财产

  The  world  paper derives from papyrus, the name  of a  riverside plant similar to grass, from which an   ancient form  of paper was used in Egypt and   Mesopotamia. It could be  argued  that  these  empires were  made  possible by the use  of official  records on papyrus. However, paper  as we know it today  has its origins in the Han  dynasty of China . In  about A.D. 105 , an  official in the imperial court produced the  forebear of what has become  today  the world's  most indispensable product.  The  art  of paper making reached  westwards to Baghdad, Iraq in the   8th  century at the  height of the  Islamic culture. From  there  it entered Europe , where is  was polished into its contemporary   form during the 19th   century.
   derive  美 [dɪˈraɪv]      v.得到；追寻起源；推论；由来
papyrus  美 [pəˈpaɪrəs]   n.纸莎草； riverside  美 [ˈrɪvərˌsaɪd]      n.河畔；河岸
ancient  美 [ˈeɪnʃənt]      adj.古代的；古老的；很老的 。 imperial  美 [ɪmˈpɪriəl]       adj.帝国的；
the imperial court  朝廷  court UK: [kɔː(r)t]n.法院；宫廷；院子；求婚
forebear  美 [ˈfɔrˌber]      n.祖先；祖宗
indispensable  美 [ˌɪndɪˈspensəb(ə)l]      adj.必不可少的      n.不可缺少的人或物
Islamic  英 [iz'læmik]      adj.穆斯林的  网络伊斯兰教；伊斯兰教的；
polished  美 [ˈpɑlɪʃt]      adj.抛光的；磨光的；擦亮的；优雅的      v.“polish”的过去式和过去分词
contemporary     美: [kənˈtɛmpəˌrɛri]   adj.现代的；当代的；当时的

   Paper can be  made from any plant,  but trees  are the best source of cellulose  for paper production.  In fact, earlier forms of paper were made from processed cotton waste and rags,  but trees contain a better proportion and type  of cellulost  than  any other plant. In countries with  a deficiency of  forest land,  other  natural fibers such as  sugar cane pulp ,bamboo, cereal straws , flax, and hemp are  used.  Today's paper  and paper product mills rely  on a steady inflow of wood  logs or chips. In  the United  States alone,  the  paper and paper  products industry   is  worth  more  thant  US$80 billion , with  world  production  well  over  1000,000,000  tons annually.
  cellulose 美 [ˈseljuloʊz]    n.纤维素； earlier forms  早期 
cotton 美 [ˈkɑt(ə)n]    n.棉；棉布 .   waste  美 [weɪst]    n.垃圾
contain  美 [kənˈteɪn]      v.包含；含有；控制；容纳 .  proportion   美 [prəˈpɔrʃ(ə)n]      n.比例；部分；
deficiency  美 [dɪˈfɪʃ(ə)nsi]      n.缺乏；不足；缺陷；    
fibers是fiber的复数  fiber  美 [ˈfaɪbər]     n.〈美〉同“fibre”      网络纤维；光纤；纤维发射器
cane 美 [keɪn]      n.手杖；藤条；藤杖；（某些植物，如竹或甘蔗的）茎     v.   pulp   美 [pʌlp]     n. 渣 纸浆；髓；浆状物
 cereal  美 [ˈsɪriəl]    n.谷物；   straw 美 [strɔ]      n.稻草；(吸冷饮用)麦秆状吸管           flax  美 [flæks]      n.亚麻；亚麻纤维
  Mills 美 [mɪl]  paper product mills  造纸工厂 ;  a steady inflow 固定 
  logs 圆木， 日记  ；  chips 片  ；油炸土豆条；炸薯条
  annually 美 [ˈænjuəli]     adv.一年一次地
   deforestation 美 [diˌfɔrəˈsteɪʃ(ə)n]      n.毁林；滥伐森林；烧林     网络森林砍伐；砍伐森林； 
  
    Everyone  knows what  paper is , since  most people  use at   least  one sheet of it a day , but few  people  stop  to consider the different kinds  of paper  available to us  today . Office  workers   are well aware  of the many  kinds of  paper they   use,  such as  regular typing or computer printing  or copier paper.  They  also  come into  contact with bond, a high-grade paper used for  important documents. It is  thicker and more durable than other  forms of paper.  Book paper comes in at least four different  finishes, These may be  seen in books, magazines, brochures,  and calendars, Newsprint is used  for newspapers and some  magazines or books, while kraft  paper  is used for shopping    bags.  Paperboard is seen  daily as  bo lunch containers,  cardboard boxes, and even  building materials. Finally ,sanitary  paper has been developed for use in tissue paper, paper toweling, and paper napkings. Carbon paper, postcards, and envelopes are also dialy  use items  made  of  paper.  Even a tea  bag  is made of paper!

sheet  美 [ʃit] n.薄板；床单；纸张；报纸    aware 美 [əˈwer]        adj.意识到；知道
regular   US [ˈreɡjələr] ；经常的；常规 规则的；有规律的
copier  US [ˈkɑpiər]      n.复印机；誊写笔；誊写[复写]员；抄录者 Web影印机；打印机
bond  US [bɑnd] n.债券；键；结合  铜    v.使牢固结合； grade  US [ɡreɪd]      n.品级；水平；评分等级；阶段      v.分等；给
thick  US [θɪk]      adj.充满；弥漫；厚的；粗的      n.最厚[粗]的部    durable  US [ˈdʊrəb(ə)l]     adj.耐用的  form 纸张
finish  US [ˈfɪnɪʃ] 完成, 材料  kraft US [kræft]      n.牛皮纸  .  paperboard   ['peɪpəˌbɔd]    na.卡纸板
material  US [məˈtɪriəl]      n.材料；资料   sanitary   US [ˈsænɪˌteri]      adj.卫生的；环境
tissue paper, paper toweling, and paper napkings
tissue  US [ˈtɪʃu]      n.绵纸；（人、动植物细胞的）组织；手巾纸
toweling  US [ˈtaʊəlɪŋ]      n.毛巾；手巾；纸巾
napkin  US [ˈnæpkɪn]      n.餐巾(纸)；   item US [ˈaɪtəm]      n.项目；(新闻的)一条；(戏剧的)节目 adv.同上      Web物品；道具；
    
    Paper and its products seem endless ,but conservation of even the  abundant resource of  trees is in everyone's interest.  Recycling of paper   and better  designed pulp and paper factories have helped decrease waste.  Many  offices encourage   the use of  both sides of  a piece of paper, for example , and  students  or private  organizations  sometimes collect  old newsprint to send to reprocessing center. By conserving paper, the average paper user in his lifetime  can  save at least one tree from being  felled. As valuable as trees  are,  and as valuable as paper is , everyone  should  cooperate  to use this essential  commodity wisely. 
    conservation  US [ˌkɑnsərˈveɪʃ(ə)n]      n.保护；保持；
    abundant      US: [əˈbʌndənt]       adj.大量的；丰盛的；充裕的
decrease  US [dɪˈkris]  .降低；减少；缩小  pulp US [pʌlp] n.纸浆  .降低；减少；缩小；减弱
fell  US [fel]   adj.邪恶的；残暴的  v.砍伐（树   ; newsprint   US [ˈnuzˌprɪnt]     n.新闻纸；白报纸
    essential  [ɪˈsenʃ(ə)l]      n.要点；要素；实质；必需品 adj.完全必要的；必不可少的；
    commodity  US [kəˈmɑdəti]     n.商品；产品；货物；商品经济      Web日用品；品名；  wisely 精明地；明智的
    
**  Lesson  25 Earthquake Precautions 
    17分后没声音了
   Bam! The  bathroom door  slamming against the wall woke me out of a  sound  sleep. Groggily wending my way  in the  dark  to the bathroom, I secured  the door  latch to make sure I would have no  further  interruptions of much-needed  sleep. I  then  lumbered back into  bed  and started to drift off .
precautions是precaution的复数
precaution  美 [prɪˈkɔʃ(ə)n]  n.预防；预防措施 v.使提防；预先警告
slam  美 [slæm]  v.（使…）砰地关上；用力一放；使劲一推；猛劲一摔
sound sleep n.熟睡    groggily 美 ['grɒdʒɪlɪ]  adv.摇摇晃晃地
wend  美 [wend]  v.  走
secure 美 [sɪˈkjʊr]  v.担保；获得；保证；得到
further  美 [ˈfɜrðər] dv.进一步；此外；更远；而且  v.促进；增进
drift 美 [drɪft]  v.漂移；漂流；  drift  off 睡着

  Not for long. My body , the bed and the whole bedroom  began shaking. After a few  confused  and frightening seconds, I realized   "Earthquake!" "Big one" I added, noting  that  the neighborhood dogs had joined in the weird sounds the hills around my house were making. Within  moments I was  out of  bed and on my feet, contemplating leaving the house. "I'll wait", I comforted myself. "Even these  big ones  pass in a few seconds."
contemplate  美 [ˈkɑntəmˌpleɪt]  v.考虑；沉思；思量；思忖  网络注视；凝视；打算

  This one wouldn't , It kept coming;everything was  shaking and trembling,  rattling,  I heard  a pane of glass crash  onto the floor. The walls of the house and the  things attached to them   seemed to heave, not just shudder.    I then  noticed that  the street lights had failed and  my heart was pounding harder than  when I used  to lift  weights. I acknowledged my fear.
  
tremble  美 [ˈtremb(ə)l]  v.颤抖；发抖；颤动；哆嗦
rattle  美 [ˈræt(ə)l]  n.拨浪鼓；一连串短促尖厉的撞击声；咔嗒声  v.（使）发出咔嗒咔嗒的声音；（运行时）发
pane     美: [peɪn]   v.嵌玻璃于；用染色小布片拼做(衣服)   n.（一片）窗玻璃
attached to 网络附属于；隶属于；  美: [əˈtætʃt] 
heave 美 [hiv] n.举；起伏；拖；拉  v.拖；（强烈而有节奏地）起伏；
shudder  美 [ˈʃʌdər]  n.战栗；强烈的震动；剧烈的抖动  v.战栗；强烈震动；剧烈抖动
pound     美: [paʊnd]  v.捣碎；反复击打；连续砰砰地猛击；咚咚地走  n.英镑（英国货币单位，等于 100 便士）
acknowledge 美 [ək'nɒlɪdʒd] v.承认；公认；认为；感谢  网络公认的；承认告知；得到承认的

   Realizing  that  there  was  no time  to flee  the house, I simply  waited and  waited.  The   nearly  one-minute long temblor finally subsided, and my  reasoning came back to me.  All  was  well, or  well enough. I walked unsteadily to another room  and looked  outside. A neighbor with  flashlight was checking on his and others'  homes for damage.
   flee      美: [fli]   v.逃跑；迅速离开
subside      美: [səbˈsaɪd]   v.沉降；消退；平息；减退
reasoning      美: [ˈriz(ə)nɪŋ]   n.推理；论证；推想；理性的观点
unsteadily  美[ʌn'stedɪlɪ] adv.拿不准地；不安定地；跌跌撞撞地
damage  美[ˈdæmɪdʒ]      v.      损坏; 伤害      n.    损坏; 伤害; 不良影响; 损害赔偿金

    I know  it had been a major quake, though not  centered  where I lived. The next day  I  learned that a 7.6 Richter-scale earthquake had devastated the lovely  rural communities  of central  Taiwan.  For  the next  few  weeks,  everyone's  life  was  centered around the quake due  to  the constant media coverage and electricity rationing.
    
Richter scale  美 ['rɪktə skeɪl]      na.【地】里氏地震强度表
devastate  美 [ˈdevəˌsteɪt]      v.摧毁；彻底破坏；毁灭；使震惊
rural  美 [ˈrʊrəl]      adj.乡村的；农村的；似农村的
community  美 [kəˈmjunəti]      n.社区；社团；社会团体；居民
constant  美 [ˈkɑnstənt]      n.常数；常量      adj.连续发生的；不断的；
ration 美 [ˈræʃ(ə)n]      n.定量；（给战士或食品短缺地区的人提供的）定量口粮；正常量；合理的量      v.配给；限定…的量；定量供应

    Taiwan  is but  one of  many places situated along the "Ring of Fire"  encircling nearly  half the globe around the Pacific   Ocean. Constant  volcanic and earthquake action occurs here.  sometimes with  cataclysmic results.  In   this  century alone. major  earthquakes have taken  more than  one million lives.  Many  more have been  injured and made homeless. The economic 经济, social, and personal costs  are immeasurable.

situated  美 [ˈsɪtʃuˌeɪtɪd]      adj.位于；坐落在；处于…状况；处境…
encircle 美 [ɪnˈsɜrk(ə)l]      v.包围；围绕；环绕
cataclysmic  美 [ˌkætəˈklɪzmɪk] 剧变
injured 美 [ˈɪndʒərd]      n.伤员；受伤的人；伤兵
immeasurable  美 [ɪˈmeʒərəb(ə)l]     adj.不可估量的；无限的；无穷的

Over  the pass  quarter century,  many  countries in earthquake-prone areas have  begun to educate their   citizens on how to take  appropriate precautions for earthquakes. The  following  list has been  compiled from experience.

appropriate 美 [əˈproʊpriˌeɪt]      v.拨款；剽窃；挪用 adj.恰当的
precaution  美 [prɪˈkɔʃ(ə)n]      n.预防；预防措施

    Before the earthquake:
    Prepare an "earthquake kit"(地震包))  near   everyone's  bed; these kits should  include  drinking  water, a flashlight with fresh batteries , and dry food.
    Place an extra pillow, blanket, or quilt near  the bed  to be placed over  the head during the earthquake and  for  warmth if  trapped  afterwards.
      trap    美: [træp]     n.圈套；牢笼；嘴；（捕捉动物的）陷阱    v.吸收；使落入险境；使陷入困境；卡住  afterwards      美: [ˈæftərwərdz] adv.后来；以后
 
    During  the earthquake:
    If possible, get out of the building you are inside of and into a clear area.
    If  escape from  building is impossible, get away from windows  and doors; try  to  find shelter under   structural beams  or under   any heavy piece of furniture, like  a large  table  or bed.
shelter    美: [ˈʃeltər] n.避难所；庇护所；躲避；住所v.躲避；保护；庇护；遮蔽
structural     美: [ˈstrʌktʃ(ə)rəl]  adj.结构（或构造）上的
beam    美: [bim]  n.梁；道；(船的)横梁；【物】波束  v.闪光；眉开  urniture      美: [ˈfɜrnɪtʃər] n.（可移动的）家具
    After  the major  earthquak (remember that  aftershocks will occur):    aftershock     美: [ˈæftərˌʃɑk] n.【地】余震；余悸

    When  shaking ends   or subsides, turn  off tag lines.
    Leave the building   ( never use elevators)  quickly but  not in  a panic.   panic    美: [ˈpænɪk] adj.恐慌的；(恐慌心理)没来由的；过度的；牧人之神的 n.惊恐；恐慌 快速而不是恐慌
    If  uninjured, be ready  to assist rescue workers with  information  or labor.
       assist    美: [əˈsɪst] v.协助；帮助；援助；促
       labor    美: [ˈleɪbər] n.劳动；分娩；工作；人工v.劳动；苦苦地干；颠簸
    When  a  Big  One happens, there  is little anyone  can do. The  above  contingency   preparations,  however, could  make the difference between   life   and death. 
    ontingency    美: [kənˈtɪndʒənsi] n.可能发生的事；偶发（或不测、意外）事件 网络偶然性；意外事故；意外事

    


** Lesson   26   Berries: Nature's Natural Desserts

  The last child has left  the house for school. The  table is clean and neatly set, and the  coffee is brewing . The  cool orange juice  stands like a sentry over the tableware. Mother sits down , pours cereal into  a bowl, and sprinkles  it lightly with sugar. She  is then  ready for the final masterpiece. She  carefully spoons pre-cut ruby strawberries onto the mound of golden corn flakes. Pouring ivory-white milk  over the  concoction, Mother smiles to herself. An attractive, nutritious  breakfast fit for a  queen. 

  neatly  [ˈnitlɪ] adv.整洁地；巧妙地；整整齐齐
brew   [bru] v.酝酿；沏   .  sentry  [ˈsentri] n.哨兵  v.站岗；
pour  [pɔr] v.倒；倾注； . cereal  [ˈsɪriəl]  麦片    n.谷物；谷类植物
sprinkle  [ˈsprɪŋk(ə)l] v.撒；洒；点 .   masterpiece  [ˈmæstərˌpis] n.杰作；名著；
spoon  [spun] n.匙；一匙的.  mound  [maʊnd] n.土墩；小丘；小山岗；一堆
flake [fleɪk] n.鳞片；薄片；絮片   pour  [pɔr] v.注；倾注；倾吐；流
attractive  [əˈtræktɪv] adj.迷人的；楚楚动人的；吸引人 . nutritious  [nuˈtrɪʃəs] adj.有营养的；

 Most  people  around the world  are now familiar  with and can enjoy  strawberries, but few are familiar with  other more exotic berries, such as   the  gooseberry, blackberry, and raspberry. Indeed, even  fewer  people realize  what the word berry  technically refers  to.  The  berry of the botanist and  the berry of the public  are often  two  quite different fruits.

 exotic  [ɪɡˈzɑtɪk] n.舶来品；外来物；adj.异国风味的
 gooseberry  [ˈɡusˌberi] 醋栗  raspberry  [ˈræzˌberi]
technically  [ˈteknɪkli] adv.根据确切意义地；在专业上
refer to v.查阅；提到 botanist  [ˈbɑt(ə)nɪst] n.植物学家  botanic garden  植物园 

 Those  whose  specialty is plants define a berry  as s simple, fleshy fruit with a thin wall and many seeds.  Under this classification  are several surprises.  One  would  expect that cranberries are berries, of  course, but  less obvious  members of this class are dates, grapes, tomatoes, and even potatoes,  bananas, and  asparagus! Indeed , according to  botanists, some popular "berries" are not true berries at all.  Experts in plant life  consider the blueberry an  "inferior berry"  and  the  strawberry, raspberry, and  blackberry an "aggregate fleshy fruit."  However no matter  how  scientists call them , most people think of berries as small, round sweet, and  delicious fruits.

 those  [ðəʊz] adj.那些(的) . fleshy  [ˈfleʃi] adj.多肉的；肥胖的；肉质的
expect [ɪkˈspekt] v.期望；预 .  expert  [ˈekˌspɜrt]  专家n.内行；技师

  Berries such as strawberries , blackberries, respberries, and blueberries prefer cool and moist growing  conditions. Though they  rarely thrive in tropical conditions ,they  can  be  grown on the sides of taller  hills  and mountains there. Several  species  of wildlife  forage  for berries , the largest of these being  the bear.  Some  smaller mammals and  birds, too, enjoy  berries ,not to mention  people. Wild berries are noticeable smaller than  their  domesticated  cousins,  but many people  prefer the full,  rich taste of  freshly  picked forest berries.

moist  [mɔɪst]     adj.微湿的； rarely  [ˈrerli] adv.很少；罕有
thrive  [θraɪv] v.繁荣；茁壮成长；蓬勃;  tropical  [ˈtrɑpɪk(ə)l]adj.热带的；来
condition  [kənˈdɪʃ(ə)n] n.条件；情况  forage [ˈfɔrɪdʒ]  为食物 n.牧草；饲料；粮秣；粮秣的搜索[征发]
    v.搜索[征发]粮秣；给(马)吃草料
noticeable [ˈnoʊtɪsəb(ə)l]    adj.显著的；显而  
domesticate [dəˈmestɪˌkeɪt] v.驯养；栽培； cousins [ˈkʌz(ə)n]n.堂[表]兄弟；亲戚
    
 Besides being  a condiment on breakfast  cereals(麦片), are there  any other  uses  for berries? Westerners make good  use of their local fruits.  Jellies, jams, and preserves can be easily made with berries, gelatin,  and sugar. These  three  sweetend foods differ only  in the process used to make them. Jellies are made  from the juice of a fruit, jams from the thoroughly crushed fruit, and preserves from the  partially  crushed or cut fruit.  They are all equally delicious!

 condiment  [ˈkɑndɪmənt] n.调味料；  cereal [ˈsɪriəl]n.谷物
jelly  [ˈdʒeli]  v.使成为胶质；使冻 果冻
jams [dʒæmz]n.果酱；堵塞；拥   preserve  [prɪˈzɜrv]v.保留；保护；蜜饯
partially  [ˈpɑrʃəli] adv.部分地；

  Berries are also  used  in baked goods. Pies and tarts often  contain  berries as do many other  pastries. These  small  fruits are also  added into  cakes  and  even  breads, especially after drying. In  addition ,  the concentrated juice of berries can be used to  make cool   summer drinks. Concentrated further, various  syrups can be added to foods as diverse as  pancakes and ice cream. As flavorings, they  are often added to candies and chocolates. In Western  cuisine, life  would be less  sweet  and interesting  without  the humble berry.

  bake  [beɪk]  v.烤；焙干  tart  [tɑrt] adj.酸的；尖酸刻薄的；严厉的 n.〈英〉(果)馅饼
  pastry  [ˈpeɪstri]n.油酥面  糕饼
  addition  美 [əˈdɪʃ(ə)n] n.添加；增加；  concentrated  [ˈkɑnsənˌtreɪtəd] adj.决心要做的；全力以赴的；浓缩的
further 美 [ˈfɜrðər] adv.进一步；此外；更远；而且 v.促进；增
various  [ˈveriəs]     adj.各种不同的；  syrup  [ˈsɪrəp] n.糖浆；
diverse  [daɪˈvɜrs]     adj.不同的；相异的；多种多样的；形形色色的
flavoring  [ˈfleɪvərɪŋ] n.香料；调味 ；  cuisine  [kwɪˈzin] n.烹饪；菜肴

  For  some  people, though, berries   are best  eaten fresh. They  say that  after washing and  refrigerating,   simply place  a  generous  portion of berries into a cereal  bowl, add chilled milk , and top with sugar.  Enjoy ! As the season for berries is  usually in the summer and fall, this  snack  or dessert really hits the spot. For  those  who  do not live where berries grow  naturally and plentifully, these natural  dessert fruits  can be enjoyed while visiting those areas  luck  enough  to have  them.

  refrigerate  [rɪˈfrɪdʒəˌreɪt] v.冷冻；解
  generous  [ˈdʒen(ə)rəs] adj.慷慨的；大方的； portion[ˈpɔrʃ(ə)n] n.部分；（食物的）一份；分享的部分；分担的责任
    v.把…分成若干份（或部分
cereal  [ˈsɪriəl]    n.谷物；谷类植物；（常加牛奶作早餐用的）谷类食物
    adj.谷类制成的
chilled  [tʃɪld]  adj.冷却了的；冷淬过的；经过冷藏的
snack  [snæk] n.小吃；快餐；点心 hits the spot  恰到好处
spot  [spɑt]  n.斑点；污迹；污渍；脏点     v.看见；看出；注意到；发现
    adj.现货交易的；立即支付的  网络地点；场所(BBG)

复数：spots  过去式：spotted  现在分词：spotting  

    
**  Lesson  27  The Global Proliferation of  English
 感觉主要是查看不认识的单词上 感觉理解比以前更加好了 

 02:56 
Everyone  knows that  there  are more speakers  of Mandarin  than  other language in the world. Just  over one billion  people speak Mandarin as their native tongue. Compared  to  the nearly for  hundred  million native speakers of English. there would appear to be "no contest"  Yet , it  is just  as well-known that English  ,not Mandarin, is the international language. Given  these  statistics, how can this be ? Looking  more closely  at these and other facts reveals how English has become the world's  most widespread  language.

mandarin  [ˈmændərɪn]n.柑橘 普通话；  no contest  没得比 不抗辩；
statistics  [stə'tɪstɪks] n.统计学； widespread  [ˈwaɪdˌspred]     adj.分布广的；普遍的；大
reveal  [rɪˈvil]v.启示；揭露；透露

   The  history of written Chinese goes  back at   least 4 000 years.  that   of English  little more than   1 000 years.  The language  called English  is actually a  hybrid of Scandinavian  and  German  tongues   created by  immigrants  to England   in the 5th century  A.D.  Over  the next  500 years, English developed into several major dialects spoken principally on most of the island of England. With  continuous invasions by  more  Scandinavians and   the French over the  next few centuries,  the English language  received a fresh stimulus  of foreign  words, including Latin and Greek, the preferred classical languages in  educational  and political circles at that  time in Europe. English as a  principal language of literature did  not evolve until the 14th  century(Chaucer).  By   the 16th  century, English was in full bloom, both  in  literature as well  as in science.

   England,  referred to  as  Great  Britain by   this time, was  amassing  political, economic, and military  power  at breath-taking(惊人的) speed.  The Industrial Revolution of  the next century  required foreign  resources;  imperialism  gave the go-ahead  for Britain and  other European powers to not only take  what  they  wanted  from foreign lands  but to  lay  conquest to those lands as well.      Additionally, the rapid  social changes engendered by the change from agriculture to manufacturing meant a surplus of farm workers, resulting in a  waiting army of  the dispossessed  to emigrate to Britain's  newfound colonies. In the  17th and  18th  centuries, millions of Englishmen left their mother  country  for  North America.  In the  18th century,hundreds of thousands more set sail for Australia and New Zealand, as  well as  South Asia(the British Raj)  and Africa(primarily South Africa).  At  the height  of the British Empire, one-fourth of the world's  people  and lands  were living under the Union Jack. Thus, by  the close of the 19th  century English  rule had extended to the six principal continents(including British Guyana in South America.)
refer to      v.查阅；提到  amass  [əˈmæs]v.积聚；收集；
union jack n.联合王国国旗   military [ˈmɪlɪˌteri]  n.军事 军队
imperialism  [ɪmˈpɪriəˌlɪzəm] n.帝国主义；帝国统治 conquest  [ˈkɑŋˌkwest] n.征服；占领
additionally  [əˈdɪʃ(ə)nəli]adv.另外 rapid [ˈræpɪd] n.急流；滩流adj.瞬间的；快速的
manufacturing  [ˌmænjəˈfæktʃərɪŋ] n.制造业  engender  [ɪnˈdʒendər]  v.产生；
surplus  [ˈsɜrpləs]  n.盈余；顺差；剩余；过剩  dispossessed  [ˌdɪspəˈzest] n. 无产 被剥夺财产者
emigrate  [ˈemɪˌɡreɪt]v.移民；移  colony  [ˈkɑləni]n.殖民地；【
sail for  [seɪl] v.驶向  extended  [ɪkˈstendəd]  延伸    adj.延长了的
principal  [ˈprɪnsəp(ə)l] n.本金；委托人；资本；主角     adj.最重要的；主要的
continent [ˈkɑntɪnənt]     n.大陆；陆地


hybrid  [ˈhaɪbrɪd]  n.杂种；杂种动物；杂交植物 adj.杂种的；混合的；  Scandinavian  [ˌskændɪˈneɪviən] n.北欧(人)的；斯堪的纳维亚语(的
immigrant  [ˈɪmɪɡrənt]    n.侨民； dialect  [ˈdaɪəˌlekt]n.方言；语调
principally  [ˈprɪnsəp(ə)li] adv.主要地 invasion  [ɪnˈveɪʒ(ə)n] n.侵略；侵犯
prefer [prɪˈfɜr]v. 偏爱,推荐；建议；申请
classical  [ˈklæsɪk(ə)l] adj.古典的；经典的   
stimulus  [ˈstɪmjələs] n.刺激物；促进因素   evolve  [ɪˈvɑlv]     v.进化；演
bloom  [blum] v.盛开；开花；繁殖；   literature  [ˈlɪt(ə)rəˌtʃʊr]     n.文学；文学作品
political  [pəˈlɪtɪk(ə)l]  adj.政治的  political circles  政坛

  This first-ever domination of the gobe by one language is the primary reason for the  international  use of English  today. A second reason  lies in the rise  of the United States of America  as a  leading world  power  just  as Britain's  power began to fade. At  The  close of  the 19th century, the U.S. fought with Spain(in 1898)   After the U.S. victory, Spain  ceded the Philippines, Guam ,and Puerto Rico .resulting in the further  introduction of English  into Asia  and the Caribbean. After U.S. involvement in both  World Wars, despite Britain's  continued decline, English became  more commonly used  around the world, especially  in continental  Europe and Japan. Since 1950,  the  rapidly growing U.S. economy as  well as  its academic and scientific  excellence has insured that  English  remains the language of commerce  and intellectual intercourse. The world of entertainment,most notably Hollywood, has  also contributed to  the popularization of English .
 first-ever    adj.首次的  domination  [ˌdɑmɪˈneɪʃ(ə)n] n.统治；优势
 lies in the rise  of  在于崛起  lie  [laɪ] n.谎言；诺言 v.躺；在于
fade  [feɪd] v.逐渐消失逐渐消逝  cede  [sid] v.割让；让给；转让
despite  [dɪˈspaɪt]prep.尽管；即使 decline   [dɪˈklaɪn]v.下降；衰退
rapidly  ['ræpɪdli]adv.迅速；高速   academic  [ˌækəˈdemɪk] adj.教学的；学术性的
commerce  [ˈkɑˌmɜrs] n.商业；intellectual  [ˌɪnt(ə)lˈektʃuəl]n.知识分子；脑力劳动者 intercourse  [ˈɪntərˌkɔrs]    n.交际
contribute  [ˈkɑntrɪˌbjut]  v.捐献；投稿； notably   [ˈnoʊtəbli]    adv.特别；非常
  
  It is estimated that  at least  300 million people around the world are now studying or using English  as a second language, for purposes of education, employment , or personal interest, Some 75% of all international communications  are in English , and with  the rise   of  the Internet , it is  doubtful that  this  figure  will decrease any time soon.  At the dawn of the new  millennium, the world has  on international language, English.

estimate  [ˈestɪmət]n.估计
doubtful  [ˈdaʊtfəl]adj.怀疑；拿不定主意  decrease  [dɪˈkris]v.降低；减少
dawn  [dɔn]     n.黎明；曙光；拂晓；破晓 v.开始；变得明朗；开始清楚
  domination  [ˌdɑmɪˈneɪʃ(ə)n]  n.统治；优势；【生】显性化     网络支配；控制



  
** Lesson 36  Vancouver: Asia's   Newest city

 [vænˈkuːvə(r)
  What ?  Wait a  minute! Did I read that right? I thought   Vancouver was  in Canada,  not   in Asia.  Why  is the title of this  article "Vancouver: Asia's  Newest City" ?
  
  
