* Lesson 17 
  Precious  and  Semi-Precious Stones 
  "My! What a beautiful ring you're wearing!" This  compliment never fails to flatter and honor the lucky wearer
  of  the ring or other pieces of jewelry bedecked with  precious or   semi-precious stones. Most people  know the names of only some  fo these natural treasures. Many people  are surprised to learn that all  semi-precious stones can be bought  inexpensively, not  to mention that  the precious   stones can also be  had  for far less than  one imagined. However, as with  everything else  in life, you have to pay for the  best quality.   This  lesson will give the reader   both  information and tips on gem stones and their purchase.

precious  [ˈpreʃəs] adj.珍奇的；珍  compliment  [ˈkɑmplɪmənt] v.赞美称赞钦佩 n.称赞；赞扬
flatter [ˈflætər] v.奉承；讨好；向…谄媚；自命不凡   semi-precious /ˌsem.iˈpreʃ.əs/
jewelry  [ˈdʒuːəlri]     n.珠宝；首  bedecked  [bɪˈdekt]v.打扮
treasure  [ˈtreʒər]n.宝藏；财富；宝贝

  Just  what are  precious and  semi-precious  stones? The  word semi refers to anything   which is half or only partial; thus,  semi-precious stones are not precious,  by definition.  Actually, some high-quality semi-precious  stones are far  more expensive   than  some low-grade precious stones, so the terms "precious"  and  "semi-precious"  when   applied to  stones do not refer necessarily to  their  cost.


partial [ˈpɑːrʃ(ə)l] adj.部分的；不完整的 definition  [ˌdefəˈnɪʃ(ə)n] n.定义；清晰度
term  [tɜrm] n.条款；说法；
  
 All authorities on gems  agree   that the diamond, ruby, sapphire, and emerald are  precious stones.  Some  of these   experts include the opal as a fifth precious  stone while others   consider the pearl in this class. The   latter may surprise the reader,  but on reflection,  pearls, are also  a  kind  of stone,   though organically produced by certain  shellfish rather than  by geologic forces.

authority  [ɔˈθɔrəti] n.当局；权威 gem [dʒem] 宝石
diamond [ˈdaɪəmənd] n.金刚石；钻石 sapphire  [ˈsæˌfaɪr] n.蓝宝石；
emerald  [ˈem(ə)rəld] n.翡翠；绿宝石 opal [ˈoʊpəl] n.蛋白石；猫眼石
pearl  [pɜrl] n.珍珠；  latter  [ˈlætər] adj.（刚提及的两者中）后者的
reflection  [rɪˈflekʃ(ə)n] n.反映,沉思,深思 organically [ɔr'ɡænɪklɪ] adv.有机
certain  [ˈsɜrt(ə)n] adj.肯定； forces  军队  强制 

  Semi-precious stones include all other  stones considered  worthy of use in jewelry.  The  list of these  stones is very long;  suffice it  to say that  there  are several hundred  such stones, though most people are aware  of only a  couple  of dozen   of their  names, and  few  people can  readily recognize   more than   a  couple of any type  of stone at all.

suffice  [səˈfaɪs] v.足够；足以   dozen [ˈdʌz(ə)n] n.很多；（一）打；十二个；十来个
  
 Diamonds  and the colored stones ruby , sapphire, and  emerald are   often  considered the most expensive  among all stones.   This is generally  true, though quality is more important  than   stone type on  price. One   can  by a  "real sapphire" for US$10, but it  would be considered  not much better  than junk  to a jeweler.  These professionals  consider several  features  of     stones  before assessing   their value.  Carat size, or the weight  of  the stone(one carat = 200 milligrams) is one such feature, The  cut of  the stone is another.  Some  styles of cuts are considered  more costly than others; 此外 besides,  in the technical cutting  of  the gem  from the rough stone, great care must be taken not to cut into   or scratch  the surface of the finished stone.  The color  is also important, Rubies, sapphires, and emeralds, for instance, in order to fetch the hightest prices, must  be solid   colored  throughout,  Finally,  clarity or translucence, with  neither  streaking nor a "cloudy"   inner  appearance , also determines the final price. Gems  with these   qualities are far  and few between,  commanding nearly astronomical prices. A good jeweler advise  you of  these  characteristics and how to look for and evaluate them yourself.  Also  remember  that for a gem ring or pendant,  roughly 70% of the value of the piece   of jewelry is in the primary stone(s), with  the  rest in labor and metal.

diamond  ['daɪəmənd] n.钻石；菱形；
jeweler  [ˈdʒuələr]n.珠宝商  assess  [əˈses] v.评估；估算
karat  [ˈkerət] n.克拉  technical [ˈteknɪk(ə)l] adj.技术的；
rough  [rʌf]v.虐待；(铁蹄上)装防滑钉；粗暴地说；惹怒     n.草稿；（高尔夫

 Don't let anyone  sell you a  "good deal on a gem" on  the street. Go  to several professional  jewelers before   committing  yourself -- and  your money -- to a piece of jewelry with  precious  or semi-precious stones. Part of the value  of that  good  piece  of jewelry is the fact that  it can  be handed down  generation  after   generation with   increasing value. People  in all cultures never  seem  to tire  of  the brilliance of gems. 

 Specific names  of semi-precious stones are too  numerous  to mention, but  jade is well  known   to Chinese.  The  finest  jade (apple green in color)  commands very high  bids at auction.   The  trouble  with  semi-precious stones  is that   they are not  so hard  as precious  stones  so they  far more easily scratch, crack, or chip. If  this happens, the  hardest natural  stone, and  rubies  and  sapphires, the second hardest, are  actually rather hard  to deface.

 
